### ISSUE TITLE
Portals sometimes continue existing even after doors are closed

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#100]
title

either i iterate through every tardis getting their portals and killing them if their doors are closed
or i just mixin into the portal and give it a tardis to check up on and kill itself if its not meant to be there

second one sounds better icl

**Comment by Duzos** [comment]
tried to see if i could just save extra data to the portal
doesnt look like it

**Comment by Duzos** [comment]
mixin it is :(

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/9b080f6b-326f-4563-bd3e-ca98522b8e4a)
ai is just writing this whole thing for me

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/3afc9293-63a2-4e03-8eb2-33258be8dcf6)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/056c4315-8cf1-4ec9-b5ab-9785d2ebf8be)

idk what i doing
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/10c0cd4f-53c6-4643-9544-d55e34254503)
i copy creatiovuos using interface for setters 😭👍
idk why im documenting this im just bored
