### ISSUE TITLE
Fourth Doctors Console Addition

### ISSUE THREAD

**Issue by EL1987** [amblelabs/ait#104]
Another console or skin/alternative to the Hartnell console could be the 4th Doctor's console featured in episodes such as Pyramids of Mars and Planet of Evil. 
![forth doctor rotor pannels topdown view](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/a5cbaaec-35f4-433d-a185-38124f5ca8ab)
![fourth doctor rotor top](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/f4958697-c665-4302-b113-8713cd71692a)
![fourth doctor rotor bottom](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/81d94c17-b199-481e-8a11-26b06f899ce8)
![fourth console panel 6](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/4feb3de0-6e07-4b1c-856b-c15eecce7161)
![fourth console panel 1](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/1bb7e792-becb-4f31-b78d-7eb61323e7e4)
![fourth console panel 2](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/cc010f74-2703-41fc-a5a5-d96bbaa48556)
![fourth console panel 3](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/7b01aea7-c2e3-46bd-b300-79824b917d2d)
![fourth console panel 4](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/39a8dd77-ce38-4afb-a460-e185ead4373d)
![fourth console panel 5](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/104514946/b787d3bc-dc82-43a6-a588-6b02f1bfba35)
l

**Comment by Monsterwaill** [comment]
There is a skin on the hartnell for this console, as not many cannon consoles will be added, loqor decided that the best way to not add that many consoles while adding the classic ones too would be to reskin the hartnel to look like cannon ones. This may change in the future
