### ISSUE TITLE
Console Pos goes null when you relog

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#105]
Likely bc its either not being saved properly on server or isnt being synced back to client, to test just have a console down relog and then take off and you wont hear any sounds.

**Comment by Creativious** [comment]
probably a side effect of my network fix, I'll fix that

**Comment by Creativious** [comment]
it works for me are you using the latest version?

**Comment by Creativious** [comment]
@Duzos

**Comment by Duzos** [comment]
like when you relog inside the tardis

**Comment by Duzos** [comment]
dont seem to be getting this anymore, re-open if it occurs
