### ISSUE TITLE
Animations are broken on client

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#108]
they dont get told to setup correctly, probably because i put the listener for the packet in the ExteriorAnimation constructor, meaning they retain the last values
to test this, use the remote to demat a tardis and then use it again and you will see timeLeft is at 66 instead of the expected higher value, bc it doesnt get setup correctly

stop closing this issue, cus u havent fixed it

**Comment by Duzos** [comment]
sommet tells me the exterior block entity shouldnt be holding the animation anymore
just doesnt seem like its up to the job
( totally not because its always null on client )

**Comment by Duzos** [comment]
is sending a packet with the animation thaat baddd
it wooorkedddd

**Comment by Duzos** [comment]
i kms
using `MinecraftClient.getInstance().world` instead of the tardis bs fixed it pretty sure
makes sense but like bruuh
anyway now its broken on server woo
