### ISSUE TITLE
Proper way to change console stuff ( variants + main type )

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#117]
bc a stick and bone isnt good
put some ideas here lol

**Comment by SpartanGamezFTB** [comment]
Maybe through the monitor, in Desktop Settings there could be a Change Console, and when that's selected there could be a Variant Option below the name of the Type of console then when they click Apply they have the one they selected?

**Comment by Duzos** [comment]
yeah but id prefer to move away from doing everything in a GUI

**Comment by SpartanGamezFTB** [comment]
ik that it could then be 2 sliders on the hartnell console for example one for changing console type and one for console variant so its not in the gui perhaps

**Comment by Duzos** [comment]
console generator
