### ISSUE TITLE
somethings spamming markdirty, stop.

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#118]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/3a3cd413-ac60-406f-baeb-1066dfe30be0)

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/99ee1685-0b3d-4ae2-a41b-a01ce9ed510f)
thats not related

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/a1ed983d-bb59-42d4-b6d0-aa7d8bd0f94c)
its not to do with the tickers

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/3928c888-f166-4300-a486-a6c68d10a05e)
found it
duuuh im stupid
