### ISSUE TITLE
Power Outage while in Flight/When Landing

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#124]
**Mod Version:**
ait-1.1.29-1.20.1-beta

**Description:**
So while in flight i loaded up a waypoint to and then when i went to land, i ran out of fuel and her power went off, once i had enough power to turn her back on, i couldnt leave the tardis or take off.
PS: Was landing her inside herself using the waypoint cartridge i had saved - dont know if that helps or if it ties to every dimension/location

**Video:**
https://streamable.com/ooihz1

**Comment by SpartanGamezFTB** [comment]
also when i ran out of fuel and was in the process of landing inside using the cartridge, she went to -65 so i think her exterior didnt register anymore...

**Comment by Duzos** [comment]
should? be fixed
