### ISSUE TITLE
Gateway for Trouble/Griefers - Door Busted

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#125]
**Mod Version:**
ait-1.1.29-1.20.1-beta

**Description:**
When I have the door locked and turn off power, i can use the key to unlock/lock her inside as well as use an axe, but then i can use an axe to forcefully open her when power is off without a key while she's locked. [My enemies have a way to get inside without a key!]

**Video:**
https://streamable.com/tkrfss

**Comment by Duzos** [comment]
not a bug its a feature
yes we could have door controls work while the powers off but i like slamming doors open like a toddler
