### ISSUE TITLE
Anti-Gravs with Immersive Portals

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#128]
**Mod Version:**
ait-1.1.30-1.20.1-beta

**Issue:**
When the player turns on the anti-graves and decides to take a step outside to see where they are, they end up falling through a little gap of the immersive portals hitbox. Is it a hitbox? And whenever the player closes the doors and then stands on the edge of the TARDIS Exterior Doors and then opens them they fall aswell.

**Video:**
https://streamable.com/gjkpj0

**Comment by Duzos** [comment]
this is because collisions on the tardis get disabled while a portal is there, this needs changing, but is fine for now.
