### ISSUE TITLE
If you save an interior with a console that has it's entities, if you try to load the structure, it will crash the game as the entities are kept in the file itself.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#133]
Fix; just add a debug/creative only item that kills the entities to allow for the console to be saved properly.

**Comment by Duzos** [comment]
what about data pack people who won't know this idk

**Comment by Loqor** [comment]
not sure, they'll just crash i guess im not sure. i dont know how to make the nbt files avoid those entities; maybe mixin into the structure block and make it skip saving entities? idk

**Comment by Loqor** [comment]
the console entities, btw, not just entities

**Comment by Duzos** [comment]
what about this amazing thing called “don’t save entities”

**Comment by Loqor** [comment]
well people want their item frames and armor stands, wouldnt be fair to take that from em
fixed now by using a mixin to add a check for if its a console entity or not to return

**Comment by Suff99** [comment]
what the fuck solution is that

**Comment by Loqor** [comment]
a solution that works 😎 (im gonna fix it later its just for now tbh + i was lazy)

**Comment by Duzos** [comment]
he solved it the lowor way

**Comment by Creativious** [comment]
the yandere dev way
