### ISSUE TITLE
Cloaking w/ Immersive Portals Installed 

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#134]
**Version:**
ait-1.1.31-1.20.1-beta
immersive-portals-3.3.7-mc1.20.1-fabric

**Issue:**
When cloaking is engaged, and the player has immersive portals installed it causes this to happen 

![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/7b329b7d-a8cc-4f8e-93d5-1fbc2158c693)

**Comment by Duzos** [comment]
Unless i can find some way to change the alpha of the portals i don’t rly know what i can do here tbh

**Comment by Loqor** [comment]
That's actually intentional and canonical, surprisingly.
