### ISSUE TITLE
TARDIS lights surrounding area when power is off, and doesn't turn red with alarms on.

### ISSUE THREAD

**Issue by TheRealBb8fan1** [amblelabs/ait#136]
![2024-01-05_19 04 30](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/155708904/66160f39-aedb-4f3e-a2ed-02cd6e5a7bbd)
It bugs me personally.
![2024-01-05_19 10 13](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/155708904/ebf4be58-8e1a-421e-83d3-7ebb3d58f36c)

**Comment by Loqor** [comment]
The light isn't intended to follow either of those protocols.
