### ISSUE TITLE
Can't Enter Grown TARDIS

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#137]
**Version:**
ait-1.1.31-1.20.1-beta

**Issue:**
When the TARDIS is fully grown I cant seem to enter like there's an invisible barrier preventing me from entering

**Video:**
https://streamable.com/evxz5v

**Comment by Duzos** [comment]
loqor outright removing my temporary fixes to issues and then not fixing it 🥲

**Comment by Loqor** [comment]
Fixed in the newest release.
