### ISSUE TITLE
Random black screen.

### ISSUE THREAD

**Issue by CohenEmerald** [amblelabs/ait#138]
When on a single player or in a essentials world, When spawning a Tardis and opening the door, my Minecraft goes black and becomes useless, when closing the game it doesn't give me a crash report, I reload the world, the door opens but when walking in, same thing happens again, even when using the console sometimes it just happens.
video file was to big so had to use streamable to send a video of the issue happening

https://streamable.com/16ykln

**Comment by Duzos** [comment]
that is so weird

**Comment by Loqor** [comment]
if you're using any mods that are incompatible with immersive portals, get rid of them, or get rid of immersive portals.
