### ISSUE TITLE
Controls Disappearing

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#140]
**Mod Version:**
ait-1.1.32-1.20.1-beta

**Issue:**
When i change the interior, exterior, or even just leaving the TARDIS, the controls would disappear at random times sometimes.

**Video:**
https://streamable.com/l2k95v

**Comment by SpartanGamezFTB** [comment]
added a video

**Comment by Duzos** [comment]
should b fixed by @Loqor
