### ISSUE TITLE
servers are super slowagain :((

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#143]

**Comment by Duzos** [comment]
who would have guessed
that sendingthe entire tardis
to allthe clients
would lag out 
the clients??
wow
wowowoaw
we just ned to UPDATE the bits that havebeen CHANTGE DNOT EVERY SINGE L GOD DAMN THING
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Duzos** [comment]
@Loqor

**Comment by DrTheodor** [comment]
> who would have guessed that sendingthe entire tardis to allthe clients would lag out the clients?? wow wowowoaw we just ned to UPDATE the bits that havebeen CHANTGE DNOT EVERY SINGE L GOD DAMN THING AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

exactly what i did in my branch...

**Comment by Duzos** [comment]
i knowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww :((((((((((((((((
i no no wanna :(

**Comment by Duzos** [comment]
#168 beatch
