### ISSUE TITLE
Exterior Non-Existent when Entering Void

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#145]
**Version:**
ait-1.1.33-1.20.1-beta

**Issue:**
the bug where once shes in the void after hitting -1 or below, her exterior seems to be non-existent to where the player cant leave, cant fly, so pretty much is trapped and now has a "dead" TARDIS

**Video:**
https://streamable.com/404cjz

**Comment by SpartanGamezFTB** [comment]
yup

**Comment by SpartanGamezFTB** [comment]
you think there could be a way to save her if that does happen?

**Comment by Duzos** [comment]
Was working for end apparently
But has been causing issues while testing on server

**Comment by Duzos** [comment]
bump
