### ISSUE TITLE
Siege Mode TARDIS Disappears in Inventory.

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#146]
**Version:**
ait-1.1.36-1.20.1-beta

**Issue:**
When I try to pick up the TARDIS while in Siege Mode, it disappears from my inventory.

**Video:**
https://streamable.com/la6ebl

**Comment by TheRealBb8fan1** [comment]
I just had that same issue.

**Comment by Duzos** [comment]
same as #144, probably because of something i did

**Comment by SpartanGamezFTB** [comment]
Duzo did you ever figure out what you broke lol

**Comment by Duzos** [comment]
Nope i forgot

**Comment by Duzos** [comment]
bump
