### ISSUE TITLE
crashing using essentials and Immersive portals

### ISSUE THREAD

**Issue by CohenEmerald** [amblelabs/ait#148]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/147286807/f33fa486-0163-4374-b655-d6fa1f76082f)

version: 1.1.37

every time I'm on a essentials world with someone and someone opens the door I or whoever opens the door gets kicked and this error comes in

**Comment by Creativious** [comment]
Does it work fine in singleplayer?
And can you send over the logs from when you opened the door.

**Comment by SpartanGamezFTB** [comment]
> Does it work fine in singleplayer? And can you send over the logs from when you opened the door.
It does work in singleplayer

**Comment by TwilightEmerald** [comment]
[2024-01-12-6.log.gz](https://github.com/M-D-Team/ait-fabric-1.20.1/files/13926474/2024-01-12-6.log.gz)

this is the only log i have today i seem to be fine on singleplayer

**Comment by Creativious** [comment]
Can you test it in 1.1.36?

**Comment by SpartanGamezFTB** [comment]
> Can you test it in 1.1.36?

we did crash aswell in 1.1.36

**Comment by Creativious** [comment]
What version did this start?

**Comment by SpartanGamezFTB** [comment]
1.1.36 is when it started

**Comment by SpartanGamezFTB** [comment]
once we removed immersive portals we dont get this error.
