### ISSUE TITLE
No fading black effect when powers off/siege mode

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#149]
Version:
[1.1.37-1.20.1-beta](https://github.com/M-D-Team/ait-fabric-1.20.1/releases/tag/1.1.37-1.20.1-beta)

Issue:
When I turn the power off or enter siege mode, theres no fading black effect like there used to be. Once i click onto the monitor the lights come back. On older worlds and sometimes happens on newer worlds 

Video:
https://streamable.com/9m4rkv

**Comment by SpartanGamezFTB** [comment]
works on a new world

**Comment by SpartanGamezFTB** [comment]
nvm now it doesnt work

**Comment by SpartanGamezFTB** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/c0aeb6c3-e797-4352-af51-e34d8b32e3a7)

**Comment by SpartanGamezFTB** [comment]
once you click the monitor the lights essentially return

**Comment by SpartanGamezFTB** [comment]
on older worlds this happens and when i sometimes on newer worlds when i just place a tardis sometimes its just dark even though the powers on untill ive clicked the monitor

**Comment by Monsterwaill** [comment]
This is not a bug, but in fact a feature.

**Comment by Duzos** [comment]
This is a bug you buggy bugger
Broken bc of @Creativious in progress rewrite
Should be fixed when hes one

**Comment by Loqor** [comment]
In progress rewrite will fix.
