### ISSUE TITLE
Doors dont sync to clients on multiplayer

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#15]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/da6c1ea5-830a-4b25-818d-894f9c4dcdbf)

**Comment by Duzos** [comment]
needs retesting after uuid rewrite thign

**Comment by Loqor** [comment]
After the sync rewrite and the uuid rewrite (that im not sure is finished or if we did it at all) we just finished, this bug is no longer existent.
