### ISSUE TITLE
Monitor Preview

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#150]
Version:
1.1.37

Issue:
The Exterior is off within the monitor selection

![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/0e7350df-bb55-4e36-b0cc-5fec0f38f9d9)

**Comment by Creativious** [comment]
Is this a problem in 1.1.36?

**Comment by TheRealBb8fan1** [comment]
No, I have the same problem in the latest version.

**Comment by Creativious** [comment]
What version did this start?

**Comment by SpartanGamezFTB** [comment]
ive only noticed in 1.1.37

**Comment by Loqor** [comment]
The coral exterior texture was changed to be the off version, and since we don't render the emission map with the model in the monitor, it appears off. I will fix by adding said emission map.
