### ISSUE TITLE
Waypoint Cartridges Destinations

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#151]
Version:
1.1.37

Issue:
When I place a cartridge with the same coords as my current position it sets the destination to the TARDIS Dimension

Video:
https://streamable.com/4mjplp

**Comment by Duzos** [comment]
known about, its because when you try to set the destination to your own coordinates it moves the destination to your tardis interior

**Comment by Duzos** [comment]
It's not a bug, its a feature.
