### ISSUE TITLE
loqors a poo

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#155]

**Comment by Duzos** [comment]
i cba

**Comment by Loqor** [comment]
Don't close it omg

**Comment by Duzos** [comment]
no

**Comment by Loqor** [comment]
Leave it open, I'll do it

**Comment by Loqor** [comment]
I'm not dealing with this I'm gonna do it either way

**Comment by Duzos** [comment]
dont do it

**Comment by Loqor** [comment]
Bugger off mate I've been asking you to for like a week at most, I'm gonna do it, albeit I'm probably not going to mess with exterior/console variants just yet because that's a spaghettified mess

**Comment by Suff99** [comment]
https://github.com/Suff99/TardisRefined/pull/192

my unique idea


taken


![image](https://media.tenor.com/vaSdpDq4EHkAAAAM/i-cant-even-crying.gif)

**Comment by Portal3i** [comment]
Kill your self

**Comment by Duzos** [comment]
AIT when the TR
https://www.google.com/url?sa=i&url=https%3A%2F%2Fgiphy.com%2Fexplore%2Fmine&psig=AOvVaw20xQu0r1ME4MAgCtaqK3OK&ust=1705336435862000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCJi5m7Wn3YMDFQAAAAAdAAAAABAE

**Comment by Duzos** [comment]
https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/b1dcf409-919b-4c8e-b6b6-aa568ea750c1
