### ISSUE TITLE
Walking Through Interior Doors

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#156]
Version: 
1.1.38

Issue:
Can walk through All Interior Doors when there is no block behind them while doors are closed, was using Dev Interior to test

**Comment by Duzos** [comment]
known about, they dont have collisions ( is this on purpose? )

**Comment by SpartanGamezFTB** [comment]
oh i didnt know they didnt have collisions, nor if its possible

**Comment by SpartanGamezFTB** [comment]
Ill close this issue then
