### ISSUE TITLE
Immersive Portal w/All Interior Doors

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#157]
**Mod Versions:**
1.1.38
immersive-portals-3.3.9-mc1.20.1-fabric

**Issue:** 
When i open the interior doors, i see the TARDIS wall?...i dont know how to really word that...

**Video:**
https://streamable.com/2nqonx

**Picture:**
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/eaf1e78b-4864-44a9-90c5-2cd8fcc256c2)

**Comment by Loqor** [comment]
If you're using iris this is a common issue. Sodium also seems to cause it as well, I'm gonna ask quoteall about it

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/be512aec-e36a-477e-94a9-c25beccb9442)
i dont think its sodium mate

**Comment by Loqor** [comment]
That's bizarre. I asked quoteall about it. We will see I guess.

**Comment by Tr1ght** [comment]
Figured it out. For some reason when changing the chamaleon circuit sometimes the portal entity for the previous door is still present.

**Comment by Loqor** [comment]
Fixed in the most recent version by making sure that dadgum portal gets murdered

**Comment by YeeeeeahBoyee** [comment]
this issue seems to be back in 1.0.5
