### ISSUE TITLE
Crashing Trying to load into world

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#158]
Version:
1.1.38
immersive-portals-3.3.9-mc1.20.1-fabric

Version It Started:
1.1.37

Issue:
Whenever I logged out inside the TARDIS, every time I try to load back into the world I get this error. 

Log File:
[2024-01-14-3.log.gz](https://github.com/M-D-Team/ait-fabric-1.20.1/files/13933511/2024-01-14-3.log.gz)

Picture:
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/220193c1-70eb-4988-abcd-cae38efba9ec)

**Comment by Loqor** [comment]
You sent the wrong log i think

**Comment by Loqor** [comment]
it seems to be an issue with betterf3, update mod menu

**Comment by SpartanGamezFTB** [comment]
[2024-01-14-5.log.gz](https://github.com/M-D-Team/ait-fabric-1.20.1/files/13933591/2024-01-14-5.log.gz)

**Comment by Loqor** [comment]
bizarre, im going to push some fixes to release anyways so it should be fixed there

**Comment by SpartanGamezFTB** [comment]
hopefully
