### ISSUE TITLE
Serial Dimension issues

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#16]
Because client cant get any other world than the one its currently in, serial dimension and the findWorld method in tardisutil causes the game to disconnect
what i think should be done is create a client version of the class without the dimension var and findworld usages cus yeah
it only causes crashes because when it sends over the serial dimension to the client the client freaks out trying to get the world
id fix it but im tired

**Comment by Duzos** [comment]
@Loqor claims to have fixed
