### ISSUE TITLE
Z-Fighting on the coral console

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#160]
![2024-01-16_21 13 05](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/152225935/dccf7650-8cfa-4665-993f-3f2c358b8861)

**Comment by MaketendoDev** [comment]
![2024-01-16_21 15 29](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/152225935/cfe0b1f5-e081-42b1-b5f9-0cc5cf09d8f5)

**Comment by Tr1ght** [comment]
yes

**Comment by MaketendoDev** [comment]
yes

**Comment by Duzos** [comment]
yes
