### ISSUE TITLE
Tardis becomes null? Game Crashes

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#162]
Version:
1.1.39

Issue:
After a bit of being in a world, and i click on my sonic screwdriver or key, my game would crash. 

Latest Crash Report:
[crash-2024-01-17_20.33.49-client.txt](https://github.com/M-D-Team/ait-fabric-1.20.1/files/13971432/crash-2024-01-17_20.33.49-client.txt)

**Comment by Duzos** [comment]
same as #166
