### ISSUE TITLE
References to other pages on the wiki is broke

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#165]
Example - if you click on a link to `control entities`, instead of taking you to `https://m-d-team.github.io/ait-fabric-1.20.1/control-entities/` it takes you to `https://m-d-team.github.io/control-entities/`, missing out the repos url.

**Comment by Duzos** [comment]
Also noticed that this shows up when using the categories selector

**Comment by Duzos** [comment]
That commit fixes the comment i just left. 
Looking into the main part.
