### ISSUE TITLE
Lookup gets cleared

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#167]
This is on the so called [performance branch](https://github.com/M-D-Team/ait-fabric-1.20.1/tree/performance)

It's oddly specific, and I'm not sure what to do as this is what happens:

Boot up game -> join server -> everything is fine -> leave and rejoin -> the client recieves and adds the tardis to the lookup, but then on the render thread or something the lookup gets cleared(?) or is empty on that thread(?) -> Restart game -> Repeat

Genuinely no clue
Pretty sure its to do with threads getting desynced from eachother causing one to overwrite the other maybe
But we do do `synchronized` when we [add to the lookup](https://github.com/M-D-Team/ait-fabric-1.20.1/blob/performance/src/main/java/mdteam/ait/tardis/wrapper/client/manager/ClientTardisManager.java#L94)
Making it a `ConcurrentHashmap` doesnt appear to change anything either.

SOS

**Comment by Duzos** [comment]
I know the performance branch and how the networking is done and the entire code base sucks ass, just help me out

(talking to the voices fr)

**Comment by Suff99** [comment]
Don't fuck with threads 

I don't know this codebase but it sounds like you're clearing the lookup at some point and trying to reference it directly afterwards 

That or your lookup stuff is only executing on the server side and the client doesn't know enough 

You validated the client had nothing via breakpoints?

**Comment by Duzos** [comment]
`this.lookup.clear()` is only ran in reset which only called when the client's disconnect event is fired, but considering it only bugs out *after* you disconnect that could be the source of the issue.

i was pretty sure, i used a breakpoint in the sync method on client and the tardis definitely got added and then another breakpoint somewhere else and it was empty, but i also dont rly know how to use breakpoints but thats a google search for later

also i was bored and added a println to the client tick and it looks like youre just gambling for that lookup
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/ad44351a-5a73-4f5f-9c81-9ff85a5779b9)

**Comment by Duzos** [comment]
Removed the clear from reset for a sec and retried everything to see if anything changed, it didnt

**Comment by Duzos** [comment]
it looks like using `this.getLookup()` is somehow different to doing `getInstance().getLookup()` as the `this` one is populated, then the instance one isnt and then the this one is empty again
ill try only adding and editing the lookup using `getInstance().getLookup()` 
im desperate :sob:

![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/6ff2952c-a953-4ef5-83ef-c0ac59cb43e5)

**Comment by Duzos** [comment]
i dont even want to think about why that fixed it
what level of brain rot is this code

![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/22f66c04-acfe-4c58-98ca-a1d32a62b23b)

**Comment by Duzos** [comment]
oh wait im just insane and didnt ever create a new world or restart the server when making changes
it all works fine
