### ISSUE TITLE
Recursion Crash with Desktop Screen

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#175]
`nextDesktop` repeated in `OwoInteriorSelectScreen`

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/7bdf6e5f-e5ac-45ed-9dba-53203c67a90d)
BAHAHHA

**Comment by Duzos** [comment]
DesktopRegistry isnt getting synced
loqor was riiiiiiight booooo
