### ISSUE TITLE
Most consoles arent animating their individual levers properly

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#179]

**Comment by Duzos** [comment]
like if you have autopilot on the autopilot lever wont appear as down etc
dont know whether its an animation problem or a code problem

**Comment by Loqor** [comment]
i think the autopilot stuff and assorted properties doesnt sync to the render thread OR simply the model code is using the wrong getter.

**Comment by Loqor** [comment]
This was a merge issue. it's fixed now.
