### ISSUE TITLE
Console Animations Gone on Servers

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#186]
Version: 
[1.2.2](https://github.com/M-D-Team/ait-fabric-1.20.1/releases/tag/1.2.2-1.20.1-beta)

Issue:
All Consoles I'd assume. Tested Coral & Toyota controls:
Protocol 1912 & Protocol 116 animations are gone/don't work

Video:
https://streamable.com/3nxfn7

**Comment by Duzos** [comment]
issue #179

**Comment by Loqor** [comment]
This is incorrect. Fixed in latest release.

**Comment by Duzos** [comment]
does client definitely not have them in the rendering?
can you send like a pic of a breakpoint or a println
