### ISSUE TITLE
Siege Mode crashed me 

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#187]
Version:
https://github.com/M-D-Team/ait-fabric-1.20.1/releases/tag/1.2.2-1.20.1-beta

Crash Report:
[crash-2024-01-29_06.05.47-server.txt](https://github.com/M-D-Team/ait-fabric-1.20.1/files/14084009/crash-2024-01-29_06.05.47-server.txt)

**Comment by Loqor** [comment]
rare issue, does not occur normally, was due to corrupted/non-existent tardis file.
