### ISSUE TITLE
Flight stuff is really screwed

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#188]
Bullet points!!!!

- Flight time percentage doesn't tick, it just goes from 0 - 100 immediately when it hits the correct destination.
- Shake randomly either gets not triggered or is triggered even after the tardis has landed
- Sounds don't play correctly
This is definitely a sync issue because the good ol' fashioned loadTardis() method thats in the desktop settings screen reloads it!

**Comment by Loqor** [comment]
This also includes SINGLEPLAYER AS WELL, and doesnt sync (the tardis flight state + shake +sounds) until the monitor -> desktop settings is clicked

**Comment by Loqor** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/65447472/4cc1164c-6f4f-4904-b3ee-f5e9e4ea3e99)
@Duzos... lmaooo this was all it needed

**Comment by Duzos** [comment]
oops
better than the complex idea i was having to fix it

**Comment by Duzos** [comment]
loadtardis (take a guess here) loads the entire tardis from server
do not do

**Comment by Duzos** [comment]
flight time percentage was on purpose otherwise we’d be sending data every tick of flight and i didn’t rly want to do that so we’ll have to find an alternative

**Comment by Loqor** [comment]
weirdly enough thats not the case, on client its totally fine to do, it doesnt send a 2.3mb or a 1.3mb packet, it sends nothing, but ti was soemthing to do with syncing that i fixed it anyway

**Comment by Loqor** [comment]
> flight time percentage was on purpose otherwise we’d be sending data every tick of flight and i didn’t rly want to do that so we’ll have to find an alternative

speaking of, the easy way to do this is to communicate the length of time and do it like how we do the animation timer.

**Comment by Duzos** [comment]
well it only loads it if it doesn’t have it already

yeah send a start packet with the length or whatever
