### ISSUE TITLE
Tardis files get deleted on crash of server if they were being written to at the time of the crash.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#189]
It's bizarre, but when the server crashes or gets stopped (killed) unexpectedly, whatever file is getting written to will get deleted. just, completely deleted entirely, not corrupted just deleted

**Comment by Rasttny** [comment]
To be specific, whatever tardis data file in the .ait folder

**Comment by Loqor** [comment]
we can most likely take advantage of datafixers perhaps

**Comment by Duzos** [comment]
what would datafixers do here

**Comment by Duzos** [comment]
https://fabricmc.net/wiki/tutorial:datafixer:start
they won’t help in this situation

**Comment by Loqor** [comment]
fair dues, i was thinking we made an .old file (the last successful save of a tardis) like rasttny was talking to me about and then reference that if the current file gets kablooied

**Comment by Duzos** [comment]
yeah that’s good

**Comment by Duzos** [comment]
we can di that then
