### ISSUE TITLE
TimeLeft variable isnt set properly on Client

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#19]
on client when you demat the timeLeft variable in ExteriorAnimation starts to go into the negative as the setupAnimation for demat does not work properly for some reason
as a temporary fix i added a check to getAlpha and tick:
` if (this.timeLeft < 0)
            this.setupAnimation(exterior.tardis().getTravel().getState()); `

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/794a95c2-ce80-4cb8-a595-5aa2def7c993)
For the pulsating animation it gets stuck at 66 after remat and bugs out on demat
It seems like the client is starting and stopping at the wrong times and isnt resettings the timeLeft value properly, causing it to flip back over and freak out
this isnt fixed
que caca

**Comment by Duzos** [comment]
this causes the pulsating demat to be broken pls fix

**Comment by Duzos** [comment]
this got fixed
thanks for help @Creativious  <3
