### ISSUE TITLE
Tardis null error on server when anyone on the server is traveling

### ISSUE THREAD

**Issue by Chronosmage** [amblelabs/ait#196]
Hey, 

So im playing on the MD server - 

Whenever anyone is using a tardis to travel i get kicked with this error 

![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/67873575/22c5b1cc-3287-4711-852a-150b4741447a)

Any help ?

**Comment by Duzos** [comment]
what version of ait

**Comment by Chronosmage** [comment]
^ This seems to have been fixed in your latest update (as i was on the server ) Many thanks
