### ISSUE TITLE
Generated console won't cache after changing interior

### ISSUE THREAD

**Issue by TheLoneCrafter2017** [amblelabs/ait#209]
The title pretty much says it all. 

I am playing on version 1.2.31 of the mod, and it seems I cannot cache the console after changing the interior. 

It works when I initially spawn a tardis and I can cache any extra consoles I place down, but after changing it to any interior the main console can no longer be cached. 

I can also confirm this is within the confines of the main mod, as I tested this with no other mods loaded outside of fabric api and owo-lib. 

Below is a link to a short video to visually demonstrate the issue for your convenience:

https://drive.google.com/file/d/1COCwBaT0tWazK4_cuzOw8KCCvolueE6Z/view?usp=sharing

**Comment by Duzos** [comment]
bc verifiying consoles was removed
will be readded to fix this
