### ISSUE TITLE
Rewrite SonicItem

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#21]
Its just so bad i genuinely cant
Who let @Loqor code something on his own

**Comment by Suff99** [comment]
INT TO MODE? HAS MAN NEVER HEARD OF ENUM ORDINALS

**Comment by Loqor** [comment]
> INT TO MODE? HAS MAN NEVER HEARD OF ENUM ORDINALS


Ofc I have, i was too lazy to do it when writing it goddamn; it's not a permanent feature either, it was entirely testing

**Comment by Suff99** [comment]
dont worry loqor, im only messing around on these issues, we all have testing phases

**Comment by Duzos** [comment]
u wish it was an enum 
its not even that

im rewriting it anywya idc if its a test or not
