### ISSUE TITLE
Unlocking the TARDIS while it's reconfiguring

### ISSUE THREAD

**Issue by Nekopheus** [amblelabs/ait#210]
**Describe the bug**
It's possible to unlock the TARDIS while it's reconfiguring by shift-snapping.

**To Reproduce**
1. Have a linked gold key or better.
2. Start the interior configuration.
3. Walk outside.
4. Shift-snap.

**Expected behavior**
The door should not unlock.

**AIT Version:**
1.2.31

**Comment by Duzos** [comment]
Believe this is fixed
