### ISSUE TITLE
Tardim Glitch

### ISSUE THREAD

**Issue by Milvohouse** [amblelabs/ait#211]
**Describe the bug**
I'm using immersive portals mod, and it wont allow me to walk into the tardis with the tardim exterior

when using the Tardim exterior and some others from the top of my head. It didnt allow me to go through like a block was stopping me, but I was able to go through with spectator mode. The previous problems I've seen of this on other Tardis mods which was because of the 2 block height while other could go through the 3 block height tardises.

**AIT Version:**
ait-1.2.25-1.20.1-beta

**Comment by Duzos** [comment]
@Loqor portal placement issue
