### ISSUE TITLE
Error on making a world

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#212]
**Describe the bug**

**To Reproduce**
1. Go to 'singleplayer'
2. Click on 'create new world'
3. Click on 'create new world' in the create world options
4. Click on 'yes'
5. See error

**Expected behavior**
Loaded in the world

**Screenshots**
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/152225935/04f7a635-572a-49a7-b9d9-e1c9bca66534)

**AIT Version:**
1.2.44-1.20.1-beta

**Additional context**
Immersive Portals

**Comment by Duzos** [comment]
Playing with any datapacks?

**Comment by GeminiSlime** [comment]
Ive had the same issue, but with loading back into a world I already made. It will let me load back in if I disable fullscreen, but when I do load back in the tardis has deleted it self. Also If I was inside the tardis when I logged out before, when I log in after disabling fullscreen the door and the console are invisible.

**Comment by Duzos** [comment]
weirddd
