### ISSUE TITLE
Unable to do absolutely anything with my TARDIS. it is dead.

### ISSUE THREAD

**Issue by hurriedsue** [amblelabs/ait#213]
I can move it within 100 blocks, it keeps teleporting me to the wrong dimension when i leave the doors, the power doesn't work. the refueller doesn't work, and isn't visible anymore with HWYCA (or whatever the mod is lmao); the power won't turn on or off. i've been through the hard reset of using an artron collector panel and then putting artron into the TARDIS before setting it to refuel. nothing works.

I crashed, that is the only step that needs to be reproduced.

**Comment by hurriedsue** [comment]
I overwrote the TARDIS Mod when updating a modpack and it appears to have caused this.

**Comment by Duzos** [comment]
Issues like this should be fixed
