### ISSUE TITLE
java.lang error

### ISSUE THREAD

**Issue by ethanbennett0602** [amblelabs/ait#215]
when i first start minecraft i get the error java.land.illegalaccessError:No such constructor:
![Screenshot (63)](https://github.com/M-D-Team/ait/assets/140556469/9aa58950-f556-4d75-aba5-ab80fcab31f8)

AIT Version:
1.16.5

**Additional context**
happens no matter what i do with reinstalling and changing forge loader

**Comment by Loqor** [comment]
It's a fabric mod.. not forge. Please read into what the specifications are on the mod pages.

**Comment by Duzos** [comment]
They're on forge because they're trying to play the old forge 1.16.5 version

**Comment by ethanbennett0602** [comment]
i assume the 1.16.5 forge version doesnt work anymore

**Comment by Duzos** [comment]
Its unsupported, so I don't recommend using it
