### ISSUE TITLE
Basic Loyalty System

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#217]
Step by step how it should work and be implemented.
- [x] Implement LoyaltyHandler where you see fit, and I will come in and edit it if need be.
- [x] The values should be kept obfuscated so that people don't find ways to juke it, so make it confusing there.
- [x] Instead of the key system we're so reliant on, convert everything the key does to loyalty. It's better that way.
- [x] Relating to the key, perhaps possessing a key awards you loyalty when you keep it in your inventory (only to a limit, don't make it eternal).
- [x] When implementing it, we will have levels of loyalty; Owner (which is more like a pet owner really like it's just so loyal this person is their leader n stuff), Pilot (which there can be multiple, up to 6), Companion (which is controlled by loyalty AND by the security submenu, which allows different levels of loyalty to control the TARDIS with Isomorphic Security), Neutral (the default state) and finally Reject (the one the TARDIS hates, no matter how much you cajole it into trying to keep that person in the TARDIS, it will just kick them out. They can redeem themselves by gaining loyalty through other means).
- [x] With this loyalty system, it will also affect successful repair, time to repair, convenient crashing locations, and rewarding flight events (like vortex tunnels to desirable locations or xp rewards).

**Comment by Duzos** [comment]
id split this up into separate issues too but effort

**Comment by Loqor** [comment]
I'm thinking of delaying the loyalty system till after the first release and releasing it with upgrades and etc., makes more sense.

**Comment by Duzos** [comment]
agree

**Comment by Duzos** [comment]
@Loqor  done?

**Comment by Loqor** [comment]
Wow we actually did complete this
