### ISSUE TITLE
Unlocking System (Consoles, Interiors/Desktops, Exteriors)

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#218]
Step by step how it should be implemented.

(All unlocking systems will use data crystals (made from Zeiton and powered with Artron))

CONSOLES:
- [ ] We already have a cool locked effect in the console generator, but we should also find some way to display what the console is so that you know what you're looking for to unlock it.
- [ ] With that said, we need a better way to convey how you're supposed to switch consoles, I think hovering buttons will do the trick over using the sonic or blaze powder.
- [ ] It should be data packable, as in that each variant gets a randomly generated data crystal with a custom color (similar to spawn eggs or potions) and the name of the variant. They could also have configurable rarity or ways of acquirement, perhaps through the smithing table or some other kind of manufacture process (and loot from chests).
- [ ] They should be balanced, meaning that if you have copies and copies of the data crystal (which would be kinda difficult because to use them you have to imbue them with Artron basically) it would reward you with XP instead of unlocking something new, or you can distribute them to people who don't have that console/variant unlocked.

SIDE NOTE:
- [ ] For the hovering buttons, they should act like the control entities on the console. Well, they should be control entities just like on the console but for the generator. They should hover around but not too close to the hologram as to not clip into it, but they should also display (in like 2D sprite form that follow you) what changes the type, variant, and what the confirmation button is.

INTERIORS/DESKTOPS:
- [ ] For this one, I was thinking of it being much rarer than the console or exterior data crystals. These need to be imbued with artron and need an extra-strength fluid link to handle the transfer of information into the TARDIS, given that it is in fact a living machine it would make sense that the fluid links work like veins or the nervous system in tandem.
- [ ] With that said, interiors/desktops are also incredibly unbalanced due to the nature of Minecraft. It gives you blocks for free, so I think this process should be more arduous than the other ones, since the rest are purely cosmetic (except the console types, I'll get back to that later) versus this one actually providing you with both space and materials.
- [ ] With this complementary amount of blocks that we give the player, we should add a balance. I think a player must gather a block or item that is related to that interior and load that in with the data crystal, otherwise the interior will be purely white with no color (not to say that we need to let them do what the TARDIS plugin does, where you can color your interior, because 1. that's too much work and 2. kinda invalidates the point of a builder at that point); however, I think this is actually quite easy to do, and we just have  them named "slate" interiors.
- [ ] The console that is correspondent to that interior should NOT be unlocked with that interior. People have asked for that in suggestions often and I think that would be a pretty bad idea, especially with how I want all this unlocking stuff to go. So just don't do that basically.

EXTERIORS:
- [ ] Alright, so this is the fun part. For unlocking different exterior types, I think they should be found or, actually, better idea, constructed the way you might think of it. Perhaps you build the exterior and then save it to the data crystal, and then you need to have the block/item that correlates to the variant (or perhaps a variant modifier that you find in the nether because we have those nether variants and soon end/sculk variants) and that's how you unlock different types and variants. This one is simple but also super fun.

**Comment by Duzos** [comment]
unlocking exists with loyalty
