### ISSUE TITLE
console nerd shit loqor put on the trello

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#22]
When the console type is changed, it changes all consoles in the entire tardis; we need to instantiate the console type to the console itself to allow for multiple consoles with different types at the same time; multiple consoles already sync and work together as well. - @Loqor

**Comment by Suff99** [comment]
Guys please just connect the repo to trello so these auto post 😭

**Comment by Duzos** [comment]
WHAAT how do i do that omg

**Comment by Duzos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When the console type is changed, it changes all consoles in the entire tardis; we need to instantiate the console type to the console itself to allow for multiple consoles with different types at the same time; multiple consoles already sync and work together as well.](https://trello.com/c/BekFymh2/80-when-the-console-type-is-changed-it-changes-all-consoles-in-the-entire-tardis-we-need-to-instantiate-the-console-type-to-the-con)

**Comment by Duzos** [comment]
this is the same as #33 but  with fancier words..
