### ISSUE TITLE
Unlocking System (Exteriors)

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#220]
Step by step how it should be implemented.

(All unlocking systems will use data crystals (made from Zeiton and powered with Artron))

**Comment by SpartanGamezFTB** [comment]
maybe like when sonic is in scanning mode say in an Ancient City, it would start being a sonic detecting a chip(s) in chests that when u then put the sonic in the offhand and right click the chip it would load it into the sonic [consumable so no sharing] and then the player takes it back to the tardis, inserts it into the console sonic slot and then she would play a sound that would tell the player she has unlocked something.

**Comment by Duzos** [comment]
noo
