### ISSUE TITLE
MOVED TO SEPERATE ISSUES

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#221]
- [ ] This is minor but the sonics just need to have the lights on when they're being right-clicked held down, not just always on.

Big things as well:
- [ ] Sonic should be placed in the keyhole/somewhere on the exterior to denote to the TARDIS to repair the current interior instead of just wiping everything and initiating a change. The interior shouldn't change until the time is up either, there should be a grace period where it just has alarms going off and whatnot until it changes.
- [ ] We need to implement the sonic port for each console to charge it. We should implement a battery for the sonic.

**Comment by SpartanGamezFTB** [comment]
When the player has no loyalty and uses the TARDIS Sonic Mode, it will only set the coordinates, and the player will have to go and take off.

When the player's loyalty is high enough and they use the TARDIS mode for the sonic, the TARDIS will disengage their handbrake and turn on Auto Pilot.

When the player's loyalty meter is higher, the TARDIS will come to the player within a 256 block radius [Whats currently in the latest build]

**Comment by SpartanGamezFTB** [comment]
Since a player can use a Sonic Screwdriver without it being linked, i think it could be really cool that when a Non-Linked Sonic is in TARDIS Mode and when right clicked on a block for setting the Coordinates, the player can take it to any TARDIS and when they place the Sonic into any Sonic Port, it will then load those Coordinates

**Comment by Duzos** [comment]
https://github.com/M-D-Team/ait/issues/231

**Comment by Duzos** [comment]
https://github.com/M-D-Team/ait/issues/232

**Comment by Duzos** [comment]
https://github.com/M-D-Team/ait/issues/233
