### ISSUE TITLE
Upgrades/Component System

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#222]
Step by step how it should be implemented.

- [ ] Each TARDIS component should have an item and recipe. You craft each one individually, and assemble them within the machine that you need to create, and they all combine to make the link between the TARDIS engines (which are separate from everything else and not something we should add) and the console, that being:
- [ ] Dematerialisation Circuit (if this is not in the TARDIS, the only thing it can do is fly in the real world, it cannot dematerialise nor can it go to different dimensions. It will hate you for doing this.)
- [ ] Different kinds of fluid links (will explain in a later comment most likely)
- [ ] Others I can't think of right now

Upgrade System

Tright gave this fantastic idea of canisters that contain different upgrades, and you can only select one of the two (although all are unlockable by endgame), and they have their own pros and cons.
- [ ] Canisters (I will let Tright explain it in a later comment)

**Comment by Tr1ght** [comment]
Canisters (inspired by the Deus Ex augmentation mechanics) are essentially components that you can either craft and/or find in structures. These, when inserted into the TARDIS matrix (be it the console or engine) would allow you to install one of two upgrade options. Once a certain upgrade is installed, further upgrade canisters of the same type will then be used to level up the installed upgrade. There will be a set number of slots for each upgrade, and once max level is reached in that slot it will no longer be useable.

![IMG_2196](https://github.com/M-D-Team/ait/assets/58902744/d49ad2e8-55e9-4c58-ae29-9936334b6d79)

**Comment by Taygamer** [comment]
I Think There should be Different Canisters and They Can Make it a higher tier upgrade or Lower tier And like a success chance type thing so the canisters can Fail and Not upgrade it or succeed and Upgrade it Going from what @Tr1ght Said

**Comment by Duzos** [comment]
yapping

**Comment by Duzos** [comment]
replaced by subsystems
