### ISSUE TITLE
Junk TARDIS/Console TARDIS/Blocks Attached to Exterior/Physical Vortex

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#227]
Step by step instruction.

Background Information:
In the show, we see the (I forget what doctor) use the console by itself as a standalone TARDIS. This, of course, is kind of impractical, since he needed a whole freaking nuclear power plant to just power a short trip. In the 11th Doctor episode "House", we also see something similar; the TARDIS supplies energy to a "junk" TARDIS, which consists of a few panels, a floor and a small tin roof with a console that barely looks like it works.

- [ ] Make consoles in the Overworld work like potential TARDISes, but only for a short time before being destroyed entirely. Let blocks be placed around them (perhaps use block display entities with barrier blocks for collisions?)
- [ ] Must jumpstart the TARDIS with Artron and some other function.
- [ ] Have those blocks dematerialize with the console (must have the component inserted into the console for it to work)
- [ ] The vortex will fade IN for anyone currently inside of the bounding box of the junk TARDIS for dematerialization/rematerialisation.
- [ ] Must have shields to avoid getting sucked into the vortex stream and having your junk TARDIS lost entirely.

To achieve this practically, we will need:
- [ ] Components (demat circuit, shields)
- [ ] Some kind of system for block TARDIS stuff
- [ ] Physical vortex
- [ ] Sucking out into said vortex
- [ ] Console acting like a standalone TARDIS when enchanted(?) with Artron energy and a boost from.. something idk lightning?

**Comment by Duzos** [comment]
vortex mod clone

**Comment by TTaxer** [comment]
i mean it is the same concept as the vortex mod, but imagine it with the consoles we already have in the mod.
this idea could have so much potential

**Comment by Duzos** [comment]
what i said
