### ISSUE TITLE
Tardis Not Enterable, blocks are preventing entering tardis and sometimes does not rebuild itself

### ISSUE THREAD

**Issue by NateslPlayzzz** [amblelabs/ait#228]
Upon creating a tardis in multiple worlds (sometimes it works) The tardis will not be enterable, and sometimes it will be enterable, but upon rebuilding the interior, you will not longer be able to enter, and it wont be rebuilt. This isnt the case for ALL worlds sometimes though. you can get in however with the interior command. Sometimes restarting the world fixes bug sometimes it does not. This happens in custom maps, superflat, and RARELY default worlds.

**To Reproduce**
1. Create a New World
2.  Create a Tardis
3. One of two things will happen either you can or cannot enter due to something blocking entry.
4. If you can enter, rebuild the tardis, it will not let  you enter
**Expected behavior**

Should be able to enter the tardis and rebuild it normally but cant, and it only works on some occasions . Restarting world sometimes fixes.

**Screenshots**
Example in a superflat world, demonstrated it is blocked as well by punching the invisible blocks inside doorway.
![2024-02-23_12 12 10](https://github.com/M-D-Team/ait/assets/69865617/d1dc1d9d-d603-4d99-87ba-401983071a3f)
![2024-02-23_12 12 16](https://github.com/M-D-Team/ait/assets/69865617/5695c2b5-e866-44fc-a105-eb563bbbdec4)

**AIT Version:**

Latest  1.3.1 - 1.20.1 beta from feb 22nd 2024

**Additional context**

Im playing with the compatible immersive portals and sodium compat. which is latest immrsive portals version, and sodium 1.5.3

**Comment by Loqor** [comment]
Issue with Immersive Portals. Will be fixed soon.
