### ISSUE TITLE
Demat Animation on Multiplayer

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#23]
I dont really know how to explain this, just watch this clip

https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/13d8a16d-4726-4a7a-ab57-a6f840403b1e

from what i can tell, for some spaghetti reason, the demat animation on the exterior is bugged and doesnt run unless you right click the exterior which starts it and also for some reason fixes the console animations (???) (who cooked this spaghetti, me or loqor)

**Comment by Duzos** [comment]
think this might be because of how tardistravel gets the tardis but im not sure
as i found another issue where if you leave and rejoin while in flight the tardistravel has a null tardis

**Comment by Suff99** [comment]
why is the tt capsule from a PS2 game

**Comment by Duzos** [comment]
bceause its fire
also this is fixed
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/f8608ed8-33f2-4919-95db-cf684e8a271e)
squad
