### ISSUE TITLE
Door teleports player to incorrect location

### ISSUE THREAD

**Issue by EchoOfThePlanes** [amblelabs/ait#230]
**Describe the bug**
Occasionally after a TARDIS has landed, attempting to exit will teleport the player to the location the TARDIS had just been prior to flight.

**To Reproduce**
1. Enter TARDIS
2. Fly to another location
3. Attempt to exit TARDIS
Player is occasionally teleported to previous landing location.

**Expected behavior**
When exiting a TARDIS after landing, should appear in the actual location of the exterior shell instead of its previous location.

**AIT Version:**
1.3.1-1.20.1-beta

**Additional context**
Was playing on a multiplayer server with the following mods:

[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Star Wars Planets Ad Astra! [Forge/Fabric] (by TathanDev)](https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra)
[Reborn Core (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/reborncore)
[Things [Fabric] (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/things-fabric)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Doctor Who - Regeneration (by Jeryn)](https://www.curseforge.com/minecraft/mc-mods/regeneration)
[YUNG's Better Nether Fortresses (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses-fabric)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Bewitchment (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/bewitchment)
[Plethora Peripherals (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/plethora-peripherals)
[Modern Dynamics (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/modern-dynamics)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Adventures In Time (by duzo_)](https://www.curseforge.com/minecraft/mc-mods/adventures-in-time)
[Immersive Portal Gun (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/immersive-portal-gun)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Tech Reborn (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/techreborn)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[DimensionalDoors (by DimensionalDevelopment)](https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors)
[Packet Fixer (by TonimatasDEV)](https://www.curseforge.com/minecraft/mc-mods/packet-fixer)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[Immersive Portals (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
[Friends&Foes (Fabric/Quilt) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Rascal, Tuff Golem) (by Faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Explorify – Dungeons & Structures (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/explorify)
[YUNG's Better End Island (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island-fabric)
[VeinDigging (by Nyakorita)](https://www.curseforge.com/minecraft/mc-mods/veindigging)
[Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
[Tempad (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/tempad)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[PantheonSent (by Lucraft)](https://www.curseforge.com/minecraft/mc-mods/pantheonsent)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[NBC Heroes (by Massattack52)](https://www.curseforge.com/minecraft/mc-mods/nbc-heroes)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Ultreon Devices Mod (by XyperCode)](https://www.curseforge.com/minecraft/mc-mods/devices-mod)
[Palladium 🐿️ (by Lucraft)](https://www.curseforge.com/minecraft/mc-mods/threetag-palladium)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[EpheroLib (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/epherolib)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Regrowth (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/regrowth)
[YUNG's Better Jungle Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples-fabric)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)

**Comment by Loqor** [comment]
Immersive Portals issue. Will be fixed soon.
