### ISSUE TITLE
Sonic to initiate repair

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#232]
TODO:
- [x] Sonic placing into keyhole of TARDIS or equivalent 
- [x] This starts repair
- [ ] Interior reset should only occur when the timer is finished
- [x] During the grace period just alarms should be going off

**Comment by TheRealBb8fan1** [comment]
Would this mean that if you caused the TARDIS to take significant damage from crashing, it would have a chance to change the interior?

**Comment by Duzos** [comment]
shh

**Comment by TheRealBb8fan1** [comment]
😈

**Comment by TheRealBb8fan1** [comment]
Understood.

**Comment by Loqor** [comment]
Will not change interior for now, makes it easier on us all for this time.
