### ISSUE TITLE
Sonic Batteries

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#233]
TODO:
- [x] Artron battery on sonic ( make it implement the ArtronHolder interface ) 
- [x] Port control for holding sonics ( reference [Waypoint Handler](https://github.com/M-D-Team/ait/blob/main/src/main/java/mdteam/ait/tardis/data/WaypointHandler.java) )
- [x] Recharge sonics in port, drain from tardis'

**Comment by Duzos** [comment]
Not merged yet

**Comment by Duzos** [comment]
Nvm u merged it without a pull request
pls in future make one and wait for approval
