### ISSUE TITLE
Environmental Effects and Overgrown State

### ISSUE THREAD

**Issue by TheRealBb8fan1** [amblelabs/ait#234]
I think that the environmental effects would make the TARDIS feel more lifelike and the environment would have an effect on it as well. My idea for the overgrown state is that when it overgrows, it will turn off power as long as it's overgrown. Environmental effects could be like snow, sand, burned, and wet.

**Comment by Duzos** [comment]
cool but pls use the template provided

**Comment by TheRealBb8fan1** [comment]
Ok, sorry!

**Comment by Loqor** [comment]
Planned already.
