### ISSUE TITLE
Positioning of Sonic Screwdrivers (Console)

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#237]
Consoles:
- [x] Have every sonic be rendered onto the console at the position of the Sonic Port control.
- [x] Instead of using a switch statement with the values in the renderer, have an overridden method in the parent class that each console type (type, not variant) overrides instead and returns the necessary value.
- [x] Datapack positioning array.

**Comment by Duzos** [comment]
why is `Datapack positioning array.` needed tho as all datapacks use the same base model

**Comment by Loqor** [comment]
@Duzos different exterior variants will have different keyhole positions because its just a texture.

**Comment by Duzos** [comment]
oh this is for exteriors too
split it into two issues maybe

**Comment by Duzos** [comment]
but for the consoles, why?

**Comment by Loqor** [comment]
oops I didn't mean to make it variants for consoles too, lemme split them up idk why I keep combining them

**Comment by Duzos** [comment]
ok
