### ISSUE TITLE
Cleanup Code

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#239]
- [ ] Make sure everything that needs to be a Text.translatable() should be a Text.translatable() (replace literal() with translatable()).
- [x] Remove loggers that are unnecessary.
- [x] Remove printlns.
- [x] Remove unnecessary comments, swears, etc.
- [x] Format code with the thing that Theo told us that I can't remember right now (it's a key combo).

**Comment by Duzos** [comment]
ok

**Comment by Duzos** [comment]
you do translatables
