### ISSUE TITLE
power goes off

### ISSUE THREAD

**Issue by TheDJGamerYT** [amblelabs/ait#240]
**Describe the bug**
the power goes off randomly and you have to run like 50 commands to get it back on

**To Reproduce**
1. Enter a TARDIS and wait

**Expected behavior**
the power should go off and you cant flip the switch

**Screenshots**

**AIT Version:**
1.3.2

**Additional context**
regeneration

**Comment by Duzos** [comment]
you sure you just didnt run outta fuel?

**Comment by Loqor** [comment]
Ran out of fuel.
