### ISSUE TITLE
Real World Flight

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#243]
Plan is to have a complex real world flight, in which you pilot the exterior from the tardis console. eg throttle will speed you up in the direction youre going, xyz to set direction to travel in, handbrake will stop you. things like that
I think while im getting it setup itll be alike to Dalek Mods, but I don't want the final product to be that way and I am definitely going to be changing it

Beta will be like
- [ ] Control to enter rwf
- [x] Alike to creative flight
- [x] RWF entity? or maybe make the player themselves the tardis idk

Final product
- [ ] Control to toggle rwf
- [ ] Some way to choose travel direction
- [x] RWF entity

**Comment by foxy-commentating-bread** [comment]
amazing

**Comment by Duzos** [comment]
@Loqor  done?

**Comment by Duzos** [comment]
not planned for a while
maybe 1.3.0? entire idea needs redoing.
