### ISSUE TITLE
More TARDIS directions

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#244]
This will add more directions to the TARDIS, for example NORTH EAST, NORTH WEST etc

TODO:
- [x] Store directions as float
- [x] Clamp them to those specific directions
- [ ] Convert all Minecraft Directions to custom directions
- [ ] Fix issues with converting old ABP data to new ABP ( minecraft dir -> specific dir )

**Comment by Duzos** [comment]
LOQOR completed this
