### ISSUE TITLE
Can not re-enter tardis from certain exteriors. (immersive portals)

### ISSUE THREAD

**Issue by J0riUnderscore** [amblelabs/ait#245]
Whenever I set the tardis exterior to certain models, specific exteriors behave differently when using the Immersive portals mod.

whenever I use the Capsule, Police, and Classic exteriors the interior and exterior create a functioning immersive portal that renders on both sides and I can move freely in and out the tardis.

whenever I use the K2 Booth, and Moyai exteriors neither the interior doors nor the exterior renders an immersive portal and the door just teleports my player between the interior and exterior.

whenever I use the Renegade, TARDIM, and Plinth exteriors the interior and exterior create an immersive portal that renders on both sides but while I am able to exit the tardis, whenever I walk up to the exterior, I am unable to enter. there is an immersive portal on the exterior but for what I guess is some sort of collisions problem because when I enter spectator mode, I am able to fly through the portal into the interior but I am never able to re-enter on survival nor creative mode.

**To Reproduce**
1. Load a world with the AIT mod along with the Immersive Portals mod
2. Create a tardis and from the monitor change the exterior model to any of the exteriors listed (at the time of this post all of the one currently accessible in the mod)
3. attempt to walk out the doors of the tardis and back inside.

side note I noticed the portal created for the Renegade's interior doors renders the portal too tall for the doorway model:
![2024-03-03_15 53 44](https://github.com/M-D-Team/ait/assets/162057787/a8a002a0-ef8c-4334-a648-ccffecf7cd53)

**FABERIC LOADER AND MOD VERSIONS**
fabric-loader-0.15.6-1.20.1

owo-lib-0.11.2+1.20
immersive-portals-3.3.9-mc1.20.1-fabric
fabric-api-0.92.0+1.20.1
ait-1.0.3-1.20.1-release

**Comment by Loqor** [comment]
This is fixed in 1.0.4
