### ISSUE TITLE
When the antigravs are disabled and you're floating, they don't cause the TARDIS to fall until the exterior chunk is loaded.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#248]
Self-explanatory. Should just update the exterior block with a packet and we should be fine.

**Comment by Duzos** [comment]
Because creativious removed force chunk loading instead of fixing it.

**Comment by Loqor** [comment]
Yes, I assumed this was the case - I'm pretty sure if we just use WorldOps.updateIfOnServer() we should be alright. If not, oh well.

**Comment by Duzos** [comment]
Also why'd you assign me

**Comment by Loqor** [comment]
it auto assigns

**Comment by Duzos** [comment]
ok
