### ISSUE TITLE
Sonic doesn't interact with all types of candles

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#250]
**Describe the bug**
The Sonic Screwdriver doesn't interact with all types of candles just the default one

**To Reproduce**
Sonic any candle colour variant than just the default candle

**Expected behavior**
It just won't interact / light the candle

**Screenshots**
![Candle not lighting](https://github.com/Loqor/ait/assets/152225935/46a5c0e3-fc5d-4576-8396-454ac7c8f3d1)

**AIT Version:**
AIT (Release) 1.0.4 - 1.20.1

**Comment by Loqor** [comment]
should be fixed in the next release
