### ISSUE TITLE
[IDEA] Rename the Zeiton Block

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#253]
**Is your feature request related to a problem? Please describe.**
there is ofc i feel like the Zeiton Block should be named Block of Zeiton as this feels not very minecrafty as it isn't the same to the Block of amethyst. 

**Describe the solution you'd like**
rename the Zeiton Block to Block of Zeiton.

**Comment by foxy-commentating-bread** [comment]
perfect suggestion mod is trash without this change

**Comment by MaketendoDev** [comment]
yes
