### ISSUE TITLE
Server Crashes When Entering The Tardis

### ISSUE THREAD

**Issue by HolyAraHippo** [amblelabs/ait#257]
**Describe the bug**
A friend of mine is hosting a minecraft server at the moment, and the mod overall works, up until one tries to enter their tardis, after which the server crashes.

**To Reproduce**
1. Download  "All The Mods 9" for 1.20.1
2. Add Sinytra's Connector Mod (disregard the forge version part) and "forgified fabric API"
3. Add Adventures in Time and owo-lib
4. Open a Server with those mods
5. Join the server
6. Grow tardis
7. Enter tards
8. Game Crash

**Expected behavior**
Entering the Tardis Interior

**Screenshots**
-

**AIT Version:**
1.0.4-1.20.1

**Additional context**
It's being played with every ATM 9 mod and from 2-5 players at a time.

Additionally, 2 crash logs, to maybe pin it down a bit better:
https://mclo.gs/zgF6TSq
https://mclo.gs/XiMi862

Thank you in advance for looking into this.

**Comment by Loqor** [comment]
We do not actively support Sinytra connector nor any compatibility with other forge mods.
Thank you.

**Comment by HolyAraHippo** [comment]
Ah alright then, sorry :/
