### ISSUE TITLE
[Bug] Immersive Portal Positioning 

### ISSUE THREAD

**Issue by Ravinpanachi** [amblelabs/ait#258]
**Bug**
When I am using the TARDIS and go to the exact coordinates (Example, X:250 Y:250 Z:250) which would be in the air. Now when I turn on the Anti Grav and drops the Tardis down to a solid block. Whats weird is that when I look through the Tardis Doors with Immersive Portals, I am still at Y:250 but the Tardis is placed down at Y:40. So all that happens im going through the TARDIS doors but im exiting an immersive portal 200 block above where the TARDIS intentionally is. 

The next problem really isnt much of a big issue, but more of a visual bug. When the TARDIS goes to a different dimension by accident. I try to summon the tardis back with the Sonic Screwdriver. But when I look through the doors and turn around, its captured the image of the TARDIS from the Dimension it was accidently in. 

**To Reproduce**
1. Set Tardis Coordinates High into the air
2. Switch on Anti Grav to drop Tardis down to solid block
3. Open doors and go through to see if Immersive Portal is still linked to previous high Y value. 

**AIT Version:**
ait-1.0.4-1.20.1-release.jar

**Comment by Duzos** [comment]
Same as #261 i presume

**Comment by Loqor** [comment]
Kinda fixed kinda not oh well
