### ISSUE TITLE
[Bug] Immersive Portals door bug

### ISSUE THREAD

**Issue by nitrogenez** [amblelabs/ait#261]
## Description
With the Immersive Portals mod installed, if a door is open you not only can still break it,
but the portal itself stays open, so the only way to get rid of the portal is to place the door down again, close it, and then break the door.

## Steps to reproduce
1. Get to the TARDIS interior
2. Open the door
3. Break the door

## Expected behavior
The door shall close the portal on break, I assume this might have something to do with a callback.

## Versions
+ ait: `v1.0.4-1.20.1-release`
+ immersive-portals: `3.3.9-mc1.20.1-fabric`

## Mods installed

+ `entityculling-fabric-1.6.2-mc1.20.1`
+ `enhancedblockentities-0.9+1.20`

Immersive Portals sends a message in the chat that `entityculling` is incompatible with it.

**Comment by Duzos** [comment]
Known - is an issue with TardisPortal since we moved away from mixin
