### ISSUE TITLE
[Suggestion] Add configs for Regeneration handler

### ISSUE THREAD

**Issue by AndreLeria** [amblelabs/ait#262]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware, there is currently no configuration behind RegenHandler's actions dealing with regenerating when inside the TARDIS. While the special functionality is cool, being able to disable the interior randomly changing (to prevent loss of what's built) would also be nice.

**Describe the solution you'd like**
Add configuration to enable/disable the Regeneration mod special functionality.

**Comment by Jeryn99** [comment]
Probably better removed

**Comment by MidnightWolfang** [comment]
> Probably better removed

I like the function, I think it's pretty cool and a nice surprise when the interior changes, but to people like me who have built a lot of things inside the TARDIS this config would be pretty good, but I wouldn't say better removed cuz I'm sure there are people who likes it

**Comment by Jeryn99** [comment]
It's mainly because I don't feel comfortable with this mod interacting with mine anymore - and yes the concept of loosing your stuff because you made a mistake is horrific

**Comment by MidnightWolfang** [comment]
Well, if that's the case, then it's better to have it removed indeed. (Also you regeneration mod is amazing, I love it! Thanks for it! 💕)

**Comment by Jeryn99** [comment]
Since for some reason, I have write access, I have removed the code myself in this commit https://github.com/Loqor/ait/commit/cc19d2439c52073e5fc942d2e052ed3a2dd516a7
