### ISSUE TITLE
[Bug] Void crash

### ISSUE THREAD

**Issue by nitrogenez** [amblelabs/ait#263]
**Description**
Tardis falling into the void in the overworld causes the game to crash. At least in siege mode.

**To Reproduce**
1. Enable Siege Mode
2. Dig a hole to the void under TARDIS 
3. Enjoy your crashed game

**Expected behavior**
TARDIS teleports to a nearby land or just dematerialises, like Hostile Action Displacement System.

**AIT Version:**
v1.0.4-1.20.1-release

**Comment by Duzos** [comment]
crash report ?

**Comment by nitrogenez** [comment]
@Duzos forgot to get it first time. Will attach it to the next comment when I get home.

**Comment by nitrogenez** [comment]
For some reason I couldn't replicate the bug, for now closing the issue as not planned.
