### ISSUE TITLE
[CRASH] Missing DateUtils.java

### ISSUE THREAD

**Issue by Wowjox** [amblelabs/ait#264]
**Describe the bug**
The bug would instantly crash the server when placing a tardis from creative and when the tardis grows to 100%, but after the server restarts, she would be there where we placed her. It also makes where she'll use up her fuel as if we didn't fill her up.

**To Reproduce**
1. Entering a server with AIT
2. Plant TARDIS or Spawn one from creative
3. See error

**Expected behavior**
The whole server would crash but after restarting it, Tardis would be present

**Screenshots**
crash report- https://drive.google.com/file/d/1ReBTcLXWLePpg9uKws_TlnUH1rOQehBx/view?usp=drive_link 

**AIT Version:**
1.0.4 - 1.20.1

**Additional context**
It works fine in singleplayer, its only when playing on a server the crash would occur.

**Comment by Wowjox** [comment]
yea sure, sorry for the inconveniences

---- Minecraft Crash Report ----
// Sorry :(

Time: 2024-03-20 00:48:40
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/http/client/utils/DateUtils
	at mdteam.ait.tardis.data.StatsData.markCreationDate(StatsData.java:134)
	at mdteam.ait.tardis.wrapper.server.manager.ServerTardisManager.create(ServerTardisManager.java:181)
	at mdteam.ait.core.item.TardisItemBuilder.method_7884(TardisItemBuilder.java:109)
	at net.minecraft.class_1799.method_7981(class_1799.java:272)
	at net.minecraft.class_3225.method_14262(class_3225.java:363)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.utils.DateUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.5.0-26-generic
	Java Version: 17.0.10, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1753488640 bytes (1672 MiB) / 5368709120 bytes (5120 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8986.60
	Virtual memory used (MB): 7512.73
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -Xms5G -Xmx12G -XX:+UseG1GC
	Fabric Mods: 
		additionaladditions: Additional Additions 6.0.1
		additionallanterns: Additional Lanterns 1.1.1
		additionalstructures: Additional Structures 4.2.1
		advancednetherite: Advanced Netherite 2.0.3-1.20.1
		adventurez: AdventureZ 1.4.20
		ait: Adventures In Time 1.0.4-1.20.1-release
		alternate-current: Alternate Current 1.7.0
		amendments: Amendments 1.20-1.1.9
			mixinsquared: MixinSquared 0.1.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		aquamirae: Aquamirae 6
		aquatictorches: Aquatic Torches 1.0.1
		arcanelanterns: Arcane Lanterns 8.0.0
		architectury: Architectury 9.2.14
		ash_api: Ash API 3.0.2+1.20.1
		axesareweapons: Axes Are Weapons 1.7.3
		azurelib: AzureLib 2.0.20
		backpacked: Backpacked 2.2.7
		bakingdelight: Baking Delight 0.1.0-1.20.1
		balm-fabric: Balm 7.2.2
		barteringstation: Bartering Station 8.0.0
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beekeeperhut: Friends&Foes - Beekeeper Hut 2.0.0
		betteradvancements: Better Advancements 0.3.2.162
		betterarcheology: Better Archeology 1.1.6-1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.5
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		betterladdersmod: Better Ladders 0.0.2.1.20.1
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		bettertridents: Better Tridents 8.0.1
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		boatbreakfix: Boat Break Fix 1.0.11
		bookshelf: Bookshelf 20.1.9
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.5-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		botarium: Botarium 2.3.3
		bountiful: Bountiful 6.0.3+1.20.1
		cakedelight: Cake Delight 1.20.1-v3.0.2
		campfirexp: Campfire XP 1.1.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		catalogue: Catalogue 1.8.0
		cell: Cell 2.1
		cerbons_api: Cerbons API 1.1.0
		charmofundying: Charm of Undying 6.5.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chunksending: Chunksending Mod 1.20.1-2.8
		chunky: Chunky 1.3.138
		chunkyborder: ChunkyBorder 1.1.53
		chunkyextended: Chunky extended 2.1.1
		cleancut: CleanCut 6.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.39
		comforts: Comforts 6.3.5+1.20.1
		companion: Companion 5.1.0
		completeconfig: CompleteConfig 2.5.3
			completeconfig-base: completeconfig-base 2.5.3
		configured: Configured 2.2.3
		connectivity: Connectivity Mod 1.20.1-5.4
		convenientdecor: Convenient Decor 0.3.0
		convenientnametags: Convenient Name Tags 1.1.0
			omega-config: OmegaConfig 1.4.0+1.20.1
		coroutil: CoroUtil 1.20.1-1.3.7
		cosmetic-armor: Cosmetic Armor 1.6.0
		craft_some_elytra: Craft Some Elytra! 1.0.0
		crafttweaker: CraftTweaker 14.0.36
		cratedelight: Crate Delight 1.4.2
		crawl: Crawl 0.12.0
			mm: Manningham Mills 2.3
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		createbb: Create: Broken Bad 3.1.2
		creativecore: CreativeCore 2.11.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.4.2
		culturaldelights: Cultural Delights Fabric 0.14.12+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		cupboard: cupboard 1.20.1-2.6
		dahmersdelight: Dahmer's Delight 1.0.0
		deathlog: DeathLog 0.3.2+1.20
		debugify: Debugify 1.20.1+2.0
		delightfulcreators: Delightful Creators 1.1.8
		display_case: Display Case Mod 1.0.8
		doapi: Lets Do Api 1.2.8
		doubledoors: Double Doors 5.4
		dragonloot: DragonLoot 1.1.4
		easyanvils: Easy Anvils 8.0.2
		easyelytratakeoff: Easy Elytra Takeoff 4.2
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.2
			puzzlesapi: Puzzles Api 8.1.6
				puzzlesaccessapi: Puzzles Access Api 8.0.9
		elytra_trinket: Elytra Trinket 1.0.3
		enchantinginfuser: Enchanting Infuser 8.0.2
		enderchests: EnderChests 1.20.1-1.2
		endrem: End Remastered 5.2.4
		ends_delight: End's Delight 1.0.1
		entity-view-distance: Entity View Distance 1.1.2+1.20
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.6
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.7
		expanded_bow_enchanting: Expanded Bow Enchanting 1.0.0
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.7
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.6
		expandeddelight: Expanded Delight 0.3.0.2
		explorations: Explorations 1.20.1-1.5.2
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		extra_trinkets: Extra Trinkets 1.0
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmersknives: Farmer's Knives 3.0.2
		faster-random: Faster Random 3.0.2
		fastpaintings: Fast Paintings 1.20-1.2.4
		faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		fishingrework: Fishing Aquatica 1.20.1-0.2.8.1
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 2.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.3
		formationsoverworld: Formations Overworld 1.0.2
		framework: Framework 0.6.27
			org_javassist_javassist: javassist 3.29.2-GA
		friendsandfoes: Friends&Foes 2.0.10
		frightsdelight: Frights Delight 1.20.1-1.0.1
		frostiful: Frostiful 1.0.6
		fwaystones: Fabric Waystones 3.3.2+mc1.20.1
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic v2.2.0-mc1.20u1.20.2
		globalxp: Global XP 1.10.4
		goblintraders: Goblin Traders 1.9.3
		goldenhopper: Golden Hopper 1.4.1
		gottagofast: Gotta Go Fast! 1.1.0
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		gravestones: Gravestones v1.15
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		handcrafted: Handcrafted 3.0.6
		healingcampfire: Healing Campfire 5.3
		hearths: Hearths v1.0.0-mc1.20u1.20.1
		heroes: Heroes 1.1.61
		hybrid-aquatic: Hybrid Aquatic 1.2.2
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		icarus: Icarus 1.16
		illagerinvasion: Illager Invasion 8.0.4
		inmis: Inmis 2.7.2-1.20.1
		inventorymanagement: Inventory Management 1.3.1
		ironchest: Iron Chests 2.0.2
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		ite: Improved Trident Enchantments 1.0
		itemcollectors: Item Collectors 1.1.9
		itemphysic: ItemPhysic 1.7.0
		jade: Jade 11.8.0
		jadeaddons: Jade Addons 5.2.3
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 6.1.1+1.20.1
		kleeslabs: KleeSlabs 15.0.0
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		kubejs: KubeJS 2001.6.4-build.138
		letmedespawn: Let Me Despawn 1.2.0
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.1.5
		lmft: Load My F***ing Tags 1.0.2+1.20
		magnumtorch: Magnum Torch 8.0.2
		mcwfurnitures: Macaw's Furniture 3.2.2
		melody: Melody 1.0.3
		memoryleakfix: Memory Leak Fix 1.1.5
		midnightlib: MidnightLib 1.4.1
		mighty_mail: Mighty Mail 1.0.14
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		mobcaptains: Mob Captains 3.1.1
		moblassos: Mob Lassos 8.0.1
			extensibleenums: Extensible Enums 7.0.1
		modernfix: ModernFix 5.14.0+mc1.20.1
		moonlight: Moonlight 1.20-2.11.0
		more_sleeps: More Sleeps 1.3
		morebows: More Bows Restrung 1.0.11+1.20.x
		moredelight: More Delight 1.1.9
		movingelevators: Moving Elevators 1.4.6
		mr_better_deepslateoredrops: Better Deepslate Ore Drops 2
		mr_ctov_chefsdelightcompat: CTOV - Chef's delight Compat 2.0
		mr_ctov_farmersdelightcompat: CTOV - Farmer Delight Compat 2.1
		mr_ctov_friendsandfoescompat: CTOV - Friends and Foes Compat 2.0
		mr_ctov_villagerspluscompat: CTOV - Villagers Plus Compat 2.0
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3
		mr_edf_remastered: Ender Dragon Fight Remastered 4.3
		mr_hero_proof: Hero Proof 5.1.1
		mr_villager_transportation: Villager Transportation 1.2
		mutantmonsters: Mutant Monsters 8.0.7
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nerb: Not Enough Recipe Book 0.3
		nether_ores_reborn: Nether Ores Reborn 1.0.2-1.20.1-Fabric
		netherportalfix: NetherPortalFix 13.0.1
		nethersdelight: Nether's Delight 1.0.0
		nethervinery: Nether Vinery 1.2.6
		netherwardblock: Nether Wart Block to Nether Warts 1.20.1-6-fabric
		nets: Not Enough Trinket Slots (NETS) 0.3.5.5
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		noexpensive: NoExpensive 1.20.1-1.9.0
		noisium: Noisium 1.0.2+mc1.20.x
		nyfsquiver: Nyf's Quivers 1.20.1-fabric-1.0.4
		nyfsspiders: Nyf's Spiders 2.1.1
		obscure_api: Obscure API 16
		oceansdelight: Ocean's Delight fabric-1.0.2-1.20
		owo: oωo 0.11.2+1.20
		packetfixer: Packet Fixer 1.2.8
		palladium: Palladium 4.0.7
			palladiumcore: PalladiumCore 1.0.1
			player-animator: Player Animator 1.0.2-rc1+1.20
		pantheonsent: PantheonSent 1.0.3
			sherdsapi: Sherds API 4.0.4
		patchouli: Patchouli 1.20.1-84-FABRIC
		paxi: Paxi 1.20-Fabric-4.0
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		philipsruins: Philip`s Ruins 1.20.1
		plasmovoice: Plasmo Voice 2.0.8
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			javax_inject_javax_inject: javax.inject 1
		polymorph: Polymorph 0.49.1+1.20.1
		puzzleslib: Puzzles Lib 8.1.17
		pv-addon-lavaplayer-lib: pv-addon-lavaplayer-lib 1.0.7
		pv-addon-soundphysics: pv-addon-soundphysics 1.0.1
		ragnagoblin: Ragna Goblin 2.1.0
		railoptimization: RailOptimization 1.0
		raknetify: Raknetify (Fabric) 0.1.0+alpha.5.114
		recipe-book-delight: Recipe Book Delight 0.3.0-1.20
			dark-matter-base: Dark Matter Base 2.2.0-1.20
			dark-matter-enums: Dark Matter Enums 2.2.0-1.20
			dark-matter-minecraft: Dark Matter Minecraft 2.2.0-1.20
			dark-matter-recipe-book: Dark Matter Recipe Book 2.2.0-1.20
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.23
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respitecreators: Respite Creators 1.2.0
		restart-server: Restart Server 1.2.0+mc1.19.x-1.20.x
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		reworkednetherite: ReworkedNetherite 1.0.0
		rhino: Rhino 2001.2.2-build.18
		rotten_flesh_to_leather: Rotten Flesh to Leather 1.0.0
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 2.3+1.20
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		servercore: ServerCore 1.3.9+1.20.1
			placeholder-api: Placeholder API 2.1.2+1.20.1
		shakdel: Shakshuka Delight 1.0.0
		shetiphiancore: ShetiPhianCore 1.20.1-1.2
		simplemod: SimpleMod 1.20.1
		snowyleavesplus: SnowyLeavesPlus 0.1.9
		snowyspirit: Snowy Spirit 1.20-3.0.6
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		spawners_plus: Spawners+ 3.0-1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		staaaaaaaaaaaack: Staaaaaaaaaaaack 1.20.1-1.5-71
			fiber: fiber 0.23.0-2
		storagedelight: Storage Delight 1.0.2
		strawstatues: Straw Statues 8.0.2
		structureessentials: Structure Essentials Mod 1.20.1-3.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		supplementaries: Supplementaries 1.20-2.8.4
		suppsquared: Supplementaries Squared 1.20-1.1.14
		t_and_t: Towns and Towers 1.12
		tempad: Tempad 2.3.3
		terrablender: TerraBlender 3.0.1.4
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		thermoo: Thermoo 2.1.2
		toms_storage: Tom's Simple Storage Mod 1.6.5
		toms_trading_network: Tom's Trading Network 0.2.4
		toolleveling: ToolLeveling+ 1.20.1-2.0.0
		trade_cycling: Trade Cycling 1.20.1-1.0.10
		tradingpost: Trading Post 8.0.2
		transferable_pets: Transferable Pets 1.0.4
		transparent: Transparent 8.0.1+1.20.1
		trashcans: Trash Cans 1.0.18
			team_reborn_energy: Energy 3.0.0
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		treeharvester: Tree Harvester 8.7
		trinkets: Trinkets 3.7.2
		turkish_delight: Turkish Delight 1.0.0
		ubesdelight: Ube's Delight 0.1.5b
		universalbonemeal: Universal Bone Meal 8.0.1
		utilitybelt: Utility Belt 1.3.6+1.20.1
		veinmining: Vein Mining 1.3.1+1.20.1
		villagernames: Villager Names 7.3
		villagersplus: Villagers Plus 3.1
		villagesandpillages: Villages&Pillages 1.0.0
		vinery: Vinery 1.4.11
		visualworkbench: Visual Workbench 8.0.0
		wands: Building Wands 2.6.9-release
		watut: What Are They Up To 1.20.1-1.1.0
		weeping_angels: Weeping Angels 46.0.1
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroworldmap: Xaero's World Map 1.37.8
		xp_storage: XP Storage 1.5.5+1.20.1
		xp_storage_trinkets: XP Storage - Trinkets 1.0+1.20.1
		xxlpackets: XXLPackets 1.0.4-1.20.x-1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		yungsapi: YUNG's API 1.20-Fabric-4.0.4
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['Wowjox'/63, l='ServerLevel[world]', x=-701.45, y=65.00, z=-969.76]]
	Data Packs: vanilla, Snowyspirit Generated Pack, Supplementaries Generated Pack, Suppsquared Generated Pack, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Duzos** [comment]
@Loqor this shi again

**Comment by Loqor** [comment]
It's been fixed for a while but I haven't made a release in a minute, I'll probably end up doing that today

**Comment by Duzos** [comment]
How’d you fix it

**Comment by Loqor** [comment]
replaced DateUtil with Calendar since for some reason most JDK's just don't include the Apache package
