### ISSUE TITLE
Regeneration integration issue with incomplete TARDISes

### ISSUE THREAD

**Issue by daimond113** [amblelabs/ait#266]
**Describe the bug**
When you regenerate in an unfinished TARDIS (before throwing in a nether star) the cloister bell rings, and the exterior turns to the TARDIM one. After finishing the TARDIS, it goes in an infinite materialisation-dematerialisation loop. Opening the TARDIS in the moment possible (inbetween it dematerialising) prevents it from dematerialising, but the portal to the interior does not appear.

**To Reproduce**
1. Get regeneration energy
2. Regenerate in TARDIS
3. The cloister bell will ring and the exterior will turn to TARDIM
4. Finish the TARDIS and observe as it gets stuck in an infinite loop.

**Expected behavior**
The regeneration should be completely ignored in an unfinished TARDIS.

**AIT Version:**
1.0.4-1.20.1

**Additional context**
Regeneration mod v42.0.0
Immersive Portals v3.3.7

**Comment by TheAddieDaBaddie** [comment]
they removed regeneration mod support :)

**Comment by TheAddieDaBaddie** [comment]
here >https://github.com/Loqor/ait/compare/e0cb43437bde...db8f0ebfa57c

**Comment by daimond113** [comment]
> they removed regeneration mod support :)

Missed that, thanks!
