### ISSUE TITLE
Cannot add datapack desktop into game

### ISSUE THREAD

**Issue by RoeiWN** [amblelabs/ait#267]
**Describe the bug**
I followed the instructions on the wiki, the game recognizes the datapack, but the desktop doesn't appear on the tardis monitor. it might be a mistake I made, but I went through the process a couple of times and couldn't figure out anything I did wrong

**AIT Version:**
1.0.4

**Comment by Duzos** [comment]
run `/reload` 
force unlocks all desktops to all tardises

**Comment by RoeiWN** [comment]
tried that

**Comment by Duzos** [comment]
Can you check minecraft logs to see if it’s getting registered to ait?
It should say something like “Registered ID desktop”
If not just send the datapack .zip if that’s possible

**Comment by RoeiWN** [comment]
[Render thread/ERROR]: Error occurred while loading resource json roei:desktop/fugitive.json

[fugitive.zip](https://github.com/Loqor/ait/files/14736418/fugitive.zip)

**Comment by Duzos** [comment]
I see
I’ll take a look at the .zip later
Someone should rly make a tutorial sometime lol

**Comment by Loqor** [comment]
looks to be user error. please consult the wiki or help channels in our discord.
