### ISSUE TITLE
Tardis coral bug

### ISSUE THREAD

**Issue by SappleThyApple** [amblelabs/ait#268]
**Describe the bug**
Whenever I place TARDIS coral anywhere in the map, even in rift chunks, it instantly breaks and produces barrier particle effects.

**Screenshots**
![ATIbug](https://github.com/Loqor/ait/assets/164606885/c333e47e-0ac4-4678-b79e-be3fa1115d74)

**AIT Version:**
1.0.4

**Additional context**
I ran this with both several mods and also the only required mods, yet nothing changed

**Comment by SpartanGamezFTB** [comment]
This isn't a bug, there's just no tardis coral particle textures yet

**Comment by SappleThyApple** [comment]
okay but what about it instantly breaking everywhere

**Comment by Duzos** [comment]
Read wiki
Place on soul sand in rift chunk
