### ISSUE TITLE
Sonic Variants & Datapack Compatibility Feature

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#272]
I think it could be cool to have sonic variants like different colors like a Cherry variant for Mechanical or NetherBrick Coral and etc, just a little more customization for the mod. The GUI that is used for the Sonics Type Selection is the same for when a player selects their exterior, so the buttons are already made, just need to be coded to exist...if that makes any sense. 

Datapack Tutorial [Method/Example/Idea]..Thingy
So I have come up with 2 different methods for a player to add their own sonics to a datapack

Examples for website:
- Default = `default`
- Mechanical = `mechanical`
- Coral = `coral`
- Renaissance = `renaissance`

### Method 1:
```
{
  "id": "(namespace):(sonic_texture_name)",
  "parent": "ait:sonic/(refer to example below)",
  "texture": "(namespace):textures/(sonic_texture_name).png",
  "inactive": "(namespace):textures/(sonic_texture_name)_inactive.png",
  "interaction": "(namespace):textures/(sonic_texture_name)_interaction.png",
  "overload": "(namespace):textures/(sonic_texture_name)_overload.png",
  "scanning": "(namespace):textures/(sonic_texture_name)_scanning.png",
  "tardis": "(namespace):textures/(sonic_texture_name)_tardis.png"
}
```

Now if the coder implementing _**(Loqor or Duzo)**_ this doesn't want the player to be able to change how the lights look for the modes then here's the other method

### Method 2:
```
{
  "id": "(namespace):(sonic_texture_name)",
  "parent": "ait:sonic/(refer to example below)",
  "texture": "(namespace):textures/(sonic_texture_name).png"
}
```

I don't code, so I'm not sure if it can somehow overwrite the rest of the textures with just the default texture...so prob method 1 but hey like i said...no clue how code works xD

**Comment by TheRealBb8fan1** [comment]
Let him cook!

**Comment by PierogiPL** [comment]
Didn't someone say that this was planned already?

**Comment by Duzos** [comment]
Since the sonic models are in .json format i presume you can use those 
Unless its coded funny ( ait moment ) then idk

**Comment by Duzos** [comment]
#284

**Comment by DrTheodor** [comment]
Should be implemented by the latest commit. Needs testing.
Should work as follows:
`/data/<namespace>/sonic/<id>.json`
```json
{
    "name": "Test Sonic",
    "model": 123
}
```

Then you just need to write the overrides for the `item/sonic_screwdriver.json` model (you can check the original model cause it also uses overrides).

**Comment by PierogiPL** [comment]
Would be cool if we also had a thing for changing sounds based on sonic variants

**Comment by DrTheodor** [comment]
Here's an (currently used in the mod itself) example on how to add sonics:
`/data/<namespace>/sonic/<id>.json`
```json
{
  "id": "<namespace>:<id>",
  "name": "<name>",
  "model": <model number>
}
```

Then you just make a model override like in `/assets/ait/models/item/sonic_screwdriver.json` with the `sonic_type` matching the `model` entry of the datapack json file we made earlier.

:::note
This feature will receive updates and is not complete until the release. The format might change.
:::

**Comment by Loqor** [comment]
implemented
