### ISSUE TITLE
[1.20.1] Tardis Disappears and can't be Summoned

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#274]
**Describe the bug**
After reloading my world, my Tardis is invisible and unenterable. The thin black outline can be seen when I put it in my reticle, but clicking on it does nothing. My sonic screwdriver says "None" where it usually gives the Tardis' co-ordinates.

**To Reproduce**
Grow a Tardis, play with it for a while (in addition to crafting and building other things), exit the game and return to your world. I don't know exactly what action triggers it, but it's happened twice now during survival play. The first time it happened, I just spawned in a new Tardis Coral and grew a new one, but this time I left some important shulker boxes inside, so I'd really like to get back into this one. And prevent it from happening again, of course.

**Expected behavior**
Tardis has persistance

**Screenshots**
Tardis disappears

**AIT Version:**
1.0.4

**Additional context**
My mod list:
![image](https://github.com/Loqor/ait/assets/5751770/617bd69a-39e6-48e5-aa94-90608c9d2d93)

**Comment by Flexico** [comment]
UPDATE: I managed to get into my old Tardis' interior by making a new one and teleporting to co-ordinates from a screenshot. The console is also invisible; the blue hitboxes of the controls are visible while holding my sonic, but nothing happens when I click them.
![2024-03-29_14 04 21](https://github.com/Loqor/ait/assets/5751770/8acf5d14-0d30-4e8a-8fab-1501139e55af)
![2024-03-29_18 19 08](https://github.com/Loqor/ait/assets/5751770/fd1f92ce-bac0-48d6-94c2-51c08c0854a8)

My log file is freaking 419 MB Holy crap

**Comment by Duzos** [comment]
Check the world folder and show `.ait`
I'd also recommend running minecraft with output logs to see if theres any error message

**Comment by Flexico** [comment]
".ait" contents:
{
  "travel": {
    "state": "LANDED",
    "position": {
      "direction": "NORTH",
      "dimension": "minecraft:overworld",
      "field_11175": 216,
      "field_11174": 67,
      "field_11173": 159
    },
    "destination": {
      "direction": "NORTH",
      "dimension": "minecraft:overworld",
      "field_11175": 216,
      "field_11174": 67,
      "field_11173": 159
    },
    "lastPosition": {
      "direction": "NORTH",
      "dimension": "minecraft:overworld",
      "field_11175": 216,
      "field_11174": 67,
      "field_11173": 159
    },
    "crashing": false,
    "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
    "id": "travel"
  },
  "uuid": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
  "desktop": {
    "schema": "ait:alnico",
    "doorPos": {
      "direction": "SOUTH",
      "dimension": "ait:tardis_dimension",
      "field_11175": 47911,
      "field_11174": 13,
      "field_11173": 25726
    },
    "consoles": [
      {
        "uuid": "35a91dba-562e-4e73-ac79-21b5c1c2194c",
        "position": {
          "dimension": "ait:tardis_dimension",
          "field_11175": 47911,
          "field_11174": 13,
          "field_11173": 25745
        },
        "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
        "id": "console"
      }
    ],
    "corners": {
      "first": {
        "field_11175": 47761,
        "field_11174": 0,
        "field_11173": 25595
      },
      "second": {
        "field_11175": 48017,
        "field_11174": 0,
        "field_11173": 25851
      }
    },
    "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
    "id": "desktop"
  },
  "exterior": {
    "exterior": "ait:exterior/capsule",
    "variant": "ait:exterior/capsule/fire",
    "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
    "id": "exterior"
  },
  "handlers": {
    "door": {
      "locked": false,
      "left": false,
      "right": false,
      "doorState": "CLOSED",
      "tempExteriorState": "SECOND",
      "tempInteriorState": "SECOND",
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "door"
    },
    "properties": {
      "data": {
        "date": "2024-03-29 18:18:19",
        "fuel_count": 42088.25,
        "find_ground": true,
        "dev_unlocked": true,
        "regal_unlocked": true,
        "alnico_unlocked": true,
        "siege_held": false,
        "default_cave_unlocked": true,
        "leave_behind": false,
        "flight_ticks": 0.0,
        "tardis_recovery_ticks": 0.0,
        "hostile_presence_toggle": true,
        "queued_interior": {
          "field_13353": "ait",
          "field_13355": "alnico"
        },
        "is_regenerating": false,
        "coral_unlocked": true,
        "botanist_unlocked": true,
        "hail_mary": false,
        "newbury_unlocked": true,
        "pristine_unlocked": true,
        "war_unlocked": true,
        "copper_unlocked": true,
        "tardis_recovery_state": "NORMAL",
        "has_console_sonic": false,
        "is_in_active_danger": false,
        "is_falling": false,
        "hads_enabled": false,
        "max_speed": 7.0,
        "refueling": true,
        "mat_ticks": 0.0,
        "demat_ticks": 0.0,
        "tokamak_unlocked": true,
        "name": "Seneca",
        "hum_enabled": true,
        "type_40_unlocked": true,
        "timeless_unlocked": true,
        "last_locked": false,
        "office_unlocked": true,
        "increment": 1.0,
        "speed": 0.0,
        "antigravs_enabled": false,
        "toyota_unlocked": true,
        "handbrake": true,
        "vintage_unlocked": true,
        "power": true,
        "victorian_unlocked": true,
        "siege_ticks": 0.0,
        "console_disabled": false,
        "crystalline_unlocked": true,
        "is_in_real_flight": false,
        "cave_unlocked": true,
        "alarm_enabled": false,
        "cloaked": false,
        "target_ticks": 100.0,
        "auto_land": false,
        "siege_mode": false
      },
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "properties"
    },
    "waypoints": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "waypoint"
    },
    "loyalties": {
      "data": {},
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "loyalty"
    },
    "overgrown": {
      "ticks": 600,
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "overgrown"
    },
    "hum": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "hum"
    },
    "alarms": {
      "soundCounter": 10,
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "alarm"
    },
    "interior": {
      "ticks": 0,
      "clearedOldInterior": false,
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "interior-changing"
    },
    "sequenceHandler": {
      "ticks": 0,
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "sequence"
    },
    "fuel": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "fuel"
    },
    "hads": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "hads"
    },
    "flight": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "flight"
    },
    "siege": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "siege"
    },
    "cloak": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "cloak"
    },
    "stats": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "stats"
    },
    "crashData": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "crash"
    },
    "sonic": {
      "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
      "id": "sonic"
    },
    "tardisId": "38ac5245-18ec-469a-aaa8-b0a91582ef47",
    "id": "handlers"
  },
  "dirty": false,
  "tardisHammerAnnoyance": 0
}

**Comment by Duzos** [comment]
yeah like how many files are in the folder

**Comment by Flexico** [comment]
Three; I determined this is the one corresponding to the current messed-up Tardis.
![image](https://github.com/Loqor/ait/assets/5751770/86c37d48-44f7-4bf6-a78e-5fc37bebe776)

**Comment by Duzos** [comment]
Well shucks 
What was the UUID of the broken tardis
If a .old file exists for it restore it

**Comment by Flexico** [comment]
Restoring the backup changed nothing.

**Comment by kalethemonster** [comment]
im also experiencing this bug. i think part of what causes this bug is being in a world with multiple tardises then going into a world with only from what i can parse from my log here (taken from the latest log file)  https://pastebin.com/JqVyVb2p
![2024-04-13_15 48 42](https://github.com/Loqor/ait/assets/103093131/ddf7cdf5-ccbe-4abf-8980-0edb04bbac78)
![2024-04-13_15 48 32](https://github.com/Loqor/ait/assets/103093131/0e0edc77-2020-49ca-8de1-a7e115e2119e)
![2024-04-13_15 24 36](https://github.com/Loqor/ait/assets/103093131/64f7c0dc-7e31-4a7b-9b3b-a2e97fe8761b)

**Comment by Flexico** [comment]
I got them working again by exiting and re-loading the world a few times, but I haven't managed to reliably replicate the problem/solution

**Comment by PierogiPL** [comment]
I experience this one quite often

**Comment by kalethemonster** [comment]
> I got them working again by exiting and re-loading the world a few times, but I haven't managed to reliably replicate the problem/solution

how many times did you have to exit and re-load?

**Comment by Flexico** [comment]
> > I got them working again by exiting and re-loading the world a few times, but I haven't managed to reliably replicate the problem/solution
> 
> how many times did you have to exit and re-load?

Three, maybe four

**Comment by Loqor** [comment]
Yep, fixed in the newest updates.

**Comment by kalethemonster** [comment]
(sorry if this comment reopens the issue, ill see if i can close it if it does, im just dropping an observation ive made) 
when it comes to the memory leak... from what ive noticed by messing around in a few creative worlds, the ones where tardises have disappeared on me are ones ive used a tardis to travel across dimensions 

this is probably a minor part of the issue in 1.0.4 and this is fixed for the next version, but i thought id mention it before the next update drops in case this is apart of problems in the future.
