### ISSUE TITLE
Add New Interiors Using a Datapack?

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#275]
Is there currently a way to add custom interiors/exteriors to the mod? I know I can just use WorldEdit to paste a schematic into the "Dev" Tardis version, but I'd like to be able to regenerate the interior into a custom build, and share it with friends, etc.

**Comment by Loqor** [comment]
ehm... https://loqor.dev/ait

please look in the FAQ channel in the Discord before making an issue.

**Comment by Flexico** [comment]
Oh dang, sorry! I'm messing with so many mods I've lost track of what I have and haven't done. ^^;
