### ISSUE TITLE
Activating Seige Mode by Command won't work properly

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#278]
**Describe the bug**
when running seige mode by command it won't make you cold, turn power off and the window appears still

**To Reproduce**
activate seige mode by command

**Expected behavior**
should make you cold and i think the windows of the door isn't supposed to be there and the power should be off

**Video**

https://github.com/Loqor/ait/assets/152225935/3d6a4a62-7527-4a1e-bbca-2bfcd535f906

**AIT Version:**
1.0.4 releace

**Additional context**
nope this happens without shaders too

**Comment by Duzos** [comment]
prolly cus the command is bad 
its for testing / fixing temp bugs and instead of using the `disableSiegeMode` method or whatever it just force sets the `siegemode` property of the tardis to false
the `disableSiegeMode` method or whatever its called runs all the logic
