### ISSUE TITLE
I broke multiplaeyr :(

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#28]
two things spotted

- doors are SOO laggy bc i think it sends too many packets which we need to change, probably by where markDirty() is / move it out of the set methods to stop spam (DoorBlockEntity / DoorHandler)

- syncing issues with the exterior as nothing on it gets updated, i think this means there is no markdirty / no syncing as it clearly updates when specifically synced (ExteriorBlockEntity / ServerTardisExterior)

shouldnt be tooo bad to fix it as most of its just stuff to do with syncing but its soo annoyiinggg 
i would fix it rn but sleepy and i dont rly trust loqor to do it he overthinks things

**Comment by Duzos** [comment]
Ah and hums and alarms
They also only toggle / change sound when the tardis gets synced eg when the monitor is used

**Comment by Loqor** [comment]
Everything here is fixed because again, the sync rewrite and mark dirty things we did with the handlers where the tardis is set dirty instead of each individual handler.

**Comment by Duzos** [comment]
Who did you test with and how?
I'll test it when i get home but just checking
