### ISSUE TITLE
Immersive Portal wont despawn

### ISSUE THREAD

**Issue by TheGreElucid** [amblelabs/ait#281]
**Describe the bug**
When completing Tardis Growth for the first time, the Portal from the cave interior stays in place regardless of door or flight status

**To Reproduce**
1. Grow a Tardis
2. Activate with Nether Star
3. Wait for rematerialization
4. Walk in and See error

**Expected behavior**
When Tardis is grown the old portal should be removed from the interior

**Screenshots**
![2024-04-07_13 41 12](https://github.com/Loqor/ait/assets/44938113/03311327-5118-4b49-8aee-a06b6314e707)

**AIT Version:**
AIT 1.0.4
Immersive Portals 3.3.7

**Comment by Flexico** [comment]
Same happens with me! I've worked around the problem using the "Eradicate Portal Cluster" tool from IP and re-opening the doors, but more than once I've stepped out of my Tardis and ended up at its previous location, with no visual indication that the portal led there.

**Comment by theOneTrueFunniBoi** [comment]
> Same happens with me! I've worked around the problem using the "Eradicate Portal Cluster" tool from IP and re-opening the doors, but more than once I've stepped out of my Tardis and ended up at its previous location, with no visual indication that the portal led there.

Exact same for me! I've figured out the portal still has a visual indicator, it's just that the two are either inside each other or slightly behind, i've fixed this problem by running /portal delete-portal as much as i need, then closing and reopening the doors to refresh the portal.

**Comment by Duzos** [comment]
ancient
