### ISSUE TITLE
Providing Further Detail on Navigating Flight

### ISSUE THREAD

**Issue by Dojeman123** [amblelabs/ait#282]
**Is your feature request related to a problem? Please describe.*

It is quite frustrating for me when an event occurs and there is no in game explanation/solution to the problem. For instance, after my journey has finished, I try to land the tardis by pushing the throttle all the way back, and instead of landing, it seems to be struggling, with a change in audio.

**Describe the solution you'd like**

Please could you either provide an in-game manual or solutions to this on the official wiki.

**Describe alternatives you've considered**

I have attempted to look at other YouTubers’ interpretations of this mod but they don’t seem to have the same issue as mine.

**Comment by Duzos** [comment]
Stick a sonic in scanning mode in the sonic port

**Comment by SpartanGamezFTB** [comment]
i mean theres a reason the tardis would make an error landing sound and usually its due to either the coords being impossible like a block in the way so just adjust ur coords
