### ISSUE TITLE
[IDEA] Datapack Sonic Screwdrivers!

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#284]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look at the normal screwdrivers and think can I put it in my mout- I mean uh I uh think that why can't we change it as if we want to make new screwdrivers in the mod then we gotta test it too and it would be easier (maybe) for adding future screwdrivers.

**Describe the solution you'd like**
we are able to make a custom screwdriver in texturepacks and then add it to the sonic settings customisation and make it work as a screwdriver in datapacks.

**Additional Stuff**
https://discord.com/channels/1213989169878274068/1226827139643609099

**Comment by DrTheodor** [comment]
Gonna post some related code links here to implement it later (maybe today)

https://github.com/Loqor/ait/blob/main/src%2Fmain%2Fjava%2Floqor%2Fait%2Fclient%2FAITModClient.java#L284
https://github.com/Loqor/ait/blob/main/src%2Fmain%2Fjava%2Floqor%2Fait%2Fcore%2Fitem%2FSonicItem.java#L209
https://github.com/Loqor/ait/blob/main/src%2Fmain%2Fjava%2Floqor%2Fait%2Fclient%2Fscreens%2FSonicSettingsScreen.java#L203
https://github.com/Loqor/ait/blob/main/src%2Fmain%2Fjava%2Floqor%2Fait%2Fcore%2Fitem%2FSonicItem.java#L462

**Comment by Duzos** [comment]
This issue has already been made
#272 
Please check before creating new issues

**Comment by Duzos** [comment]
<3

**Comment by DrTheodor** [comment]
Should be implemented by the latest commit, needs testing though (need to fix my dev env).

**Comment by DrTheodor** [comment]
Implemented and tested!
