### ISSUE TITLE
[IDEA] finished Reconfiguration notif (with the key)

### ISSUE THREAD

**Issue by kalethemonster** [amblelabs/ait#285]
a thing i think would be cool is a key linked to a tardis being able to tell the player that has it that the linked tardis has finished rebuilding the interior. this is directly based on when the key for the tardis is warm in the doctor's pocket when the tardis finishes rebuilding in s5 ep1 the eleventh hour.

whether it shows up as a message above the hotbar, or as the key's texture changing, or the key giving off particles in a player's hand, it would be real cool and useful. like if you have it rebuild while you're running around your base, if it rebuilds after regenerating (with the regen mod), or even if you're stood in front of it eagerly waiting.

this also makes sense with the fact that the tardis is alive, in the episode she was using the key to say "hey thief, come look at my new desktop!"

**Comment by SpartanGamezFTB** [comment]
like the key glowing sorta? shown in Season 5 Episode 1 after the Doctor handles the Atraxi.

**Comment by kalethemonster** [comment]
> like the key glowing sorta? shown in Season 5 Episode 1 after the Doctor handles the Atraxi.

yeah, like that. exactly like that. i just think it's neat.

**Comment by TheRealBb8fan1** [comment]
Need it already!
