### ISSUE TITLE
AIT has no sound on Prominence II RPG dedicated server

### ISSUE THREAD

**Issue by MidnightWolfang** [amblelabs/ait#287]
**Describe the bug**
I'm playing the Prominence II RPG modpack with a friend, but it doesn't work in a dedicated server with fabric 0.15.+, so I searched how to make the a mod compatible with other versions, downloaded the code, changed the versions supported and dependencies on the "gradle.properties", "fabric.mod.json", and  and built the jar. It works now with in the server, but it doesn't have some sounds like the Sonic Screwdriver, some buttons and lever, the TARDIS hums and flight/landing sounds. It does the sound when the travel is completed tho, which is good. Also, the disc that comes with the mod just disappears when put in a jukebox and some texts gets weird, like the TARDIS Menus with 

**To Reproduce**
1. Create a Prominence II [RPG] Instance
2. Download .jar on the google drive (or just change the gradle.properties to work with loader version 0.14.25, fabric 0.91.0+1.20.1, owo 0.11.1+1.20). : https://drive.google.com/file/d/1gD3PXJfAOxCaoLnmE8owyTi3SbElRx6U/view?usp=drive_link
3. Open minecraft and create a world.
4. Put the TARDIS in the world and go inside it. It'll have no sounds.
5. Get a Sonic Screwdriver, it'll have no sounds.
6. Put a jukebox in world and use the music disc, it'll have no sounds.
7. Open the Monitor menu and go to settings. That and other stuff like the coordinates screen messages will have texts like "screen.ait.interiorsettings.back".

**Expected behavior**
I expected it would work properly. With sounds and the menu options with the right name.

**Screenshots**
![image](https://github.com/Loqor/ait/assets/56291210/6b381d94-c757-4815-8fb2-3b98ac11569e)

**AIT Version:**
1.0.4-1.20.1-release

**Additional context**
As said before, I'm using the Modpack Prominence II [RPG] in a dedicated server, which makes it only works with loader version on 0.14.25 of fabric (0.91.0).

**Comment by Duzos** [comment]
Run data gen.
