### ISSUE TITLE
Redo markDirty

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#29]
Idk how well i can explain this but i know how to do it
instead of having all the things that need syncing marking themselves as dirty and then syncing the tardis, they should mark the tardis as dirty and the tardis will sync itself which syncs everything. This means less syncs and less packets so more efficient.
Also don't markdirty set tick in overgrown handler

**Comment by Loqor** [comment]
Fixed! everything works super well and it all syncs perfectly + no lag for multiple connected players and multiple tardises in flight, plus hums and alarms sync amazingly well and dont have any bugging issues!
