### ISSUE TITLE
Sonic Item returns to the black and purple texture after resource reload.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#290]
Sonic Item returns to the black and purple texture after resource reload.
![image](https://github.com/Loqor/ait/assets/65447472/752fd9d8-2bda-4e87-9795-737fab3db79a)

**Comment by DrTheodor** [comment]
womp womp
populateModels fucked up

**Comment by Loqor** [comment]
sounds about right

**Comment by DrTheodor** [comment]
couldn't replicate on the last commit
