### ISSUE TITLE
Memory and CPU usage issues

### ISSUE THREAD

**Issue by Ouroboros-Games** [amblelabs/ait#293]
**Describe the bug**
When being used on servers with limited memory and storage (8GB and 40GB respectively) TARDISes chunkloading can cause boot-loops, crashes, world corruption, and various other issues and the world corruption sticks around through even the most thorough of server wipes and resets, and TARDISes loading chunks also causes storage issues such as a world booming from mere Megabytes of size to Gigabytes within 10 minutes or so

**To Reproduce**
1. Add AIT to a server with limited RAM and storage
2. boot the server
3. create 10-20 TARDISes
4. get several people on to mess around with the TARDISes and fly them around
5. repeat for a few weeks until you get desired results

**Expected behavior**
Can't really provide this since it was all sudden and unexpected

**Screenshots**
N/A

**AIT Version:**
1.0.4

**Additional context**
Performance mods and various other stable mods were used, but none have causes issues before for me

**Comment by Duzos** [comment]
force chunk loading memory leak

**Comment by Duzos** [comment]
they dont get unloaded

**Comment by DrTheodor** [comment]
wow.

**Comment by DrTheodor** [comment]
Some updates. In the original discussion on discord Miner also said that the TARDIS data was taking a lot of space.
With the latest commit you can set the option `MINIFY_JSON` in the config to `true`. This will remove the unneeded line breaks and spaces, effectively making the jsons less readable but take less space.

**Comment by PasteleiroB96** [comment]
Oh, and I have a problem, if I look at the console, my FPS decreases
I already told Theoqore, but I wanted to take precautions and repeat in this post that it's about performance.

**Comment by miner100910** [comment]
> Oh, and I have a problem, if I look at the console, my FPS decreases I already told Theoqore, but I wanted to take precautions and repeat in this post that it's about performance.

that's just gonna be a rendering/GPU strength issue, not _server_ memory and CPU issues like this is about

**Comment by foxy-commentating-bread** [comment]
> Oh, and I have a problem, if I look at the console, my FPS decreases I already told Theoqore, but I wanted to take precautions and repeat in this post that it's about performance.

Holy shit he wrote normally this is a moment in history

**Comment by miner100910** [comment]
> > > Oh, and I have a problem, if I look at the console, my FPS decreases I already told Theoqore, but I wanted to take precautions and repeat in this post that it's about performance.
> > 
> > 
> > that's just gonna be a rendering/GPU strength issue, not _server_ memory and CPU issues like this is about
> 
> Put it only happpen with the Console, and still are a problem

Still unrelated to the CPU and Memory issues this issue is about, best bet is to make your own issue about the console control entities lagging and say about it in there so it's more likely to be noticed

**Comment by Loqor** [comment]
This is fixed in the next update, or at least, should be.
