### ISSUE TITLE
PT-BR Translation Issues

### ISSUE THREAD

**Issue by PasteleiroB96** [amblelabs/ait#294]
**Describe the bug**
Some words in PT-BR are NOT translated,  or have not been translated correctly
If you guys allow me,  i can send the pt_br.json with the correct translation
But there's some phrases do not appear, only the English version

**To Reproduce**
Just looking at the items,  blocks,  etc

**AIT Version:**
1.0.4

**Additional context**
Ask to translate what was not translated, and make the rest of the translation appear instead of showing the English version((i can make a new version if you want it))

**Comment by Duzos** [comment]
sure open a PR

**Comment by MaketendoDev** [comment]
if you can't do that send me the json and ill add it

**Comment by PasteleiroB96** [comment]
> sure open a PR

What is a "PR"???

**Comment by MaketendoDev** [comment]
"Pull Request"

**Comment by PasteleiroB96** [comment]
> "Pull Request"

Are you talking about the file with everything in it corrected?

**Comment by MaketendoDev** [comment]
nah a pull request is asking the owner to add a code you changed

**Comment by PasteleiroB96** [comment]
> nah a pull request is asking the owner to add a code you changed



> sure open a PR

How i do this???

**Comment by Duzos** [comment]
its ok just send the corrected .json here or in the discord and we'll sort it

**Comment by MaketendoDev** [comment]
mhm

**Comment by MaketendoDev** [comment]
🤓

**Comment by PasteleiroB96** [comment]
> its ok just send the corrected .json here or in the discord and we'll sort it

Im working on it,  but remember there's still some word or phrases that dosent appear

**Comment by MaketendoDev** [comment]
k

**Comment by PasteleiroB96** [comment]
Btw,  why there's "existing" files,  and "normal" files???

**Comment by PasteleiroB96** [comment]
![image](https://github.com/Loqor/ait/assets/127914230/12a5e185-1109-420d-8d21-6ebad83259c2)

**Comment by DrTheodor** [comment]
this is only in the built mod.
the lang files are generated by the code and joined together with the "existing" translations.

**Comment by PasteleiroB96** [comment]
> this is only in the built mod.
> the lang files are generated by the code and joined together with the "existing" translations.

Maybe that's why there are translations that don't appear

**Comment by DrTheodor** [comment]
because it was not all translated? yeah

**Comment by PasteleiroB96** [comment]
[pt_br v1.json](https://github.com/Loqor/ait/files/15119466/pt_br.v1.json)


Here is the new file, I used it based on what was already translated, just in case, I'm going to make a REALLY new one

((i put v1 because i will make a new one just in case))

**Comment by MaketendoDev** [comment]
k

**Comment by MaketendoDev** [comment]
ill do a pr

**Comment by MaketendoDev** [comment]
done

**Comment by PasteleiroB96** [comment]
Hey Devs,  that "Custom Menu" is what exactly???
The Translation May change depending what it is

**Comment by PasteleiroB96** [comment]
> Hey Devs, that "Custom Menu" is what exactly??? The Translation May change depending what it is

[pt_br v2.json](https://github.com/Loqor/ait/files/15121985/pt_br.v2.json)
Forget it it was about that option in main menu and... stuff...
Anyways,  here's the Version 2,  in MY opinion it looks WAY better

**Comment by MaketendoDev** [comment]
done

**Comment by MaketendoDev** [comment]
just gotta wait till someone will approve

**Comment by PasteleiroB96** [comment]
Who exactly???
Btw,  the previous one was approved???

**Comment by DrTheodor** [comment]
Merged

**Comment by PasteleiroB96** [comment]
Before i close this comment and etc,  you guys allow me translate the next updates???
Then it will realese with everything ready and complete

**Comment by MaketendoDev** [comment]
uhm depends on what loqor thinks?

**Comment by PasteleiroB96** [comment]
I will let this Comment open

**Comment by MaketendoDev** [comment]
sure k

**Comment by PasteleiroB96** [comment]
Soooooo,  can i close this thing???
Like,  he allow me or not???

**Comment by MaketendoDev** [comment]
soon we will have a crowdin page not now=

**Comment by MaketendoDev** [comment]
but idk
he hasn't said anything

**Comment by PasteleiroB96** [comment]
> soon we will have a crowdin page not now=

Hmm,  Okey
I will close then,  allright???
Thanks for your time

**Comment by MaketendoDev** [comment]
okay, thank you!
