### ISSUE TITLE
[IDEA] Unlock Command

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#296]
**Describe the solution you'd like**
the unlock command can be used to unlock the loyalty unlocked exteriors and interiors of teh TARDIS

/ait 
↓
unlock or unlock all
↓
interiors or exteriors
↓
TARDIS UUID
↓
TARDIS Interior you want to unlock

**Comment by DrTheodor** [comment]
Already implemented.
See:
https://github.com/Loqor/ait/blob/main/src/main/java/loqor/ait/core/commands/UnlockConsolesCommand.java
https://github.com/Loqor/ait/blob/main/src/main/java/loqor/ait/core/commands/UnlockExteriorsCommand.java
https://github.com/Loqor/ait/blob/main/src/main/java/loqor/ait/core/commands/UnlockInteriorsCommand.java
