### ISSUE TITLE
Control Entities are discarded

### ISSUE THREAD

**Issue by Eyerisss** [amblelabs/ait#300]
**Describe the bug**
Tardis controls are removed when interacting, likely caused by another mod but unsure at this point

Game console prints the following message

[18:39:57] [Server thread/WARN]: Discarding invalid control entity at (99769.2109375, 5.037501335144043, 22433.337890625)

**Screenshots**
![2024-04-29_18 41 37](https://github.com/Loqor/ait/assets/126408706/2214d7ad-d910-4ca3-b813-3908b3604869)

**AIT Version:**
1.0.
4

**Additional context**
Playing with variety of clientside optimisations

**Comment by nitrogenez** [comment]
May you provide the list of mods that are installed, please? This would really be a nice thing to have for additional context, as some optimisations may impact the way Minecraft works with entities.

**Comment by Eyerisss** [comment]
I am building a modpack, making it very difficult to isolate what could be causing it

`  [✔] [1.20.1-fabric]-Epic-Knights-8.2
  [✔] ad_astra-fabric-1.20.1-1.15.18
  [✔] AdditionalAdditions-6.0.1
  [✔] ait-1.0.4-1.20.1-release
  [✔] alloy-forgery-2.1.2+1.20
  [✔] alternate-current-mc1.20-1.7.0
  [✔] AmbientSounds_FABRIC_v5.3.9_mc1.20.1
  [✔] amecs-1.3.10+mc.1.20.1
  [✔] antique-atlas-2.7.0+1.20
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] Aquamirae-6
  [✔] architectury-9.2.14-fabric
  [✔] astrocraft-1.2.1+1.20.4
  [✔] athena-fabric-1.20.1-3.1.2
  [✔] AttributeFix-Fabric-1.20.1-21.0.4
  [✔] autotag-2.0.2+1.20
  [✔] azurelib-fabric-1.20.1-2.0.21
  [✔] BadOptimizations-2.1.1
  [✔] balm-fabric-1.20.1-7.2.2
  [✔] beautify-1.1.0+fabric-1.20
  [✔] bellsandwhistles-0.4.5+1.20.1-FABRIC
  [✔] betterarcheology-1.1.8-1.20.1
  [✔] betterchunkloading-fabric-1.20.1-4.0
  [✔] bettercombat-fabric-1.8.5+1.20.1
  [✔] BetterF3-7.0.2-Fabric-1.20.1
  [✔] bettermounthud-1.2.2
  [✔] BetterThirdPerson-Fabric-1.20-1.9.0
  [✔] Blahaj-1.0.0
  [✔] Bookshelf-Fabric-1.20.1-20.1.10
  [✔] botarium-fabric-1.20.1-2.3.3
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.11.5
  [✔] camps_castles_carriages-2.3
  [✔] cardinal-components-api-5.2.2
  [✔] cave_dweller-1.20.1
  [✔] cc-tweaked-1.20.1-fabric-1.110.3
  [✔] chalk-2.2.4
  [✔] charmofundying-fabric-6.5.0+1.20.1
  [✔] Chipped-fabric-1.20.1-3.0.6
  [✔] chunksending-fabric-1.20.1-2.8
  [✔] cicada-lib-0.6.2+1.20.1-and-below
  [✔] cinderscapes-4.0.10
  [✔] cloth-config-11.1.118-fabric
  [✔] cmdkeybind-1.6.3-1.20
  [✔] common-networking-fabric-1.0.3-1.20.1
  [✔] connectiblechains-2.2.1+1.20.1
  [✔] Continents_1.20.4_v1.1.4
  [✔] Copycats-fabric.1.20.1-1.2.6
  [✔] coroutil-fabric-1.20.1-1.3.7
  [✔] Couplings-1.9.4+1.20
  [✔] create_dd-0.1c
  [✔] createaddition-fabric+1.20.1-1.2.3
  [✔] createbigcannons-fabric-1.20.1-0.5.4
  [✔] createdeco-2.0.2-1.20.1-fabric
  [✔] creatediselgenerators-1.2.3h
  [✔] create-fabric-0.5.1-f-build.1417+mc1.20.1
  [✔] create-metalwork-1.0.1-fabric
  [✔] create-new-age-fabric-1.20.1-1.1.2
  [✔] CreativeCore_FABRIC_v2.11.24_mc1.20.1
  [✔] cupboard-fabric-1.20.1-2.6
  [✔] Debugify-1.20.1+2.0
  [✔] decorative_blocks-fabric-1.20.1-4.1.3
  [✔] design_decor-0.2a+1.20.1-12
  [✔] DistantFriends-fabric-1.20.1-0.5.4
  [✔] do_a_barrel_roll-fabric-3.5.5+1.20.1
  [✔] DramaticDoors-QuiFabrge-1.20.1-3.2.1
  [✔] duckyperiphs-1.20.1-1.3.1-fabric
  [✔] dynamiccrosshair-7.4.4+1.20-fabric
  [✔] dynamiccrosshair-compat-3.7.2+1.20.1
  [✔] dynamic-fps-3.4.3+minecraft-1.20.0-quilt
  [✔] DynamicSurroundings-Fabric-1.20.1-0.3.3
  [✔] elytra_trinket-1.0.3
  [✔] elytraslot-quilt-6.3.0+1.20.1
  [✔] emi_loot-0.6.6+1.20.1
  [✔] emi-1.1.4+1.20.1+fabric
  [✔] EnchantingInfuser-v8.0.2-1.20.1-Fabric
  [✔] EnchantmentDescriptions-Fabric-1.20.1-17.0.14
  [✔] enhancedblockentities-0.9+1.20
  [✔] EpicSamurai-Fabric-0.0.5-beta
  [✔] Estrogen-4.2.7+1.20.1-fabric
  [✔] expandeddelight-0.3.1
  [✔] exposure-1.20.1-1.5.1-fabric
  [✔] extraalchemy-fabric-1.20.1-1.10.0
  [✔] extra-mod-integrations-0.4.4+1.20.1
  [✔] fabric-api-0.92.1+1.20.1
  [✔] fabric-end-remastered-5.2.4
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] FarmersDelight-1.20.1-2.1.1+refabricated
  [✔] farmersknives-3.2
  [✔] Female-Gender-Mod-fabric-1.20-3.0.1
  [✔] ferritecore-6.0.1-fabric
  [✔] FogLooksGoodNow-2.2.0+1.20.1
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] forgero-fabric-0.12.0-rc-4+1.20.1
  [✔] forgottengraves-1.20.1-3.2.6
  [✔] FPS-Monitor-1.20-1.3.0-Fabric
  [✔] friendsandfoes-beekeeperhut-fabric-mc1.20.1-2.0.0
  [✔] friendsandfoes-fabric-mc1.20.1-2.0.10
  [✔] friendsandfoes-flowerymooblooms-fabric-mc1.20.1-2.0.1
  [✔] geckolib-fabric-1.20.1-4.4.4
  [✔] geophilic-v2.2.0-mc1.20u1.20.2
  [✔] Gobber2-Fabric-1.20.1-2.9.5
  [✔] guarding-2.4.0
  [✔] handcrafted-fabric-1.20.1-3.0.6
  [✔] holdthatchunk-2.0.1+1.19
  [✔] iammusicplayer-fabric-mc1.20-3.22.0-alpha.4
  [✔] ibo-1.0.0
  [✔] Icarus-Fabric-2.7.1
  [✔] ImmediatelyFast-Fabric-1.2.12+1.20.4
  [✔] immersive_aircraft-0.7.5+1.20.1-fabric
  [✔] immersive_paintings-0.6.7+1.20.1-fabric
  [✔] Incendium_1.20.4_v5.3.4
  [✔] indium-1.0.30+mc1.20.4
  [✔] interiors-0.5.3+fabric-mc1.20.1
  [✔] inventoryessentials-fabric-1.20.1-8.2.3
  [✔] iris-1.7.0+mc1.20.1
  [✔] jei-1.20.1-fabric-15.3.0.4
  [✔] k9mod-1.0.2
  [✔] krypton-0.2.3
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] lanterns-belong-on-walls-1.6.1+1.20.1
  [✔] lavender-0.1.6+1.20
  [✔] lazydfu-0.1.3
  [✔] letsdo-API-fabric-1.2.9-fabric
  [✔] letsdo-candlelight-fabric-1.2.11
  [✔] letsdo-herbalbrews-fabric-1.0.6
  [✔] letsdo-meadow-fabric-1.3.8
  [✔] letsdo-vinery-fabric-1.4.15
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] lmft-1.0.2+1.20-fabric
  [✔] lovely_snails-1.1.3+1.20.1
  [✔] mcda-5.0.2
  [✔] mcde-1.5.7-1.20
  [✔] mcdw-9.0.4
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] memoryusagescreen-fabric-mc1.20-1.9.0
  [✔] minecraft-comes-alive-7.5.14+1.20.1-universal
  [✔] MixinConflictHelper-1.2.0
  [✔] mixintrace-1.1.1+1.17
  [✔] mobtimizations-fabric-1.20.1-1.0.0
  [✔] modelfix-1.15-fabric
  [✔] modernfix-fabric-5.17.0+mc1.20.1
  [✔] modmenu-7.2.2
  [✔] moonlight-1.20-2.11.12-fabric
  [✔] moreculling-1.20.4-0.24.0
  [✔] MoreCullingExtra-1.1-1.20.1
  [✔] MouseTweaks-fabric-mc1.20-2.26
  [✔] mru-0.4.0+1.20
  [✔] mythicmetals-0.19.7+1.20.1
  [✔] mythicmetals-decorations-0.6.0+1.20
  [✔] Necronomicon-Fabric-1.4.2
  [✔] nerb-1.20.1-0.3-QUILT
  [✔] neruina-1.3.0-fabric+1.18.2-1.20.1
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] noisium-fabric-2.0.2+mc1.20-1.20.1
  [✔] no-telemetry-1.8.0
  [✔] notenoughanimations-fabric-1.7.2-mc1.20.1
  [✔] nvidium-0.2.6-beta
  [✔] Obscure-API-16
  [✔] ochetgenyo-1.2.0+1.20
  [✔] otyacraftengine-fabric-mc1.20-3.7.0-alpha.2
  [✔] owo-lib-0.11.2+1.20
  [✔] Patchouli-1.20.1-84-FABRIC
  [✔] Pehkui-3.8.0+1.14.4-1.20.4
  [✔] peripheralium-fabric-1.20.1-0.6.15
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] Plethora-Fabric-1.11.7
  [✔] polymorph-fabric-0.49.3+1.20.1
  [✔] PresenceFootsteps-1.9.3
  [✔] profundis-1.6.2
  [✔] PuzzlesLib-v8.1.18-1.20.1-Fabric
  [✔] raknetify-fabric-0.1.0+alpha.5.122-all
  [✔] ReEnchantments-1.20.1-1.1.1
  [✔] reeses_sodium_options-1.7.2+mc1.20.1-build.101
  [✔] regeneration-42.0.0
  [✔] resourcefulconfig-fabric-1.20.1-2.1.2
  [✔] resourcefullib-fabric-1.20.1-2.1.24
  [✔] Resourcify (1.20-1.20.1-fabric)-1.3.4
  [✔] revelationary-1.3.7+1.20.1
  [✔] Runelic-Fabric-1.20.1-18.0.2
  [✔] scannable-MC1.20.1-fabric-1.7.12+18ccb75
  [✔] scarves-1.3.0
  [✔] scriptor-1.0.4-1.20.1-sgd
  [✔] servercore-fabric-1.5.1+1.20.1
  [✔] simplehats-fabric-1.20.1-0.2.4
  [✔] simplyswords-fabric-1.55.0-1.20.1
  [✔] sleep_tight-1.20-1.1.19-fabric
  [✔] sleepwarp-2.2.0_rc1+1.20.1
  [✔] smallships-fabric-1.20.1-2.0.0-b1.1
  [✔] smarterfarmers-1.20-1.8.2-fabric
  [✔] smoothchunk-fabric-1.20.1-3.6
  [✔] sodium-extra-0.5.4+mc1.20.1-build.115
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] spectrum-deeper-down-1.7.8
  [✔] spelunkery-1.20.1-0.3.5-fabric
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Statement-4.2.9+1.14.4-1.20.4
  [✔] Steam_Rails-1.6.3+fabric-mc1.20.1
  [✔] Stellarity-v2-0e
  [✔] stendhal-1.4.1-1.20
  [✔] tectonic-fabric-1.20-2.3.4
  [✔] tempad-fabric-1.20.1-2.3.3
  [✔] things-0.3.3+1.20
  [✔] tooltipfix-1.1.1-1.20
  [✔] travelersbackpack-fabric-1.20.1-9.1.12
  [✔] TravelersTitles-1.20-Fabric-4.0.2
  [✔] trinkets-3.7.2
  [✔] turtlematic-fabric-1.20.1-1.2.6
  [✔] UniversalEnchants-v8.0.0-1.20.1-Fabric
  [✔] vanish-1.5.4+1.20.1
  [✔] VanitySlots-1.2.9
  [✔] vcinteraction-fabric-1.20.1-1.0.6
  [✔] videotape-1.3.0
  [✔] visuality-0.7.1+1.20
  [✔] VisualWorkbench-v8.0.0-1.20.1-Fabric
  [✔] voicechat-fabric-1.20.1-2.5.12
  [✔] watut-fabric-1.20.1-1.1.1
  [✔] weaponmaster-client-only-fabric-1.20.1-3.0.5
  [✔] Weeping-Angels-46.0.1-fabric
  [✔] xercamusic-fabric-1.20.1-1.0.1
  [✔] xlpackets-1.0.4-1.20.x
  [✔] YetAnotherConfigLib-3.4.1+1.20.1-fabric
  [✔] YungsApi-1.20-Fabric-4.0.4
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.4
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4`
