### ISSUE TITLE
2 Slight problems

### ISSUE THREAD

**Issue by The-Rose-Composer** [amblelabs/ait#302]
I think I might just be stupid, but I can't seem to find the solution to this anywhere ):
I recently started up my own survival server with only AIT installed, and I have gotten almost every material to craft a Tardis
The only problem is, I don't actually know how to get dead brain coral. The only thing I could find online is getting regular alive brain coral with silk touch, but you can't mine dead brain coral with silk touch, only alive coral. I tried everything from exploding it to pistoning it, but I can't get dead brain coral to drop so that I can use it in the crafting table.
Second question, this is also crafting related: How do you craft a stattenheim remote? I looked in JEI, but it didn't list a recipe, so a little help with that would be great.
So sorry to bother you guys with this, and I hope you have a good rest of your day!

**Comment by miner100910** [comment]
You can mine the dead coral with silk touch, you always have been able to, and about the stattenheim remote, you can't craft it because Loqor is both too lazy to make a fucking recipe for the thing AND it's very buggy and acts as an unlimited range version of the sonic in TARDIS mode

**Comment by Loqor** [comment]
Erm, I don't appreciate the language used, but there's good reason to why the stattenheim remote is uncraftable.
It's meant to be a creative only item that we implemented for fun, it's not supposed to be part of the survival game loop. It also shouldn't be buggy in the coming update, and we may as well remove it if we get continued comments like this.
I would like you to be more respectful in future. Thanks.

**Comment by fastcargo99** [comment]
Oh, well that helps regardless. You can summon the Tardis with the sonic? That's neat! Although, I found out the problem with the silk touch. I had been breaking the coral with a silk touch shovel, and that breaks regular coral, but not dead coral. You can only break dead coral with a pickaxe. Not a shovel, axe, or hoe. I found this after I did some testing. Not sure why it works like that, but perhaps that could be specified somewhere in the future?
