### ISSUE TITLE
Tardis turns back into coral exterior and becomes unusuable.

### ISSUE THREAD

**Issue by The-Rose-Composer** [amblelabs/ait#304]
**Describe the bug**
I recently crafted a Tardis on my multiplayer server, and now it will not work at all. I got the nether star and reconfigured the interior, and everything worked fine for a day. I could fly anywhere, the controls worked, and nothing was wrong with it. Now, the exterior has changed from a police box, back into a coral exterior (the exterior after you first grow the Tardis.) Now, interacting with the console's hitbox causes them to disappear entirely, which is a serious problem since I can't fly the Tardis. I then tried placing down a second console, but the Tardis door will NOT close even if I change the exterior, meaning I can't take flight. I also cannot refuel the Tardis, and if I open the monitor, I can't click on the settings tab to change the interior. My Tardis is basically a vegetable, and I can't do anything with it. I can't summon it with my screwdriver either. Another interesting thing, when I exit my Tardis, it teleports me back to where I first grew it, NOT where the exterior currently is. I only have adventures in time installed on the server, so I have no clue why this would happen. It might be because I recently restarted the server?
**To Reproduce**
Absolutely no clue, 
**Expected behavior**
Tardis should not change its exterior back into the growth one and stop working entirely. Exiting interior should not teleport me back to where the Tardis first grew, it should teleport me to where the Tardis exterior currently is.

**Screenshots**
Hitboxes disappear when clicking:
![2024-05-13_13 10 02](https://github.com/Loqor/ait/assets/169574851/1abc988a-d5da-40e6-ab98-47e0fd7d6fe1)
Tardis spawns me in the roof when entering:
![2024-05-13_13 10 54](https://github.com/Loqor/ait/assets/169574851/2a8b393f-c68e-4aac-9c7f-70281742235f)
Settings menu does not work:
![2024-05-13_13 11 24](https://github.com/Loqor/ait/assets/169574851/ce3d5f4b-e7d8-42d1-ad5a-add78082d7f2)

**AIT Version:**
Provide the version of AIT this is on
1.0.4
**Additional context**
AIT is the only mod on the server side
Client side has Journeymap, JEI, and litematica

Thank you for any help given, it really means a lot. I've really been enjoying this mod and I hope that there might be some way to fix my Tardis haha.

**Comment by fastcargo99** [comment]
Quickly adding onto this, here is the JSON file for my Tardis, not sure if 
[2c30b903-a4fe-43cb-8d03-a2fcf20a7150.json](https://github.com/Loqor/ait/files/15298028/2c30b903-a4fe-43cb-8d03-a2fcf20a7150.json)
this helps at all.

**Comment by Loqor** [comment]
also a bug thats been fixed in the coming update.
