### ISSUE TITLE
Unlockable Dimensions?

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#305]
I know, I know, the Tardis is always going to be overpowered just by nature, but being able to just pop over to any dimension right out the door might be fixed pretty easily by requiring the player to feed the Tardis a medium-difficulty item from the dimension in question, like netherite scrap for the Nether, chorus fruit for the End, a zanite gem for the Aether, etc. That way you still have to get to the dimension in question via the vanilla route before you can fly there~

**Comment by Duzos** [comment]
could feed it from telepathic circuit, could be cool
but how would modded dimensions work..

**Comment by Loqor** [comment]
We could also just allow you to use a modded item from that dimension ig. could make it data generated, not sure.

**Comment by miner100910** [comment]
Could make it so once the owner or a high loyalty crew member of a TARDIS enters that dimension then the TARDIS is able to go there via some sort of telepathic circuit linking system

**Comment by DrTheodor** [comment]
I side with Masker here.
Some "item from a dimension" is pretty vague, also won't solve the issue for datapack dimensions and situations where the server has a multiworld setup.

**Comment by DrTheodor** [comment]
who the fuck added stale bot

**Comment by MaketendoDev** [comment]
Lololol

**Comment by Duzos** [comment]
> who the fuck added stale bot

😁
