### ISSUE TITLE
Sonic Screwdrivers do not render in the sonic port on custom consoles.

### ISSUE THREAD

**Issue by rhamn0us** [amblelabs/ait#306]
**Describe the bug**
Sonic Screwdrivers do not render on custom console textures. 

**To Reproduce**
1. Have a custom console texture.
2. Put the Sonic Screwdriver in the sonic port.

**Screenshots**

![image](https://github.com/Loqor/ait/assets/62453042/02ec31be-b366-44dc-a10e-6e96896ece76)

**AIT Version:**
Latest Current Release.

**Additional context**
This was purely AIT, no other mods installed.

**Comment by Duzos** [comment]
Changed via datapack?

**Comment by rhamn0us** [comment]
That's correct, it's a custom console texture from a datapack.

**Comment by Duzos** [comment]
I'm guessing datapack console variants reset the offset and rotation of the sonic

my suggestion to fix is to ensure
```java
	public Vector3f sonicItemTranslations() {
		return new Vector3f(0.1f, 1.2f, 0.26f);
	}

	public float[] sonicItemRotations() {
		return new float[]{120f, 135f};
	}
```

are overwritten to match their parents in `ClientConsoleVariantRegistry#convertDatapack`

**Comment by Duzos** [comment]
yes

**Comment by Loqor** [comment]
Fixedadoodledo
