### ISSUE TITLE
[Idea] Exterior Scanner

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#307]
For the sake of those who play without Immersive Portals, there should be a way to tell from the inside what blocks/liquids are immediately outside the Tardis' door. Currently there's no way to tell aside from walking out, and if you happen to be in or above a lava pool or something, there's no way to know! Maybe make it part of the monitor block, or a new button on the console that prints the block ID's to the chat or something.

**Comment by PasteleiroB96** [comment]
I suggest something similar,  it was with entities
LMAO

**Comment by kalethemonster** [comment]
yeah this is cool and a need, as IP doesnt really work with half my optimization mods

**Comment by Flexico** [comment]
YES, this is still a need!

**Comment by DrTheodor** [comment]
Get stale issued

**Comment by DrTheodor** [comment]
Oh also
You can now hear from the interior if its snowing/raining or lava/water pouring (since 1.0.5)

**Comment by Duzos** [comment]
what he said
