### ISSUE TITLE
Coral Console... a laggy machine

### ISSUE THREAD

**Issue by PasteleiroB96** [amblelabs/ait#309]
**Describe the bug**
Every time that the Coral Console is on the screen,  my pc start to die
((but this dosent apply for the hologram))

**To Reproduce**
1. Go to 'The Console'
2. Click on 'Console Cache'
3. Select 'Coral Console 
4. Click on 'Console Thing with Sonic Scrwedriver'
5. See error

**Expected behavior**
The FPS its INCREDIBLY reduced

**AIT Version:**
The current version

**Additional context**
I tryed with Entity Culling to see if it help, but no,  it dosent

**Comment by DrTheodor** [comment]
I improved the console rendering code in one of my latest commits.

(Not gonna close the issue cause i didnt compare the performance before and after)

**Comment by PasteleiroB96** [comment]
> I improved the console rendering code in one of my latest commits.
> 
> (Not gonna close the issue cause i didnt compare the performance before and after)

Thanks fella,  i wont close it for the same reason too
