### ISSUE TITLE
Emission does not render properly.

### ISSUE THREAD

**Issue by funniman-exe** [amblelabs/ait#312]
**Describe the bug**
The consoles do not have any emission at all. Whatsoever. This is extremely apparent with the Toyota Console, causing it to be grey instead of Orange or Green/Blue. This issue also exists for the TARDIS -- only being able to see the emission when dematerializing or rematerializing.

**To Reproduce**
1. Look at Console or TARDIS
2. yay, issue!!1

**Expected behavior**
Emission is actually visible

**Screenshots**
![image](https://github.com/Loqor/ait/assets/112577221/d7aedda7-bb35-4a23-882e-c027e435d826)
![image](https://github.com/Loqor/ait/assets/112577221/43f20fca-caf7-4884-b9f0-4ffca44094d7)
![image](https://github.com/Loqor/ait/assets/112577221/6c1de1d2-242f-4ecd-a348-b287104a8188)
![image](https://github.com/Loqor/ait/assets/112577221/a7397df0-06bb-44e8-b4a3-0ad626830cf8)

**AIT Version:**
1.0.4

**Additional context**
I am using the following mods:

AIT (obviously)
cloth-config 11.1.118
continuity 3.0.0
create fabric 0.5.1
fabric api 0.92.2
fabric language kotlin 1.11.0
geckolib fabric 4.4.4
immersive portals 3.3.9
indium 1.0.27
iris 1.5.11
k9mod 1.0.2
lithium fabric 0.11.2
owo lib 0.11.2
portalgun 6.0.1
power networks 2.0.1
regeneration 42.0.0
sodium fabric 0.5.3
worldedit 7.2.15

Plus a custom TARDIS exterior

**Comment by Everelsu** [comment]
The Iris mod conflicts without it, everything was rendered correctly.

**Comment by theOneTrueFunniBoi** [comment]
> The Iris mod conflicts without it, everything was rendered correctly.

How unfortunate. I guess if I want it to look right, I'll have to ditch my shaders.

**Comment by TheRealBb8fan1** [comment]
Just use Canvas Renderer. It's better!
