### ISSUE TITLE
[IDEA] Block that detects the status of TARDIS power or flight

### ISSUE THREAD

**Issue by funniman-exe** [amblelabs/ait#315]
**Is your feature request related to a problem? Please describe.**
There's no clear way to trigger functions or redstone (*without mods*) to detect whether the TARDIS had power, or is in flight, or has some other function active.

**Describe the solution you'd like**
A block that emits a redstone signal when a certain TARDIS property is active, the selected property can be changed via a menu of sorts.

**Additional context**
I'm getting this from the fact that TARDIS Refined has a similar feature for whether the TARDIS is in flight or not.

**Comment by TheRealBb8fan1** [comment]
There's already a block in the mod that detects it.

**Comment by theOneTrueFunniBoi** [comment]
> There's already a block in the mod that detects it.

Which block?

**Comment by TheRealBb8fan1** [comment]
The detector block.

**Comment by theOneTrueFunniBoi** [comment]
I see.
