### ISSUE TITLE
Datapack interior help please?

### ISSUE THREAD

**Issue by kalethemonster** [amblelabs/ait#317]
ive been making a datapack interior, but i cant get it to work for the life of me. ive done a bunch to try and troubleshoot, even changing my namespace to ait, but it hasn't worked, and i do have all the mods i used blocks from installed. i also have the limitless structure block mod which i used before to get it all into the selection installed as well. here's the datapack, and the link to the mod collection that it reqires
[nebulae.tardis.zip](https://github.com/user-attachments/files/15709942/nebulae.tardis.zip)
https://modrinth.com/collection/m2OinSLO

it would also be helpful for a mention of what you edited to make it work so i know for next time :)

**Comment by DrTheodor** [comment]
Hello!
Does your datapack show up in `/datapack list`?

**Comment by DrTheodor** [comment]
Oh, i think i found the problem.

Your desktop json file looks like this:
```json
"id": "nebulae:nebulae"
```
But this is not valid json!
It should be like this instead:
```
{
    "id": "nebulae:nebulae"
}
```
(spaces and line breaks dont matter here, but the curly braces do!)

**Comment by kalethemonster** [comment]
ah, thankyou!
