### ISSUE TITLE
[IDEA] More Craftable Functional Blocks

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#318]
NEW BLOCK 1: Co-ordinate display based on the one in Back to the Future's DeLorean! The existing monitor is certainly cool, but it only shows "destination" and "current location", even though the "previous location" is stored in memory. Plus it's backwards compared to Doc saying, "This one tells you where you're going, this one tells you where you are, this one tells you where you were" that's been crystal clear in my memory since childhood. X3
![image](https://github.com/Loqor/ait/assets/5751770/914f129f-f06c-4f88-95b4-9f3d8a9cbdd0)

NEW BLOCK 2: Artron crystal block (preferrably with a 3D crystal model) for charging/discharging power between the Tardis' core and the handheld "charged zeitron crystals"! Related to a recent discussion about the rift power system, I love the idea of building mechanisms that can interact with the Tardis' systems and add more uses for the Rift Chunks and Artron Collectors.

**Comment by Flexico** [comment]
Wait, "completed"?

**Comment by Addi3** [comment]
github auto set it as that cus it was inactive
