### ISSUE TITLE
[IDEA] Recipe Adjustments

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#323]
Recipe 1: TARDIS CORAL
It doesn't make much sense to me that crafting the Tardis Coral requires a *dead* brain coral; it seems like it should be a *living* brain, even if it's abbie-normal. The other semi-endgame items required make sense, but I feel like zeitron crystals should be involved, since they're specially added by the mod.

Recipe 2: RIFT SCANNER
Considering this thing looks exactly like a compass, and functions like a compass, the recipe looks nothing like the compass recipe. My suggestion is to place a vanilla compass in the middle, and four zeitron crystals above, below, left, and right of it.

I'm not really annoyed by other recipes, except that zeiton needs more inclusion~

**Comment by DrTheodor** [comment]
@Loqor what do you think

**Comment by Flexico** [comment]
Wait, hang on, "completed"? What's all this about threads being "stale" now anyway?
