### ISSUE TITLE
[Proposal] Doc issue

### ISSUE THREAD

**Issue by nitrogenez** [amblelabs/ait#324]
## TL;DR

Many devs who are interested in the project might consider making an addon, though the problem is: the tooling is unknown unless the code is read. So this would be nice to have technical documentation of the APIs.

## Contents

There is a popular doc framework, if you would call it like so, called hugo. It's used by many projects: Helix text editor,  Hyprland, OhMyPosh, etc. I propose to make open docs for AIT, so that addon creators will be able to make their dreams cone true easier.

**Comment by DrTheodor** [comment]
I already started working on it
I just need to get more repo permissions from Loqor

**Comment by DrTheodor** [comment]
New wiki WIP currently hosted here: https://theo.is-a.dev/ait-wiki/
