### ISSUE TITLE
Backwards compatiblity for save data

### ISSUE THREAD

**Issue by drtheodor** [amblelabs/ait#325]
Current list of properties that need to be migrated to v2 AND made backwards compatible:
- [ ] `hum_enabled`
- [ ] `alarm_enabled` 
- [ ] `find_ground`
- [ ] `last_locked`
- [ ] `siege_held`
- [ ] `siege_time`
- [ ] `hail_mary`
- [ ] `is_falling`
- [ ] `antigravs_enabled`
- [ ] `hads_enabled`
- [ ] `is_in_active_danger`
- [ ] `is_in_real_flight`
- [ ] `demat_ticks`
- [ ] `mat_ticks`
- [ ] `cloaked`
- [ ] `console_disabled`
- [ ] `leave_behind`
- [ ] `hostile_presence_toggle`

Current list of properties that are migrated but don't have any backwards compatibility implemented:
- [ ] `power`
- [ ] `has_engine_core`
- [ ] `handbrake`
- [ ] `auto_land`
- [ ] `speed`
- [ ] `max_speed`

List of data structures that don't have backwards compatibility implemented:
- [x] `TardisDesktop` 
- [ ] `AbsoluteBlockPos` (deprecated, but same applies to `GlobalPos`)
- [ ] `AbsoluteBlockPos.Directed` (deprecated, but same applies to `DirectedBlockPos` and `DirectedGlobalPos`)

**Comment by TheDJGamerYT** [comment]
i might be able to help but gimme a hour to learn java im 3 episodes in to kaupenjoe - The DJ

**Comment by TheRealBb8fan1** [comment]
You're a man of culture I see.
