### ISSUE TITLE
Console Block Entity Rewrite

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#33]
Currently the ConsoleEnum is stored in the tardis, meaning its global. With that, it would also be easier on the tardis data being stored, and look a lot cleaner than if we kept storing it in the tardisData.

**Comment by Duzos** [comment]
should be safe for merge now : )

**Comment by Duzos** [comment]
issue idk how to fix rn - 
when you break the block the type resets but only on client

**Comment by Duzos** [comment]
to change console right click w command block - needs changing to smth else in future
