### ISSUE TITLE
The addition of the Iris Shaders mod caused Tadis to stop glowing

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#332]
**Describe the bug**
The addition of the Iris Shaders mod caused Tadis to stop glowing

**Comment by smallmoss233** [comment]
![2024-07-21_11 28 13](https://github.com/user-attachments/assets/0398390a-4e1a-4d1f-b4f8-77787a44aec9)
bug?

**Comment by Addi3** [comment]
Shaders dont work with ait as of 1.0.4

**Comment by DrTheodor** [comment]
Was fixed in 1.0.5, currently available dev builds

**Comment by MaketendoDev** [comment]
Aight time to close this (:<

**Comment by DrTheodor** [comment]
oh right
