### ISSUE TITLE
tardis invisable 

### ISSUE THREAD

**Issue by MrQuestion22** [amblelabs/ait#334]
**Describe the bug**
when i reload in to my save world my tardis is there but i cant use it or see the exterior 

**Expected behavior**
My Tardis still be visible and useable when i load back  in 

**Screenshots**
![20
![2024-08-02_07 51 10](https://github.com/user-attachments/assets/d0d816cf-b22b-415e-ab90-9fefbd862f09)

**AIT Version:**
aitforger-1.0.4-0.0.1

**Additional context**
no other additional context

**Comment by DrTheodor** [comment]
Can i take a look at the logs?

**Comment by MrQuestion22** [comment]
> Can i take a look at the logs?

like logs in the game chat

**Comment by DrTheodor** [comment]
Open your `.minecraft` folder, then to go `logs` and drag and drop the latest.log file to your comment text field.

**Comment by MrQuestion22** [comment]
[2024-08-01-2.log.gz](https://github.com/user-attachments/files/16468174/2024-08-01-2.log.gz)
idk if this the right one
