### ISSUE TITLE
Mood system 

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#338]
- [ ] Triggers for mood rolls influenced by the priority moods, e.g. TardisEvents
- [ ] TardisEvent for DoorEnter/DoorExit
- [ ] Some way to detect if its been longer than a specific time for someone to have been in the interior
- [ ] Loyalty and Mood are intertwined, so make them further intertwined by adding sounds that play when you do specific actions that the TARDIS hates/dislikes

-Instead of increasing all the emotions it'll choose 1 of the emotions and then increase that specific one,example if you hit it with the hammer it wont increase all 5 emotions,it'll grab 1 of them and increase that one,if you do it again it'll be a diffrent one (or the same one with chance)

-NEGATIVE MOODS

ANGRY/HURT/DISSAPOINTED/DEPRESSED/HATEFUL
Hit the console with the hammer

DISSANPOINTED/FRUSTRATED
Miss flight event/let water seep in

HATEFUL/ANGRY
Crash the tardis

FEARFUL/ANXIOUS
Travel to any dimension aside the overworld/locate a end city/fortress or if a reject is present inside the interior

UPSET/HURT/DISSAPOINTED
If a bound key gets destroyed

JELOUS
If a pet is present in your interior or you bind a key to someone else's tardis

DEPRESSED
Lack of anyone being in the tardis interior for 2 MC days

-NEUTRAL MOODS

BORED/IMPASSIVE/LONELY
Lack of anyone being in the tardis interior for 1 MC day

TIERD/MEDIOCRE
Travel at night time with the tardis (mc has a sun detector or whatever so just copy that code ig)

CURIOUS/CALM
Land near a structure (i ran out of ideas for calm)

INDIFFRENT/TOLERANT/MANIAC
Negative mood increase/neutral increase can randomly go towards these instead of the original one

-POSITIVE

COPERATIVE/CONTENT/HAPPY
Do a flight event correctly

OPTIMISTIC/HOPEFUL/ENTHUSIASTIC
Use the telepathic circuits or any general feature of the tardis like shields (has a cooldown) or travel more then 2000 blocks in a flight.

JOYFUL/EXCITED
Change the interior/hum/exterior/console (has a cooldown)

GRATEFULL/RELIVED
Come back to the tardis after abandoning it for 1+ MC day

**Comment by MaketendoDev** [comment]
should we close this now since it's already done?

**Comment by Duzos** [comment]
its done enough for this update
