### ISSUE TITLE
"Gold key emergency summon" (prolly for 1.0.5)

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#345]
If you have a artron collector unit in your offhand with 1500 AU (its max charge) and you hold a binded golden key

You can then shift right click to empty the AU into the key,the key then stays mid air as the tardis slowly "appears" (like really slowly)

This can work from any distance,but the further away the longer the summon takes.

Once the key is used it cant be taken back,once the tardis fully appears the key shatters

**Comment by Duzos** [comment]
naw
