### ISSUE TITLE
texture issues on shalka

### ISSUE THREAD

**Issue by drtheodor** [amblelabs/ait#347]
![image](https://github.com/user-attachments/assets/ff41bb7d-90ad-4552-8f25-7e88d8945fa4)

**Comment by Loqor** [comment]
I'm gonna krill maggie

**Comment by Duzos** [comment]
i assume [this commit](https://github.com/pavatus/ait/commit/0a3b1582af551f1cb0dcbb087ff1882c96f407f8) fixes
