### ISSUE TITLE
Vortex sounds offset

### ISSUE THREAD

**Issue by Ouroboros-Games** [amblelabs/ait#348]
**Describe the bug**
The door time vortex sounds are offset 10-11 blocks west of the console (when using the hourglass interior) regardless of the actual door position

**To Reproduce**
1. Create TARDIS in AIT 1.0.5
2. Switch to hourglass interior (Coral is unaffected, crystaline is affected too but sounds occur on the roof towards the Southwest side, other affected/unaffected interiors unknown so far)
3. Dematerialise
4. Go to the outer walkway to the west of the console and hear the vortex sounds (the door is North)

**Expected behavior**
Vortex sounds occur around/at the door

**AIT Version:**
1.0.5

**Comment by Duzos** [comment]
the vortex sound handler never updates door position
it should listen to the DOOR_MOVE event and update accordingly
