### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by MatrixRebel** [amblelabs/ait#349]
**Describe the bug**
When loading the mod on a dedicated server I am getting crashes every time stating "Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER"

I have tried making a complete fresh server with no other mods except dependencies for AIT and I still get the same crash every time.

**To Reproduce**
Install the mod on a dedicated server and then boot the server

**AIT Version:**
aitforger-1.0.5-0.0.1

**Comment by Duzos** [comment]
attach crash report

**Comment by DrTheodor** [comment]
Im already fixing this

**Comment by MatrixRebel** [comment]
I’m guessing if you’re already on it you don’t need me to upload a crash report? Also thanks for the fast response
