### ISSUE TITLE
immersive portals

### ISSUE THREAD

**Issue by YeeeeeahBoyee** [amblelabs/ait#351]
the wall of the tardis is rendering inside of the door portal when opened 

open tardis door 

**AIT Version:**
1.0.5

**Additional context**

https://github.com/user-attachments/assets/a9988f84-0016-4a0b-87e5-0526dae23272

other being used mods
immersive-portals-3.3.9-mc1.20.1-fabric
iris-mc1.20.1-1.6.11
sodium-fabric-mc1.20.1-0.5.3

**Comment by DrTheodor** [comment]
@Loqor correct me if im wrong 
But i dont think we can do anything about it..?

**Comment by Loqor** [comment]
We can't, rendering issue sadly.
