### ISSUE TITLE
ARS System

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#356]
- [ ] GUI for placing them in the interior
- [ ] 2D map of the entire interior space
- [ ] Render the structures of different ARS builds
- [ ] Being able to select them to generate
- [ ] In the GUI, a selection to switch between top-down and side views from each direction
- [ ] Add some kind of corridor door
- [ ] Sealing the place where you place it off
- [ ] Add ad figure out jigsawed sections to autogenerate a default engine room in each interior (require them for interior datapacks as well)
- [ ] Add datapack compatibilty for different ARS builds
- [ ] Accessible from an ARS block perhaps? or maybe some kind of system where you have to give a fraction of the blocks necessary for the build?

**Comment by Flexico** [comment]
What is ARS?

**Comment by Duzos** [comment]
split this up into multiple issues and id start on it

**Comment by Duzos** [comment]
^

**Comment by Duzos** [comment]
removing from 1.2.0 until more details are given.
