### ISSUE TITLE
TARDIS UUID's vanish on client when unloaded

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#360]
**Describe the bug**
The client seems to only be able to access the currently loaded tardises (duh)

**To Reproduce**
- go really far away from a tardis
- go into the interior of a tardis

- use /ait link and see the single autofill
- hover over a stattenheim remote 

**Expected behavior**
UUIDs to be there

**AIT Version:**
latest dev as of time of creation

**Additional context**

**Comment by Duzos** [comment]
my dementia got cured
