### ISSUE TITLE
Spaaaaaaace

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#362]
- [ ] Space
- [ ] Physically rendered planets that you can fly to
- [ ] Cool space skybox
- [ ] Gravity
- [ ] Air
- [ ] Moon?
- [ ] Mars?
- [ ] Varos (for zeiton)

**Comment by kalethemonster** [comment]
SPACE! gotta see it all! hn-hn-hn!

**Comment by Duzos** [comment]
split this issue up into multiple, more specific issues
