### ISSUE TITLE
Zeiton Caves

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#363]
Imagine the Cave of Swords in Mexico + Energon caves from Transformers.
Dripstone-like zeiton "blades" of crystal, that grow from the floor, ceiling, and walls, and can intersect.
When going into this cave, you need a respirator, and radiation pills so you don't get Artron sickness.
Checklist:
- [ ] Zeiton cave biome/feature
- [ ] Zeiton crystals and their generation
- [ ] Artron sickness
- [ ] Radiation pills

**Comment by Duzos** [comment]
reopen later
