### ISSUE TITLE
Immersive portals problems and game crash

### ISSUE THREAD

**Issue by GlobsterJail1212** [amblelabs/ait#364]
**Describe the bug**
When switching exteriors to any police box exterior (save toyotamak and coral), the immersive portals portal appears a block in front of the door instead of in the door itself. Leaving the game while having a police box exterior active causes the game to crash upon attempting to reload the world.

**To Reproduce**
1. Spawn a TARDIS
2. Change exterior to any non-toyotamak or coral police box exterior
3. (Optional) Open the door
4. Leave the game

**Expected behavior**
Immersive portals portal appearing in the doorway.
World loading like normal, without crashing the game

**Screenshots**
![2024-08-18_18 30 44](https://github.com/user-attachments/assets/6456388a-7bfe-4f65-8b0d-3b5a83ac5385)

**AIT Version:**
1.0.5-1.20.1-release

**Comment by Duzos** [comment]
already sorted
