### ISSUE TITLE
Choice of whether to receive distress calls

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#369]
there is already a "receiveCalls" property which is used, there needs to be a frontend way of updating this property (maybe security screen?)
@Loqor

**Comment by Duzos** [comment]
bump

**Comment by Loqor** [comment]
Will add to security screen

**Comment by Loqor** [comment]
@Duzos there just isnt a property for that but ok

**Comment by Duzos** [comment]
its in `StatsHandler`

**Comment by Loqor** [comment]
This is finished now
