### ISSUE TITLE
Vertical Height Search can send you under bedrock

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#370]
i had it on "Ceiling" travelling to -64

**Comment by Loqor** [comment]
@Duzos does this still happen you think

**Comment by Duzos** [comment]
prolly
test it out

**Comment by DrTheodor** [comment]
oh thats
funny
ceiling uses minecraft's heightmap
so it shouldn't do that, unless theres no safe y position at all

**Comment by Duzos** [comment]
how weird
maybe it wasn’t ceiling icr it’s old
