### ISSUE TITLE
Tardis Alarm glitch

### ISSUE THREAD

**Issue by LocalGuardian** [amblelabs/ait#379]
**Describe the bug**
The Tardis lights do not glow red when active

**To Reproduce**
I am unsure for any causes, as all i have done is hit the alarm switch and leave the tardis to check the colour

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![image_2024-09-06_203423540](https://github.com/user-attachments/assets/f86e79c4-42e5-4fe6-8d15-8ff9bc6f728b)
![image_2024-09-06_203520093](https://github.com/user-attachments/assets/440e39ac-75e9-4e82-b56f-135e5991569e)

**AIT Version:**
AIT Version is [FORGE] 1.0.5-1.20.1-release

**Additional context**
-3D Skin layer
-AIT
-Another furniture mod
-SCP Overtime
-Falling trees
-The graveyard
-Simplyswords
-Nature's compass
-More crafting tables

**Comment by TheDJGamerYT** [comment]
Use fabric forge is shitty buggy and the forge version of ait doesn't work too well

**Comment by DrTheodor** [comment]
@TheDJGamerYT *beep* wrong

**Comment by DrTheodor** [comment]
This looks like emissiveness rendering problem, and it was fixed in 1.0.6

**Comment by Duzos** [comment]
fixed in betas
