### ISSUE TITLE
Antigravity should work during falling

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#38]
this is basically my reminders app
alexa remind me to pack laptop and charger for the morning

anyway uh
during falling, if you toggle on antigravity it keeps falling
it makes more sense if the falling stops and it becomes a sold block again
just look at what happens when it hits a block and create a "forceLand" method based off that
and during ticks check if antigravs has been turned back on and if it has call the forceLand method

**Comment by Suff99** [comment]
thanks for the email reminder to pack my bag

**Comment by Duzos** [comment]
yw

**Comment by Loqor** [comment]
fixed by duzo bro just forgot to close the issue
