### ISSUE TITLE
Frooploof Exterior | Invalid locking + name

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#382]
Frooploofs exterior varients aren't lock but the rest of the police box varients are. They also dont have proper translations so they are 'exterior.frooploof.NAME' rather than just the name Version: ait-1.0.6.712-1.20.1-beta
![image](https://github.com/user-attachments/assets/aa4b4033-37cd-4898-9f97-90554da25705)

![image](https://github.com/user-attachments/assets/c0abeb75-9236-4ed2-bb94-ecb825d1bc3e)

**Comment by Duzos** [comment]
https://github.com/pavatus/ait/commit/8906baa2bdcc688cf07be7133709c6d247c13487

**Comment by Addi3** [comment]
🙏

**Comment by Loqor** [comment]
variants* and its not supposed to be locked. they're open to be used. I'm not bothered to lock them but I will add them to the translations ASAP.
