### ISSUE TITLE
game locks up while selecting dimensions

### ISSUE THREAD

**Issue by J0riUnderscore** [amblelabs/ait#383]
**Describe the bug**
While using my Tardis, when I use the dimensions button the game locks up. it doesn't freeze, I can move around but I cannot interact with any of the buttons, I cannot leave the Tardis, items disappear when I drop them instead of dropping onto the ground. I've gotten this bug with and without the Immersive Portals mod, while using the Immersive Portals mod I've been able to cycle through the nether and the end and Some of the Immersive Portals dimensions but after a few uses the game still locks up. Attempting to exit the world save when this happens my game gets stuck on the ' saving world ' load screen and I have to use task manager to close the game.

**To Reproduce**
1. Get a Tardis
2. Cycle through dimensions.

**Expected behavior**
The game to lock up and stop working.

**AIT Version:**
ait-1.0.5.1348-1.20.1-release.jar

**Comment by Duzos** [comment]
fixed in unpublished releases
