### ISSUE TITLE
The portal of the appearance of the 12th Dr. Ren is misaligned

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#387]
The portal of the appearance of the 12th Dr. Ren is misaligned

![屏幕截图 2024-10-13 100555](https://github.com/user-attachments/assets/79fe318e-57d4-4561-a9d9-e81fa709063f)

**Comment by smallmoss233** [comment]
![2](https://github.com/user-attachments/assets/c1076e13-c9fe-467d-9a8d-7ca0a24a2571)

**Comment by Duzos** [comment]
fixed in betas iirc
