### ISSUE TITLE
Player tracking

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#388]
Allows Tardis to track the coordinates entered by the player, saving TP the trouble of other players

Added a UI to the telepathic interface to give the player the option to decide where to go

Let's make the consoles of the 11th and 15th doctors

Integrate the operation of the waypoint library into the console, and the waypoint library can be used to store the waypoints

**Comment by Duzos** [comment]
player tracking exists in the form of the hypercube in betas
split your other suggestions into multiple issues
