### ISSUE TITLE
A better sonic driver

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#391]
I like the sound of the sonic driver in 1.0.5, but this version of the sonic driver only works for a while when you click

I think this screwdriver can refer to the Dalik mod and let the screwdriver work for a while before activating the function

There is also a sonic driver that enhances the scanning function, so that the scan can scan players, mobs, and track, for example, something on a player, the sonic driver will lock on to the player and keep tracking

Don't add subsystems!

**Comment by Duzos** [comment]
too late we already added subsystems

**Comment by smallmoss233** [comment]
How long ago was that? I forgot I also gave feedback on this.

**Comment by Duzos** [comment]
its being added rn
