### ISSUE TITLE
The upper part of Dr. War's console is partially gone

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#392]
When I use the 9 console's variant of the Doctor War console, I find that the top of this variant disappears, is it a bug?

**Comment by smallmoss233** [comment]
Is this a model problem or something

![798b5644e526edfeb98a512bcc94077a](https://github.com/user-attachments/assets/7cb8231f-04ad-43fa-9813-a159d3d78635)

**Comment by Duzos** [comment]
intentional
