### ISSUE TITLE
The remote control summons Tardis and does not show the range

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#395]
1.0.4 normal display range disappeared again to 1.0.5

**Comment by Duzos** [comment]
can u provide images

**Comment by smallmoss233** [comment]
> 你能提供图片吗

I can't upload my images, but I think this problem is harmless, mainly other issues such as the appearance portal misalignment after playing for 12 for a long time

**Comment by Duzos** [comment]
okay cool
portal is fixed in beta builds
