### ISSUE TITLE
pressing dimension button causes crash

### ISSUE THREAD

**Issue by NotGorgo** [amblelabs/ait#398]
**Describe the bug**
basically when im on my modpack and i press the dimention button while on server pack it causes the tps to go out of wack and cuase the server watchdog to activate.
**To Reproduce**
1. Go to tardis
2. Click on dimention change button
3. watch it kick you out of server
4. See error in crash logs

**Expected behavior**
change dimension with no crash

**AIT Version:**
1.0.5

**Additional context**
prominence 2 hasturian era mod pack

**Comment by Addi3** [comment]
its a 1.0.5 issue and is fixed in betas

**Comment by 1sckk** [comment]
> its a 1.0.5 issue and is fixed in betas

where do i find it, its not listed on curse forge

**Comment by Addi3** [comment]
you pay loqor on kofi and get access to them

**Comment by 1sckk** [comment]
how much and where

**Comment by Addi3** [comment]
https://ko-fi.com/loqor < here and you can do as much as higher than or $5 but make sure to join the discord server first and link your discord account to your kofi

**Comment by 1sckk** [comment]
> https://ko-fi.com/loqor < here and you can do as much as higher than or $5 but make sure to join the discord server first and link your discord account to your kofi

okay i paid and added my discord, what now

**Comment by Addi3** [comment]
if you are in the ait server you will get access to the donator and beta channels, if you didnt join the ait server, join it an send proof of purchase in general

**Comment by Duzos** [comment]
fixed in betas
