### ISSUE TITLE
[IDEA] Maximum TARDIS Limit

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#399]
**Is your feature request related to a problem? Please describe.**
Some times people make too much TARDISes these days and it can cause people with servers built onto a grape to lag alot (not looking at aternos 👀 ) but also servers that maybe would want to have limits for no apparent reason too 🤷  (Like a weird challenge)

**Describe the solution you'd like**
add a game rule (for dummies) or do a config for the limit to be adjustable and maybe also if you put like a -1 or something u get infinite tardises also if the player does accidentally craft a tardis on the limit then it can maybe delete it self and throws out the items you need to craft it (or something else you can decide!)

**Describe alternatives you've considered**
there is none ):<

**Additional context**
no

**Comment by Duzos** [comment]
imo requires #400
