### ISSUE TITLE
Flight Events (Code, not feature)

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#40]
Not flight events as in tasks while your flying. I mean events as in a fireable event.
eg TardisEvents.DEMAT 
you get me
this basically means stuff for api / addon mods and will also debloat the TardisTravel class as we could move stuff thats being stuffed in the demat method into their own seperate events

**Comment by Suff99** [comment]
am i sensing a inspired idea

**Comment by Duzos** [comment]
in school i thunk bro i can make events too its not just for like minecraft, maybe thatd get rid of the bloat
is sus tho mb

**Comment by Suff99** [comment]
nah i meant inspired by fabricmc lmaooo

**Comment by Duzos** [comment]
ooh 😭

**Comment by Duzos** [comment]
https://fabricmc.net/wiki/tutorial:events
asdhasdu
