### ISSUE TITLE
[IDEA] Tardis Self Destruct

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#400]
**Is your feature request related to a problem? Please describe.**
People often have multiple Tardis' or abandon them, I believe a method of removing a TARDIS would be useful.

**Describe the solution you'd like**
Tardis needs to have some kind of "#delete" method, which will remove it from all Tardis managers an delete all associated blocks and unlink all items.
An item of extreme power, eg nether star, could be consumed by the telepathic circuit and initialises self destruct. The tardis interior will be evacuated and (if enabled in config) it will cause an explosion at the exterior.

**Describe alternatives you've considered**
Could be initiated via GUI instead

**Additional context**
N/A

**Comment by MaketendoDev** [comment]
oooh that would feel soo cool if the interior exploads too where it would expload in a radius of 20 then 15 then 10 then 5 and would be a cool getaway lol. like in that one episode where the tardis gets reset but in our case it isn't reseting

**Comment by MaketendoDev** [comment]
kinda

**Comment by Duzos** [comment]
remove method already exists, self destruct can b added in 1.2.0
