### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#401]
### Version: ait-1.0.6.735-1.20.1-beta

- The new 'shalka' and 'hudolin' exteriors added in 1.0.5 they have a rogue pixel and the handles have no texture. Also there is a issue on the top part of the capsule interior door.

![image](https://github.com/user-attachments/assets/f2ebe372-237c-4a67-bc58-37868d17508f)
![image](https://github.com/user-attachments/assets/c6670dd6-42b4-48eb-a516-55be279a0382)
![image](https://github.com/user-attachments/assets/47fa0125-ef96-431c-bd06-5b903da71ff4)

**Comment by Addi3** [comment]
also on the 'exile' exterior the phone box part is on the wrong side of the door 
![image](https://github.com/user-attachments/assets/47a4adc0-fc27-43f8-bbd7-4fd5e370611d)

**Comment by Duzos** [comment]
according to loqor exile is intentional, idk about the others though

**Comment by Duzos** [comment]
capsule is a bug
