### ISSUE TITLE
Monitor Menu Textures are Outdated

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#406]
you forgot to update the monitor screen textures (the home page is fine but the other pages are still the old one)
![image](https://github.com/user-attachments/assets/5a1ffec0-2e94-4d46-a0c3-011369b0bc0b)

**Comment by Duzos** [comment]
this can come in 1.2.0

duplicate to #337

Loqor, please do this for 1.2.0

**Comment by TheMilkSnatcher** [comment]
tbh i think we can still use the home page's textures :P

**Comment by Duzos** [comment]
worked on by @MaketendoDev
