### ISSUE TITLE
Locked Dimensions Stay Locked (ClientSide)

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#409]
The Nether dimension is still grayed out even it's unlocked.
And The End dimension lit up even if it wasn't unlocked.

**Comment by Duzos** [comment]
use blaze powder on telepathic circuit to unlock

**Comment by Joggester** [comment]
AIT Version:
dev build #736 [ait-1.0.6.736-1.20.1-beta]

**Comment by Duzos** [comment]
end dimension can be left until 1.2.0 if we're in a time crunch

**Comment by Joggester** [comment]
> use blaze powder on telepathic circuit to unlock

it doesn't work

**Comment by Duzos** [comment]
wait nvm its not that its a netherite scrap

**Comment by Joggester** [comment]
> wait nvm its not that its a netherite scrap

I mean even after unlocking the Nether, the option displayed is still greyed out.

**Comment by Duzos** [comment]
after you right click the telepathic circuit with a netherite scrap it is greyed out?

**Comment by Joggester** [comment]
No, it is always grey, even when unlocked

**Comment by Duzos** [comment]
i see

**Comment by Joggester** [comment]
Wait, there is no problem with the function, it is just a display problem

**Comment by Duzos** [comment]
I see so you can go there but it *appears* grey

**Comment by Joggester** [comment]
Yes, The End is the opposite, it is white whether unlocked or not

**Comment by Duzos** [comment]
yes, i made #413 for that issue

**Comment by Duzos** [comment]
likely needs a sync
