### ISSUE TITLE
The FallingTardis being removed

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#41]
For example, when the tardis falls into the end void it gets deleted
When this happens the tardis gets stuck in an infinite fall loop
either we run "stopFalling(); // temporary fix for void kill - thanks SpartanGamezFTB ( fixme, if you leave the interior at all during this bug your tardis  is gone bro )" which i tried to put in remove but then realised that causes a loop
or just set "falling" to false meaning the tardis will be able to takeoff again
i dont really know

https://discord.com/channels/859856751070937098/859856751070937103/1187741266172194848

**Comment by Duzos** [comment]
creativious gave me coed to use as reference
