### ISSUE TITLE
Spamming on the menu button that scrolls through features causes a crash

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#410]
yep it was me suckers.

**Describe the bug**
If you go on to your tardis console monitor and find a button that can scroll through different modes (i used the permission button)
and press on it a buncha times then it crashes is what im guessing
 it was on the ait server

**Comment by Duzos** [comment]
attach crash report

**Comment by Duzos** [comment]
unless this isnt client side, then its not you its me

**Comment by MaketendoDev** [comment]
It doesn't crash the client its the server

**Comment by Duzos** [comment]
then its not ur fault

**Comment by Duzos** [comment]
#411
