### ISSUE TITLE
[IDEA] A ding sound when you receive a hypercube.

### ISSUE THREAD

**Issue by BredDino** [amblelabs/ait#414]
**Is your feature request related to a problem? Please describe.**
It's a bit hard to notice it when you receive a hypercube as you don't always look at the door and might not notice it.

**Describe the solution you'd like**
I'd like you to add a nice notification sound.

**Additional context**
I want to make a texture pack to change the sound to the "you got mail" sound.

**Comment by Duzos** [comment]
there should already be a ding sound that plays at the door iirc
