### ISSUE TITLE
Too many ways to set waypoints 

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#416]
https://github.com/user-attachments/assets/ad39247f-910c-44a6-a1a4-08776fcc945b
AIT Version: dev build #736 [ait-1.0.6.736-1.20.1-beta]

**Comment by Duzos** [comment]
lol what does this mean

**Comment by Joggester** [comment]
According to the wiki, there is only one way to set a waypoint, but there are many ways to set a waypoint in the game

**Comment by Duzos** [comment]
ohh
wiki will become updated soon
