### ISSUE TITLE
Cloisters Playing on every player. Doubling the noise.

### ISSUE THREAD

**Issue by AuroraNyxs** [amblelabs/ait#419]
**Describe the bug**
It doubles the noise with each player in the interior

**To Reproduce**
1. Go into interior with multiple people
2. Crash or set alarms on.
3. See issue

**Expected behavior**
A single cloister sound

**AIT Version:**
dev build #738 [ait-1.1.0.738-1.20.1-beta]

**Comment by Loqor** [comment]
@Duzos is this still an issue? I unfortunately can't test.

**Comment by Loqor** [comment]
Any idea on how to fix? it seems like it should just play a single time at a single position not at every single player's position

**Comment by MaketendoDev** [comment]
Yea or just make it play on client side

**Comment by Duzos** [comment]
it already plays client side

**Comment by Duzos** [comment]
can someone test to see if this issue still exists

**Comment by Duzos** [comment]
Line `114` in `TardisCrashHandler reads
`serverPlayerEntity.playSound(AITSounds.CLOISTER, 1f, 1f);`
this is why it plays twice for every player
removing..
