### ISSUE TITLE
Notification on Interior Change are not displayed

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#421]
A TARDIS built from TARDIS Coral must be flown once before the notification on interior change will appear.
However, a TARDIS taken from the creative inventory will never display the notification on interior change.

AIT Version:
ait-1.1.0.740-1.20.1-beta

**Comment by Joggester** [comment]
Yes, I have

**Comment by Duzos** [comment]
fucks sake

**Comment by Duzos** [comment]
what item and how’d you link it

**Comment by Joggester** [comment]
I have tried all the items that can be linked.

**Comment by Duzos** [comment]
life is pain
i’ll check it out

**Comment by Joggester** [comment]
The planted TARDIS will only display Notification on Interior Change after it has flown once.

**Comment by Joggester** [comment]
I tried again and this time it worked after linking the key

**Comment by Duzos** [comment]
so it was a one off? can you reproduce it?

**Comment by Joggester** [comment]
I tried again and this time it worked after linking the key

**Comment by Duzos** [comment]
then for now..

**Comment by Joggester** [comment]
So it's intentional that the prompt won't show up if the item isn't linked, right?

**Comment by Duzos** [comment]
yes
