### ISSUE TITLE
Add more text to lang

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#424]
-Monitor
-Controls
-Security
-Flight Events
-Notification on unlocked something
-Achievement
-CREATIVE ONLY SKELETON KEY
-Sonic Settings
-Sonic Modes
-Land Type Control
-Rotation Direction
-"Position"
-Some text in Smithing Template
-TARDIS Loyalty
![未标题-2](https://github.com/user-attachments/assets/ccf2e621-9425-4581-b52c-dbbcc7001289)

**Comment by MaketendoDev** [comment]
Most of the broken lang is now fixed in the latest version are you also suggesting more lang types too?

**Comment by Duzos** [comment]
some things are still literal and not translatable

**Comment by MaketendoDev** [comment]
ya

**Comment by Joggester** [comment]
hope these texts can be added to lang soon

**Comment by Duzos** [comment]
@MaketendoDev did you complete this

**Comment by MaketendoDev** [comment]
yep

**Comment by MaketendoDev** [comment]
although i don't think advancements can be translated

**Comment by MaketendoDev** [comment]
i'm not sure tho

**Comment by Joggester** [comment]
wait what?

**Comment by Joggester** [comment]
Sonic Modes and controls can't be translated?

**Comment by MaketendoDev** [comment]
will come soon ™

**Comment by MaketendoDev** [comment]
![image](https://github.com/user-attachments/assets/f486b499-33b9-4b7f-b68a-dd029a43fb22)

**Comment by Addi3** [comment]
keep it
