### ISSUE TITLE
TardisRef null Exterior Collision

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#425]
Beta server crash
Just add a null check and worry about the rest for 1.2.0

java.lang.NullPointerException: Cannot invoke "loqor.ait.api.link.v2.TardisRef.isEmpty()" because "ref" is null
    at loqor.ait.core.blockentities.ExteriorBlockEntity.onEntityCollision(ExteriorBlockEntity.java:146)
    at loqor.ait.core.blocks.ExteriorBlock.method_9548(ExteriorBlock.java:332)
    at

**Comment by Duzos** [comment]
["I accidentally replaced a fortress with exterior blocks"](https://discord.com/channels/1213989169878274068/1214758186066772008/1300096834169208863) - Jelly
nice.
add the check anyways, tis not hard.

**Comment by Duzos** [comment]
in `ExteriorBlockEntity.onEntityCollision`
