### ISSUE TITLE
'Exile' Prime exterior variant 

### ISSUE THREAD

**Issue by TheMilkSnatcher** [amblelabs/ait#427]
'Exile' Hartnell exterior variant 
![classic_exile](https://github.com/user-attachments/assets/017e3d22-420c-4639-b2b5-dcb5bb376222)

**Comment by TheMilkSnatcher** [comment]
Also I think we should add this asap since it lwk looks a tad bit off currently

**Comment by Duzos** [comment]
yeah okay
