### ISSUE TITLE
Update gilded booth exterior

### ISSUE THREAD

**Issue by Ouroboros-Games** [amblelabs/ait#430]
I fixed issues with my gilded booth exterior texture shortly after 1.0.5 released and i'm just asking if the texture could be swapped out for the new one
![booth_gilded_emission](https://github.com/user-attachments/assets/e7844246-e38e-42a0-8008-36d67f73a410)
![booth_gilded](https://github.com/user-attachments/assets/65aca34a-1d2d-484c-ac09-8224cfd3de50)

**Comment by Duzos** [comment]
what were the issues

**Comment by miner100910** [comment]
The window pattern seemed too basic to me, and some of the texture was coloured incorrectly and was still using the colours of one of the default booth variants

**Comment by miner100910** [comment]
The gold on the current texture is also different from the gilded console and geometric exterior as they're more up-to-date and their gold is dithered
