### ISSUE TITLE
Hitting the console with a hammer while the TARDIS is in flight will not reduce loyalty

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#431]
I've tried it many times, and no matter how far I fly or how many times I hit it with my hammer, the TARDIS's loyalty never decreases.

AIT Version:
ait-1.1.0.741-1.20.1-beta

**Comment by Duzos** [comment]
loqor can sort this idk how hammer or loyalty works

**Comment by Joggester** [comment]
so?

**Comment by Duzos** [comment]
cant repro
