### ISSUE TITLE
Console Positon Exploding when crashing

### ISSUE THREAD

**Issue by AuroraNyxs** [amblelabs/ait#434]
**Describe the bug**
The specific position where a console is located or WAS located explodes when crashing from the explosion damage issue
It is sometimes hard to replicate but it does happen

**To Reproduce**
1. Place a console, remove it with the normal cache or world edit it away.
2. Start up flight and do a Critical Crash, (this being a powered down interior)
3. See damage from issue

**Expected behavior**
It shouldent be exploding anything in the tardis interior, only producing knockback damage

**AIT Version:**
dev build #740 [ait-1.1.0.740-1.20.1-beta]

**Comment by Duzos** [comment]
this is a larger issue of positions not being removed correctly, but thats a later down the line problem
