### ISSUE TITLE
New 'Interior settings' Gui 

### ISSUE THREAD

**Issue by TheMilkSnatcher** [amblelabs/ait#439]
'Interior settings' Gui for 1.1.0 since it still uses the old one
(also make sure to have like gallifreyan after the command line entry lol)

![retxt AiT monitor OTHER THINGY](https://github.com/user-attachments/assets/5ed8c9de-1e12-4ac3-b6f1-6223e52159e3)

**Comment by Duzos** [comment]
no new features/enhancements for 1.1.0, only fixes

**Comment by Duzos** [comment]
@MaketendoDev

**Comment by MaketendoDev** [comment]
yep i'm using this alr

**Comment by Duzos** [comment]
alr
check ur email i invited u to this repo

**Comment by MaketendoDev** [comment]
kk
