### ISSUE TITLE
Engine is just straight up stupid.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#443]
The engine core is just dumb. It needs a different model (I'm willing to settle on a block with just a texture and some emission since Tright's back) and a different way to get it back after interior changing. I'm thinking just make it deprecated until 1.2.0.

**Comment by Loqor** [comment]
@Duzos what do you think

**Comment by Addi3** [comment]
this is a personal opinion but i liked this one , what happened to it?
![image](https://github.com/user-attachments/assets/1341bf27-7e4a-44e0-9da4-c0984e37ecb5)

**Comment by Loqor** [comment]
NTM dupe ahh engine (i also hated it)

**Comment by Addi3** [comment]
fair enough

**Comment by Duzos** [comment]
don't bother making it deprecated, we can fully implement it and do changes in 1.2.0, we can't risk more bugs so close to release.

**Comment by Loqor** [comment]
Gotcha, there should be a better way to give the engine core back after the interior change because it dropping is bad.

**Comment by Duzos** [comment]
leave it to 1.2.0 or a 1.1.* patch
we fixes only right now

**Comment by Duzos** [comment]
once you have all your ideas, split this up into multiple issues OR make a todo list on this issue

**Comment by Duzos** [comment]
replaced with milestone
