### ISSUE TITLE
Stallion exterior 'Steel' variant REMAKE, new 'Pristine' & 'Green' variant

### ISSUE THREAD

**Issue by TheMilkSnatcher** [amblelabs/ait#446]
![stallion_steel](https://github.com/user-attachments/assets/07513353-f858-45ba-bf73-a5aa8a744b49)
![stallion_pristine](https://github.com/user-attachments/assets/e09f2ba7-5455-428b-8e1a-3f53e8948588)
![stallion_green](https://github.com/user-attachments/assets/73453a08-fc37-472a-8139-7348b7fa7e39)
![stallion_steel_emission](https://github.com/user-attachments/assets/fcf068c0-2adf-46ef-a80b-387536024ae1)
![stallion_pristine_emission](https://github.com/user-attachments/assets/2c0972f0-4095-4d84-bdd2-593ae9be4b6e)
![stallion_green_emission](https://github.com/user-attachments/assets/fc34321b-a683-4cd1-9d01-e1fe2d0fe814)

included the emission textures if they use em lol
(might need a new name for 'Green' since its a bit boring, also for 1.1.0)

**Comment by Duzos** [comment]
for 1.2.0

**Comment by TheMilkSnatcher** [comment]
at least add the new steel remake for 1.1.0 😭

**Comment by Duzos** [comment]
no

**Comment by TheMilkSnatcher** [comment]
![image](https://github.com/user-attachments/assets/adc7f291-b20e-4ac5-98d3-d3c44de3367d)
![image](https://github.com/user-attachments/assets/9a2a8c9b-c3f7-47af-b519-1313ef4f5d86)
the remake applies this fix since it doesnt make sense
