### ISSUE TITLE
Title Screen Text + Panorama

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#447]
Stills reads as 1.0.5

**Comment by MaketendoDev** [comment]
Fixin this rn

**Comment by Duzos** [comment]
while youre at it change the paronama

**Comment by MaketendoDev** [comment]
alr any suggestions on what to?

**Comment by Duzos** [comment]
also change "aitlogo.png" in the assets folder

**Comment by Duzos** [comment]
change it to whichever interior is ur fav

**Comment by MaketendoDev** [comment]
*Chooses the Dev Interior*
