### ISSUE TITLE
TARDIS ground searching is buggy 

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#449]
It goes inside blocks, doesn't search properly, and the list just goes on.

**Comment by Loqor** [comment]
im debating whether or not to solve this now or wait for 1.2.0

**Comment by Duzos** [comment]
leave it for theo to fix in 1.2.0

**Comment by Loqor** [comment]
![2024-11-01_22 36 23](https://github.com/user-attachments/assets/a84504b0-d4f9-4d64-bf7a-7e6481a5fe5f)

**Comment by Duzos** [comment]
dupe
