### ISSUE TITLE
waiter waiter! another tokamak variant please! (73 Yard variant of Tokamak Police Box)

### ISSUE THREAD

**Issue by TheMilkSnatcher** [amblelabs/ait#457]
![police_box_glyngatwg](https://github.com/user-attachments/assets/90837585-353f-4418-a301-ee2ef6cf58c1)|
![police_box_glyngatwg_emission](https://github.com/user-attachments/assets/2f496db2-f6a6-406a-a54f-70e8a5d0df13)

**Comment by Addi3** [comment]
omg its done, yes pls add this
