### ISSUE TITLE
Console Model resets on Client when broken

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#46]
title
basically when the block gets broken its the right type on server but on client the  type gets reset back to the default one
options are probably:
- find some way for the server to resync to the client when the block gets broken, but not immediately after as the client takes time to update ( block entity will be null if synced too soon )
- create an ASK packet the client can send to the server which then makes the server resync clients

**Comment by Creativious** [comment]
@Duzos Why is this reopened?
