### ISSUE TITLE
seeing strange squares on my screen when looking at immersive tardis door 

### ISSUE THREAD

**Issue by evabay1** [amblelabs/ait#465]
when i look at the tardis door with immersive i see

**To Reproduce**
1. I look at the tardis portal from either inside or outside
2. See error

**Screenshots**
![image](https://github.com/user-attachments/assets/ec5dd87d-b539-4190-a39b-f22d55197a96)
ith.

**AIT Version:**
1.1.0

**Additional context**
the squares have a strong similiarity to the journymap squares used to represent chunks

**Comment by Duzos** [comment]
if you make an immersive portal does this happen?

**Comment by TheMilkSnatcher** [comment]
also i think this might be an issue with the minimap mod you're using
since the squares look similar to the grid pattern of it

**Comment by Loqor** [comment]
yeah its the minimap mod

**Comment by Duzos** [comment]
bring this up with the minimap mod or immersive portals

**Comment by TheMilkSnatcher** [comment]
also what mod is this so we can see this for ourselves (and maybe provide some logs about it too)
