### ISSUE TITLE
TARDIS siege texture inconsistency

### ISSUE THREAD

**Issue by Ouroboros-Games** [amblelabs/ait#476]
**Describe the bug**
The siege mode TARDIS exterior's newer, less blue texture is only used for the in-world block, the item form still uses the blue texture

**To Reproduce**
1. Put a TARDIS into siege mode
2. Pick up TARDIS
3. Texture changes from the newer texture to the old blue one

**Expected behavior**
Both textures should be the new gray siege mode

**Screenshots**
N/A

**AIT Version:**
1.1.0

**Additional context**
N/A

**Comment by miner100910** [comment]
I'll get some now

**Comment by miner100910** [comment]
![2024-10-31_02 24 47](https://github.com/user-attachments/assets/3002e87c-45bf-4322-a53e-57affe1023ec)
![2024-10-31_02 25 38](https://github.com/user-attachments/assets/404c92b5-71a0-46d5-8c04-018188e2595b)
![2024-10-31_02 25 42](https://github.com/user-attachments/assets/4149a673-06ee-4d80-9f5f-18cfb0d14aee)
First screenshot is the block, second is first person and in hotbar/inventory, and third is third person in hand
