### ISSUE TITLE
Artron collector uses too much zeiton clusters and only gives out one

### ISSUE THREAD

**Issue by Dispnser** [amblelabs/ait#479]
**Describe the bug**
artron collector will "eat" other zeiton clusters in the stack

**To Reproduce**
1. Go to a rift chunk and place down an artron collector
2. Right click on the artron collector with a stack of zeiton clusters

**Expected behavior**
Only one zeiton cluster should be used and others stored in another inventory slot(or dropped to the ground if not enough inv space)

**AIT Version:**
1.1.0

**Additional context**
I would like to get my 3 zeiton clusters back on the server :P

**Comment by Duzos** [comment]
addie or jelly give the man his dusters
