### ISSUE TITLE
Camera Shake

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#48]
title
cwaig said "just edit their view on the client innit"
i took that as mixin to gamerenderer ( or similar ) and was starting to do that then decided "maybe i should just search in the fabric dev server" and saw ppl saying this
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/ca6f605a-43c6-4088-a6ee-34aa8cc328bb)
and that sounds better than a mixin because i ahte mixins so ill just send a packet to the client telling them to shake their screen by adjusting the x and y rot of their camera or smth like that idk

thisll be used somewhere probabbly camera shake is cool

**Comment by Duzos** [comment]
did more reading andthat seems baout right as what other people are doing

**Comment by Duzos** [comment]
you spin me right round baby right round like a record baby round round round round
just realised its probably a bad idea to you know send a packet every tick
ill just make a start and stop packet?
or make it have a duration???
ill do start/stop for now
https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/7320f123-c621-4835-b9e9-d4b0b151d567

**Comment by Duzos** [comment]
ohh its only going in one direction because im only adding to the pitch/yaw
ill make it so it add or removes based off a random boolean

**Comment by Duzos** [comment]
or maybe i do no packets 
the client already has access to all the info needeeeddddddddddd
hmmmmmmmm

**Comment by Duzos** [comment]
ill do no packets and if it needs to be better ill change it
