### ISSUE TITLE
When a TARDIS gets bugged hard and gets removed, it spams "failed to load <uuid>!" over and over in server console.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#481]
![image](https://github.com/user-attachments/assets/da102c51-786b-4d37-b4c2-e3b550cf4b0f)

**Comment by Loqor** [comment]
it occurs within loadTardis() where there's a try/catch statement, something is fucking up where the object isnt being loaded properly

**Comment by DrTheodor** [comment]
That could happen in 2 cases:
1. The tardis fails to successfully load or created.
2. The tardis is removed but stuff that's linked doesn't get unlinked.

I have some ideas on how to fix it, I've sent some ideas in the dev chat.

**Comment by Loqor** [comment]
Exterior block wasn't loaded when removed.

**Comment by Duzos** [comment]
also seems related to #533 
if server freezes and you kill it, any tardises from last save to now get bugged
as they exist on disk but not in the world

**Comment by Duzos** [comment]
bump

**Comment by Duzos** [comment]
this is just a consequence of another bug, so find the bug causing this and make an issue about that
