### ISSUE TITLE
WARNING: FUNDAMENTAL NETWORKING FLAW

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#482]
![image](https://github.com/user-attachments/assets/ec7bba19-06b7-4462-a3cc-325c1be85345)

**Comment by DrTheodor** [comment]
I wouldnt call it fundamental. It really just looks like the siege component doesn't check if it's running serverside before attempting to get the world instance.

**Comment by Loqor** [comment]
Should be fixed.
