### ISSUE TITLE
Sent to Overworld when loading into TARDIS Interior | Multidim Bug

### ISSUE THREAD

**Issue by Sparta1121** [amblelabs/ait#485]
**Describe the bug**
When you join a server/singleplayer world, there is a more then likely chance if you join while inside an interior/tardis dimension you get teleported to the middle of nowhere.

**To Reproduce**
1. Enter any tardis
2. leave the game/shutdown server
3. rejoin the game
4. upon joining you are in the middle of nowhere

**Expected behavior**
You get teleported always to the same location, its never random.

**Screenshots**
Cant provide any at this time

**AIT Version:**
1.1.0

**Additional context**
Playing with the regular server mods, like Xaero's minimap/world map
JEI
Simple Voice Chat

**Comment by Duzos** [comment]
this is because `Multidim` kicks everyone out of closing dimensions

**Comment by MaketendoDev** [comment]
It sometimes mostly happen when the world closes without saving before exiting (like crashes)

**Comment by Duzos** [comment]
its inconsistent

**Comment by Addi3** [comment]
happens like 40% of the time

**Comment by Duzos** [comment]
happens when the player loads before the tardis interior

**Comment by Duzos** [comment]
this next commit doesnt fix it

**Comment by Duzos** [comment]
@DrTheodor

**Comment by Duzos** [comment]
yup

**Comment by Duzos** [comment]
now it happens consistently if youre in the interior of the tardis and rejoin a world
im considering 
- add a `forceLoad` tag to WorldBuilder to decide whether to save and load this dimension
- add a custom `MultiDimWorld` ( maybe )
- storing all the dims into a .json on server close
- mixin to when the server is loading overworld etc and force our dimensions to be loaded

on a PR soon
@DrTheodor  thoughts?

**Comment by DrTheodor** [comment]
> - mixin to when the server is loading overworld etc and force our dimensions to be loaded

Huh
I thought we already do that with an event

**Comment by Duzos** [comment]
```
    static {
        ServerTickEvents.START_SERVER_TICK.register(server -> MultiDim.get(server).tick());
        // ServerPlayConnectionEvents.INIT.register((handler, server) -> MultiDim.get(server).load(handler.getPlayer().getServerWorld()));
    }
```

not from what i can see 
the worlds are loaded when needed, which doesnt load them fast enough if there was a player inside 
maybe we could track if there was a player inside before shutdown instead and force load based off that
or find some way to load at the very start of the players connection, but that would prolly be a race
