### ISSUE TITLE
exterior textures are missing / wrong - ait-1.2.0.812-1.20.1-beta-datapack_sfx

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#486]
![image](https://github.com/user-attachments/assets/3292a241-854c-4b33-9f81-846961b57896)
![image](https://github.com/user-attachments/assets/a60f2dd1-b558-48d6-9d85-1e3b60d6a458)
![image](https://github.com/user-attachments/assets/2541eb5c-1a8a-4bd2-8d56-aae973592842)

**Comment by Addi3** [comment]
it fixed when i changed the exterior

**Comment by Duzos** [comment]
strange stuff

**Comment by Duzos** [comment]
i think i incorrectly did the datapacks for the stallion ones tbh

**Comment by Duzos** [comment]
files are corrupted

**Comment by Addi3** [comment]
oof

**Comment by Duzos** [comment]
ill redownload them later

**Comment by Duzos** [comment]
this also exists on main
