### ISSUE TITLE
exterior hitbox rotates

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#487]
when demating / remating the exterior hitbox faces north - ait-1.2.0.812-1.20.1-beta-datapack_sfx

![image](https://github.com/user-attachments/assets/311f6705-9164-48a5-aefc-6c53dcd019b8)

![image](https://github.com/user-attachments/assets/ab65e6a4-2936-4b05-b5e4-cda26d0a86a1)

**Comment by Duzos** [comment]
cant repro
