### ISSUE TITLE
"/ait siege" execution error

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#492]
**Describe the bug**
both "/ait siege <TARDIS> true" and "/ait siege <TARDIS> false" put the TARDIS into siege mode

**AIT Version:**
1.1.0

**Comment by Duzos** [comment]
![image](https://github.com/user-attachments/assets/3b9d73d7-8218-4894-859a-23055f14fd4e)
lol ur right

**Comment by MaketendoDev** [comment]
kk
