### ISSUE TITLE
Unable to obtain the "Enter the TARDIS for the first time" achievement

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#493]
**Describe the bug**
When I entered the TARDIS, I didn't get the "Enter the TARDIS for the first time" achievement like usual

**AIT Version:**
1.1.0

**Comment by Joggester** [comment]
Is it because the TARDIS dimensions are all independent?

**Comment by Duzos** [comment]
entered how

**Comment by Joggester** [comment]
Just walk into the tardis

**Comment by Duzos** [comment]
i see

**Comment by Joggester** [comment]
My bad, I modified the achievement file for translation, but it was overwritten without modification since 1.0.5.
