### ISSUE TITLE
[IDEA] Ghost Monument Return

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#494]
**Is your feature request related to a problem? Please describe.**
Ghost Monument Easter Egg/Feature back in the mod please

**Describe the solution you'd like**
Because it was fun to have aswell as was a super cool feature/easter egg to have, and it was in the mod before.

**Comment by Duzos** [comment]
it's still in the mod, it's even in the config
you're probably doing it wrong and icr how it's done
