### ISSUE TITLE
[IDEA] Disengaging Siege Mode

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#495]
When the player goes into Siege Mode [Protocol 1913], i think they should have to disengage it first before operating any other controls and not just resort to turning on the power again. With most/all protocols, usually in order to access other things, sometimes they have to be engaged or disengaged to use them.

**Comment by Duzos** [comment]
turning on the power already requires you to disable siege mode
wdym?

**Comment by SpartanGamezFTB** [comment]
wait it does? cause ive still seen where u can just click the power control to disengage siege mode

**Comment by SpartanGamezFTB** [comment]
nvm i was stupid, a buddy clicked the siege mode to disable it and i turned on the power and mustve dosed off. Apologies
