### ISSUE TITLE
[BUG] Same Location TARDIS Landings cause an exterior to become invisible  

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#496]
**Describe the bug**
When trying to land within another tardis interior by "parking" in the same exact location as another tardis with shields off. The tardis exterior disappears.

**To Reproduce**
Place 2 Tardises down, get coordinates of 1 tardis and put them into the other to travel to the same exact location. Travel to those coordinates while the other tardis has shields disengaged, and land. The exterior of the other tardis that you were trying to land in the same exact spot has now disappeared. However the tardis still exists. To fix simply demat the "invisible" tardis and remat at another location.  (use teleport command if outside the exterior invisible one)

**Video**
https://streamable.com/1y2fwh

**AIT Version:**
1.1.0 Release

**Comment by Duzos** [comment]
probably still exists tbf

**Comment by Duzos** [comment]
cant repro
