### ISSUE TITLE
message.ait.artron_units text and screen.ait.monitor.on|off text is broken

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#498]
![2024-11-02_04 42 23](https://github.com/user-attachments/assets/d50acb85-6cf2-4784-bb8d-0ab4c3abc0fa)
![2024-11-02_04 45 33](https://github.com/user-attachments/assets/7eae1ba4-28ed-464c-ae53-7e7a75d8c834)

**AIT Version:**
ait-1.2.0.821-1.20.1-beta

**Comment by MaketendoDev** [comment]
shoot sorry! I forgot to check out these ones while testing for adding your suggestion this will get this fixed soon.
