### ISSUE TITLE
Loyalty can be bought with XP 

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#499]
does what it says on the tin

basically loyalty do be hard to gain, what if you could expend some xp to gain a point or two?

**Comment by Duzos** [comment]
how about instead
tardis has a list of items its likes
in return for that item and some xp, you gain some loyalty when right clicked with on telepathic circuit
liked items are decided on creation
liked items are stored in a registry, with an xp cost and a loyalty gain count
and also datapack definable for the hell of it

**Comment by Loqor** [comment]
@Duzos sure why not sounds peak
