### ISSUE TITLE
Sonic scan mode stopped showing TARDIS controls

### ISSUE THREAD

**Issue by wolf2070** [amblelabs/ait#500]
Description:
Sonic screwdriver's scanning mode bugs and randomly shows the number fifteen when looking at the console, but doesn't show any controls when hovering over them.

![2024-11-02_00 44 03](https://github.com/user-attachments/assets/9f728be4-4cd9-41c1-aae7-1fe5ce982b4c)

To Reproduce:
Honestly no clue, unfortunately I was not paying attention.

Playing on the server, so AIT version is 1.1.0.1167

**Comment by Joggester** [comment]
Did you add caxton?

**Comment by wolf2070** [comment]
It just sorta, started working again when I joined today? I don't know if I should close this issue or not.

**Comment by Duzos** [comment]
the "15" is the redstone power of the block
