### ISSUE TITLE
Copper Console

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#511]
Texture/Model needs finishing
~~if you are good at modelling, reply to this thread or dm poozo on discord~~
*worked on by `we stan krang`*

**Comment by MaketendoDev** [comment]
Model is finished it just needs animation and implementation

**Comment by Duzos** [comment]
its not finished theres two whole empty panels

**Comment by Duzos** [comment]
we're waiting on brettski to send it over

**Comment by MaketendoDev** [comment]
aight

**Comment by Loqor** [comment]
Copper is complete
