### ISSUE TITLE
Zeiton dust and Apple skin mod display issues

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#512]
**Describe the bug**
Installing the "Apple skin" mod will show that using zeiton dust will give the player the hunger effect, but it actually does not.

**Screenshots**
![2024-11-03_03 19 40](https://github.com/user-attachments/assets/ca91cf14-1435-4627-9d9f-fe0073e5a0cf)

**AIT Version:**
1.1.0

**Apple skin Version:**
appleskin-fabric-mc1.20.1-2.5.1

**Comment by Loqor** [comment]
not something we can fix
