### ISSUE TITLE
Datapack Exteriror Emission becomes optional

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#515]

**Comment by Addi3** [comment]
it is, just dont add ' "emission": "texturepath" '

**Comment by Duzos** [comment]
no that causes the parser to fail
![image](https://github.com/user-attachments/assets/4bd80a62-8c60-4b08-92cc-3e2f8220d5bc)

**Comment by Duzos** [comment]
which means ur exterior no no loaded
