### ISSUE TITLE
Tardis is stuck on lowest speed

### ISSUE THREAD

**Issue by Profsemio** [amblelabs/ait#519]
I was flying my tardis and I accidently changed the tardis speed with commands to 50000 (Becouse I thought it was the fuel command, I didnt look good enough). And when I turned it to 7 again it stopped going faster than the slowest speed. What I mean is the speed lever will just be stuck on 1 speed and it wont go faster.

The version of AIT is 1.0.5

I wasnt playing any other mod than the Adventures in time mod

**Comment by Duzos** [comment]
did you enable autopilot (Protocol 19)

**Comment by Duzos** [comment]
also, 1.1.0 is out. u should update

**Comment by Profsemio** [comment]
No I didnt think i enabled it. I will check and let you know tho. And I updated it today but it still didnt work. I will check for the protocol tho

**Comment by Profsemio** [comment]
I checked now and No i did not enable protocol 19 and also That is not autopilot but the protocol to let players with a certain loyalty level or tardis key not being able to interact with the console. Just so you know

**Comment by Profsemio** [comment]
Yeah Thx That worked!
