### ISSUE TITLE
Remove Control Animations Config Option

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#520]
Honestly, it's pretty funny

https://streamable.com/alhdqb

AIT Version：
ait-1.2.0.838-1.20.1-beta

**Comment by Duzos** [comment]
OH

**Comment by MaketendoDev** [comment]
![image](https://github.com/user-attachments/assets/03aea001-19c4-419e-b962-30904ffb7b8e)

**Comment by Duzos** [comment]
i reckon just remove the option
its quite old
