### ISSUE TITLE
is this suppose to happen

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#521]
In - 1.1.0.1167-1.20.1-release it either sets the throttle to max or min no matter what (i have 100 loyalty btw)

https://streamable.com/rttzu4

**Comment by Duzos** [comment]
no its not fr

**Comment by Duzos** [comment]
check your speed and maxspeed using the data command

**Comment by Addi3** [comment]
it was 1, that could be why

**Comment by Duzos** [comment]
yes thats why
