### ISSUE TITLE
Use blocks to disguise your TARDIS

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#524]
-Just like the mod "Moving Elevators", when exteior is "adaptive", you can change the appearance of the TARDIS with blocks in your main hand. Since the TARDIS is two blocks high, you can use blocks to change the top and bottom halves of the TARDIS separately.

-And Then, make the "adaptive" to a control on the console instead of exterior, and if you want adaptive, change it to capsule exterior.

be like:
https://streamable.com/5afpns

**Comment by MaketendoDev** [comment]
maybe you could do this by right clicking the block in the telepathic circuits

**Comment by Joggester** [comment]
Wait, does that mean this feature has been available for a long time？

**Comment by Duzos** [comment]
cool idea
but no
