### ISSUE TITLE
When i leave the game and join again i spawn in the bottom of a cave everytime and if idk where my tardis is i lose it

### ISSUE THREAD

**Issue by M4Akula** [amblelabs/ait#525]
When I leave the game world I end up spawing in the same spot in a cave I have everything that I had before leaving but I end up losing the tardis and can't find it again I wouldn't care so much if only I could find the tardis.
I would expect to spawn where I left off before I left the game.

**Comment by Duzos** [comment]
#485 dupe

**Comment by M4Akula** [comment]
> #485 dupe

What??
