### ISSUE TITLE
[IDEA] Make an object thag you hold that will give you quordinates of the tardis

### ISSUE THREAD

**Issue by M4Akula** [amblelabs/ait#526]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MaketendoDev** [comment]
You're sonic already tells you your TARDIS coordinates in it's tooltip when it has been linked to it

**Comment by M4Akula** [comment]
> Your sonic already tells you your TARDIS coordinates in it's tooltip when it has been linked to it

Sorrt how do u see this

**Comment by MaketendoDev** [comment]
when you hover over the sonic in your inventory
