### ISSUE TITLE
When i try to teleport the tardis too me with the sonic screw driver it will either not happen or the tardis will disapear then not spawn where i asked it too and how do you use the stattenhein remote?

### ISSUE THREAD

**Issue by M4Akula** [amblelabs/ait#527]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**AIT Version:**
Provide the version of AIT this is on

**Additional context**
Add any other context about the problem here -  eg other mods you were playing with.

**Comment by Addi3** [comment]
well summoning a tardis requires loyalty, the landing type also effects where it will land, i belive. and to use the stattenheim remote, you link it with the telepathic circuits and click where you want the tardis to land (with the item in hand)
