### ISSUE TITLE
[BUG] Copper Console Control 116 

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#529]
When engaging 116 with the sexy Copper console the model control isnt connected to the console anymore

Picture:
**Engaged**
![image](https://github.com/user-attachments/assets/d404a02e-2e4a-4418-9453-81bab8e163e7)

**Disengaged**
![image](https://github.com/user-attachments/assets/1733756a-24e4-45d4-afd0-2761039545c5)

**Comment by MaketendoDev** [comment]
fixed
