### ISSUE TITLE
Console Switching Issue

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#53]
So using a command block switches the console type, whenever i switched it to the default console from hartnel and left the TARDIS, as I walked backed inside it switched back to hartnel. I've attached a streamable link to help show the issue, if not already addressed

https://streamable.com/uk0gru

**Comment by Duzos** [comment]
oh weird i never got that issue
ill look into it

**Comment by SpartanGamezFTB** [comment]
now the bug seems to have disappeared? cause the console isnt switching anymore....

**Comment by SpartanGamezFTB** [comment]
the bug was gone, but nvm its still there lol, didnt mean to delete that message

> oh weird i never got that issue ill look into it

**Comment by Duzos** [comment]
so you getting this bug or nah

**Comment by SpartanGamezFTB** [comment]
yes, looks like when i think its gone its still there...i just did a flight with hartnell console and it went back to default console

**Comment by Duzos** [comment]
ok
something something not saving the console type correctly

**Comment by Creativious** [comment]
@Loqor fixed it, it'll be fixed whenever he commits next
