### ISSUE TITLE
New Interior Settings has broken buttons

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#530]
![2024-11-06_19 39 39](https://github.com/user-attachments/assets/00a8f0cf-76f6-441e-9046-491c5ab6c8ee)

AIT Version:
ait-1.2.0.850-1.20.1-beta

**Comment by Duzos** [comment]
@MaketendoDev

**Comment by Loqor** [comment]
@MaketendoDev is this fixed yet
