### ISSUE TITLE
Interior teleport is cooked during generation

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#531]
When generating a new interior it just teleports you to a random position in the TARDIS and not the door. Not a clue why but it does. Regenerating the interior fixes it, but for some bizarre reason it just started happening recently.
@Duzos @DrTheodor

**Comment by Loqor** [comment]
Fixed:
![image](https://github.com/user-attachments/assets/1dae4984-aa8e-435a-84af-48d156c95e0a)

**Comment by Duzos** [comment]
i uncommented it for testing as it was crashing someones game

**Comment by DrTheodor** [comment]
i wanted to rewrite multidim anyway
