### ISSUE TITLE
DefaultTheme Tokamak + Crystalline Interior freezes game

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#533]
place it down
if you dont enter the tardis nothing happens
if you do, doors dont open and the interior is blank + server freeze

**Comment by DrTheodor** [comment]
Cool stuff

**Comment by Loqor** [comment]
this is due to the world.tick() its fixed now

**Comment by Duzos** [comment]
dont lie to me lil bro i just went through this

**Comment by Loqor** [comment]
fixed by doing whatever you did i think
