### ISSUE TITLE
new_interior_settings is missing a button

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#544]
![2024-11-09_00 16 12](https://github.com/user-attachments/assets/c36e66df-e688-4ef8-a33c-b4117605c106)

**AIT Version:**
ait-1.2.0.870-1.20.1-beta

**Comment by Joggester** [comment]
Also, the lines at these two places should be connected, but they are not. Is this intentional?
![2024-11-09_00 16 12](https://github.com/user-attachments/assets/dd8a92f8-e9ae-4810-9692-7786b6803f9d)

**Comment by Duzos** [comment]
also hovering over right interior button
