### ISSUE TITLE
TARDIS texture missing

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#545]
missing list:
Bookshelf:All of them
Booth:All of them
Capsule:All of them
Moyai:All of them
Plinth:All of them
TAEDIM:All of them
Police Box:Default|Fire|Cherrywood|Coral|Futuristic|Tokamk|Soul
Renegade:Except "Rotestor"
Stallion:Except "BT"

AIT Version:
ait-1.2.0.870-1.20.1-beta

**Comment by TheMilkSnatcher** [comment]
btw what biome were they in when you made this report? we have biome textures so often when a exterior lands in a biome where they dont have the associated biome texture for, they look like they're having missing texture (which they probably are?)

**Comment by Joggester** [comment]
Plains biome

**Comment by Joggester** [comment]
I haven't played this version for a long time, and I have only played it in the super flat world.

**Comment by TheMilkSnatcher** [comment]
huh weird should of had their default texture?
iirc this is a common issue so idk

**Comment by Duzos** [comment]
from what it seems all non-datapack variants are bugged
likely because of me moving about registries 
i can fix it sunday, until then copium
