### ISSUE TITLE
[1.20.1] Incompatible with Sinytra Connector

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#546]
**Describe the bug**
I've tried many different  version combinations, but if both AiT and Connector are installed, the game crashes.
https://pastebin.com/PshdP0K9

**To Reproduce**
Install both AiT and Connector, run game

**Expected behavior**
All mods to play nicely together like kindergartners bribed with cookies

**AIT Version:**
Provide the version of AIT this is on
AiT 1.0.4
AiT 1.1.0
Forger 1.0.4
Forger 1.0.5

**Additional context**
Add any other context about the problem here -  eg other mods you were playing with.

**Comment by Matthew-MBG** [comment]
Works with 1.0.5

**Comment by MaketendoDev** [comment]
Forger 1.0.4
Forger 1.0.5
was made for being on minecraft forge as a replacement for syntria on the fabric version. If you are trying to play forge ait just use forger with the forgified fabric api

**Comment by MaketendoDev** [comment]
if you are trying to play on 1.1.0 you'll have to wait until its forger version releases

**Comment by Flexico** [comment]
> Forger 1.0.4 Forger 1.0.5 was made for being on minecraft forge as a replacement for syntria on the fabric version. If you are trying to play forge ait just use forger with the forgified fabric api
I'm playing with Forge, but I need Connector for several other Fabric mods besides AiṪ.

**Comment by Flexico** [comment]
Are you kidding me.

All this time

...

I didn't have Oωo installed.

**Comment by Duzos** [comment]
so 1.1.0 works with this?
