### ISSUE TITLE
Tardis doors refuse to open + game crashes if tardis falls 

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#547]
[latest.log](https://github.com/user-attachments/files/17692115/latest.log)

https://github.com/user-attachments/assets/07d75700-67b5-4c34-82c3-f6a5f629ae82

Teleporting to the interior also gives me a error so

**Comment by Saturnorsomthing** [comment]
Presuming its related to the interior not being "summoned"

Like when the exterior gets deleted the interior doors wont open,im presuming its the same in this case but the reverse where the interior door dosent exsist.

And it seems to specificly only happen with this variation of the TARDIS (aka the tokomak one) the rest seem to work fine

**Comment by Duzos** [comment]
dupe
