### ISSUE TITLE
Tardis Can't Grow on the moon 

### ISSUE THREAD

**Issue by trerrturyy** [amblelabs/ait#548]
**Describe the bug**
if you Grow a Tardis on the moon it crashes your game

**To Reproduce**
1. Go to the moon (AIT version)
2. find a rift chunk
3. grow a tardis until mature

**Expected behavior**
it makes a normal tardis

**AIT Version:**
No clue but its a beta version

**Comment by Addi3** [comment]
for the version just copy and paste the name of the ait jar file

**Comment by Duzos** [comment]
attach crash report

**Comment by trerrturyy** [comment]
mf i did this last week i got no fuckin crash report brah

**Comment by Addi3** [comment]
just do it again and send the latest.log

**Comment by trerrturyy** [comment]
i dont even remeber what beta i used

**Comment by Addi3** [comment]
try the latest then

**Comment by trerrturyy** [comment]
alr

**Comment by trerrturyy** [comment]
well idk but its fixed
