### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#551]
* Engine core is now renamed to "Singularity matrix subsystem"

* New obtainment methode is crafting the cage which is made mostly of obsidian and othere stuff like zeiton,you then put it in a rift chunk and shove a bunch of zeiton into it and it'll grow and explode (the zeiton in the cage),then grab the cage and then throw it into the void turning it into the singularity matrix.

* Its new usage is when first placing the coral right click it with the smb,this will put it ontop of the coral,the coral will grow onto it,slowly forming around it and then forming the shell.

* Once you reconfigure your tardis and such the smb isent required anymore as its "embeded" into the tardis.

***-Engine***

-New main blocks (bassicly must haves for the tardis to work)
* The engine
* Fluid link(s)
* Stabalizers
* Life support systems

-Subsystem block list
* Artron collection system
* Artron compression upgrade
* Demat circuit
* Shielding system
* Gravitational manipulation system
* Architectual configuartion system
* Chameleon circuit
* Action defense systems
* Protocol setup unit
* Power dampener
* Emergency power system
* Scanning unit

***-The engine***

* A must have for the tardis

* The engine will show diffrent status's

* Blue = Nothings wrong

* Cyan = Missing parts for tardis to work properly

* Yellow = An error has appeard,can be caused to due to a flight event.

* Red = Critical malfunction,a imporatant/sub system that was neccesry broke

* Green = Artron overflow,if you dont have the right artron system setup the engine may overflow,this can cause the engine to begin "leaking" artron evrywhere,and you do not want artron touching you.

* Black = Engine reciving no power/powers off

* Flashing red = Engines phasing,caused due to demat circuit not being built properly.

* If the engine begins phasing the tardis alarms will activate and the player will recive a "notification",to stop the phasing engage the handbreak and wait a good ammount of time

* EVRYTHING,has to be connected to the engine by using a fluid link(s),if it isent connected then it simply wont work.

* Note that the engines will need repair and have durability,if the durability gets low they begin smoking,if it gets to 0 the engine explodes,this wont acctualy damage your interior but a lot of your work is ought to be gone.

* Once placed coral will spread from the bottom into the engine ports and such,it'll also connect to fluid links

* Has a storage comparment where you can store spare fluid links,stuff to repair subsystems ect ect.

***Fluid link(s)***
* To link evrything back to the engine.
* Required for evry subsystem,if they dont need a setup they'll have a port somewhere,however if a setup is needed then you'll have to build smthin similar to a conduit with a port,where you then insert the correct fluid link to then link it to the engine.
* The 4 slots for the fluid links will make the one in in the "main" one,which makes any fluid link of the same category link to it.
* Not all subsystems will work with the same fluid links,since you have only 4 slots but 6 fluid links you'll sometimes need to hotswap between them,however the engine has compartments to store those said 2 fluid links and any othere stuff.

***Stabalizers***
* Pretty basic function but also neccesry,the tardis wont take off without the stabalizers due to a fail safe system
* If unlocked allows throttle speeds 3-5
* Unlocks P116 aswell.

***Life Support system***
* Makes it so you dont freeze to death inside the tardis (If the power is on)
* Will try keeping you alive in the tardis
* Falling out of the tardis tps you back up
* If a room is deleted on you you get tped to the console room

***Artron collection system***
* Just place it down and connect it to the engine with fluid links
* If you dont use a compression system a artron overload may happen.
* Loses some durability when charging in rift chunks but very slowly.

***Artron compression upgrade***
* Use this to stop artron overloads.
* Makes it so artron collection system dosent break due to rift chunks.

***Demat circuit***
* A must have to make the tardis take off
* Breaks very slowly with each flight
* Requires setup.

***Shielding system***
* Used to unlock the shields
* Breaks overtime when using the shields or if anything hits the shield.
* Requires setup.

***Gravitational manipulation system***
* Allows anti gravs to be used and RWF
* Breaks slowly when anti gravs are being used or RWF
* Requires setup.

***Architectual configuartion system***
* Used to make rooms n all
* Slowly breaks when the tardis makes rooms
* Requires setup.

***Chameleon circuit***
* Used to make the exterior change and make the tardis go invisible
* Slowly breaks when P3 is being used or the adpative exterior.

***Action defense systems***
* Unlocks HADS
* Makes the tardis react to certain threats

***Protocol setup unit***
* Literly just unlocks siege mode and hail marry ect.

***Power dampener***
* Your able to put zeiton into it,it'll turn that said zeiton into artron.
* This will also make it so your tardis refules a bit slower but will make it so you only lose .1 AU per second.
* Requires setup.

***Emergency power system***
* Unlocks a 2nd power storage unit which you can choose to switch between on the monitor.
* Double tap refuler to refuel emergency power instead.
* Can store 850 artron max
* Automaticly activates when power runs out,lights will dim and turn red
* Requires setup.

***Scanning unit***
* Unlocks scanner
* Idk what else to add

***-Durability system***
* Each block has its own durability,which slowly degrades over time,you can repair them with iron and othere things
* If a block runs out of durability it will stop working and will look broken,they will smoke and spark aswell.
* The engine is the only exeption which will explode but cause no structural damage.
* The engine will also spark smoke n all when at half durability,when at like 10% dura the alarms will turn on till fixed,if at like 1% the tardis wont want to do anything,if you still force it to the engine will kaboom
* Blocks lose durability slowly when they preform theyr function,like the demat circuit taking damage when demat/rematting.

***-Setup***
* If a subsystem was marked as "requires setup" that means it'll need a conduit type build to work.

* Note this was a old suggestion i revamped so some things might not make sense

**Comment by Duzos** [comment]
[Related Milestone](https://github.com/pavatus/ait/milestone/7)
