### ISSUE TITLE
essential error?

### ISSUE THREAD

**Issue by CohenEmerald** [amblelabs/ait#56]
was playing on essentials and when going into flight i get kicked and this error in image appears.
![image_2023-12-25_030527455](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/147286807/52799244-cc5e-4ba5-ad51-499c9348f8e2)

**Comment by Duzos** [comment]
@Loqor add a null check or smth idk
im break

**Comment by Loqor** [comment]
should be fixed hopefully-
