### ISSUE TITLE
Gravitational Manipulation Subsystem

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#566]
- Unlocks Antigravs
- Unlocks RWF (if that ever comes)
- Loses durability as Antigravs/RWF is used
- Requires #595

**Comment by Loqor** [comment]
i think we should make our own implementation of the gravity mod so we can do the fun tardis stuff

**Comment by Loqor** [comment]
not for 1.2.0 but definitely in the future

**Comment by Duzos** [comment]
yea
