### ISSUE TITLE
Spawning/Growing a TARDIS crashing game

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#58]
in the latest github version, when i spawn in a tardis or grow her, she crashes my game entirely 
[latest.log](https://github.com/M-D-Team/ait-fabric-1.20.1/files/13774147/latest.log) - Latest Crash Report
https://streamable.com/mkd15s

**Comment by Duzos** [comment]
has been fixed as of 50 mins ago

**Comment by theOneTrueFunniBoi** [comment]
I am still experiencing this issue, mod version is 1.0.4
