### ISSUE TITLE
Initial subsystem

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#581]
The new Tadis comes with an initial subsystem, which saves players the time to find a subsystem, which makes the gameplay experience even better

**Comment by Duzos** [comment]
initial subsytem? wdym?

**Comment by smallmoss233** [comment]
> 初始子系统？wdym？

Tadisis comes with its own subsystem, that is, there is no need for players to install these subsystems, Tadis comes with it

**Comment by Duzos** [comment]
this would remove the progression

**Comment by smallmoss233** [comment]
> 这将删除进度

This comes with only the ones that come with flying and refuelling, and other expansions such as shields and anti-gravity have to be installed additionally, so it's not bad
