### ISSUE TITLE
Increase Loyalty Rate

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#583]
If you are the owner of the Tadis, or have a loyalty level of 35 or more, the Tadis will increase your loyalty by a point when you stay inside the Tadis for more than a game day, otherwise you will have to wait 2 days to increase your loyalty by a point

**Comment by Duzos** [comment]
it does this already, just muuuch slower
could b increased tbf

**Comment by smallmoss233** [comment]
> 它已经这样做了，只是 muuuch 慢一点可能会增加 tbf
Then speed up the trust owner

**Comment by smallmoss233** [comment]
：）
