### ISSUE TITLE
The eye of harmony is misplaced

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#587]
I added the linkage mod that the release page said could adjust gravity, and...
![2024-11-15_12 51 23](https://github.com/user-attachments/assets/b8c8098c-6d71-4e1f-b5e3-5e75374f9956)

**Comment by MaketendoDev** [comment]
you need to replace the engine core to where you want the eye of harmony

**Comment by smallmoss233** [comment]
ok
