### ISSUE TITLE
Entertain me

### ISSUE THREAD

**Issue by Jeryn99** [amblelabs/ait#59]
So there's a Tardis, it walks into a bar of cubes, every colour is there except red 

This is because red coob is god, and he does not go to bars 

He just exist across all decent doctor who mods 

where is red coob

**Comment by Duzos** [comment]
LOOQRO REMOVED MY GOD DAMN CUBE RAHH
I WANT TO  BE DECENT!!!!

**Comment by Suff99** [comment]
red coob

**Comment by Duzos** [comment]
when

**Comment by Suff99** [comment]
when you add it you dolt

**Comment by Duzos** [comment]
Bet.

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/e29baa7c-854d-4aae-a20a-d332b5b9f262)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/b3054d84-29a4-4eea-9716-3500438f9f50)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/071d7c1b-fdd2-4c61-b97b-abe29033454f)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/af95ec6a-ccbc-4375-8fef-7f508bce50e8)
try not to cum

**Comment by Loqor** [comment]
@Suff99 where is the red coob in TR/NTM?

**Comment by Loqor** [comment]
Also we're not a doctor who mod lol we're just a tardis mod

**Comment by Duzos** [comment]
https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/70aefd48-e7a0-4f0c-aa47-e4569e2fb6c2

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/6230fd47-229e-414a-968c-a54e13c790c0)
Cube, what have you done.
