### ISSUE TITLE
tardis coral crashes game (when you can access the interior to reconfig) 🎇

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#591]
[latest.log](https://github.com/user-attachments/files/17777721/latest.log)

**Comment by MaketendoDev** [comment]
SubSystemBlockEntity.system() is null so null check?

**Comment by MaketendoDev** [comment]
java.lang.NullPointerException: Cannot invoke "loqor.ait.core.engine.SubSystem.setEnabled(boolean)" because the return value of "loqor.ait.core.engine.block.SubSystemBlockEntity.system()" is null
