### ISSUE TITLE
New blocks for the subsystem structures

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#592]
* Fluid link port
>Allows you to plug in a fluid link to provide artron to the subsystem.
>Evry subsystem structure needs this

* Mercurial link adapter (for the port)
>Makes it so you can have the "upgraded" fluid links,right click on a port to upgrade it with this item.
>Requires a blueprint.

* Zeiton infused cobble
>Cobble infused with zeiton.
>Holds up to 750 AU,your able to collect it via a artron pannel.
>Evry subsystem structure needs this.

* Compact zeiton 
>Zeiton which was bashed toghether and infused with a artron collector pannel.
>Can hold up to 2000 AU,able to collect it via artron pannel.
>Mildy expensive.
>Bassicly just a upgraded version of zeitonic cobble.

* Artron rod 
>A lightning rod modefied with a artron collector.
>Pretty cheap.
>Required for emergency power system and shield subsystem.

* Zeitonic glass
>Glass which was mixed with zeiton and a bit of artron to create a new type of glass that can withhold artron (unlike normal glass)
>Acts like glass but can hold artron making it so your zeiton type blocks last longer.
>Between cheap and expensive.
>Acts as a replacement for glass for your subsystems.

* Subsystem shell block
>Use as the outershell for your subsystem structures.
>Pretty cheap.
>Evry subsystem needs this.

* Artronic shell blocks
>Similar to the SSB but can dispurse artronic charges.
>Requires blueprint pretty expensive.

* Artron gimick for zeiton blocks

* Structures will need you to use zeiton infused cobble/compact zeiton,however the zeiton will slowly begin getting charged turning yellow entering a artronic state.

* If it stays in the "artronic" state to long it'll cause your subsystems durability to degrade faster.

* But like said just use a artron collector pannel on it and it'll revert.

* In addition once in the artronic state it'll begin emitting a redstone signal so you can just make a automated system.

* But zeitonic glass and ASB can dispruse the artron making it so the zeiton needs way longer to become "artronic".

* This happens when a subsystem has a event named "excess artron" where the subsystem bassicly releases 100-200 AU.

* Note that the structures have bassicly certain spots where a SSB/ASB need to be while the rest can be replaced with glass/zeitonic glass or any othere non flamable block.

**Comment by Duzos** [comment]
first two need more info
what upgrades?
rest are being split into own issues
