### ISSUE TITLE
Demat circuit structure

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#593]
* Use shell blocks to make a conduit setup.

* Place demat circuit in the middel like a conduit

* Replace each shell block thats facing the demat circuit with a cobble infused zeiton or compressed zeiton.

* Fill it with water and then close it up so it would look like a box (any block that isent flammable can be used)

* Then simply replace any shell block with a port.

* If done correctly the demat circuit begins spinning (will spin faster in flight)

**Comment by Duzos** [comment]
wont be closed by pr, waiting on the blocks to be added to finish up
