### ISSUE TITLE
Zeiton Infused Cobble

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#597]
- is worth 750AU
- requires texture ( @Westankrang )
- right click stone with zeiton shard to convert cobble
- cobble + shard in crafting table

**Comment by TheMilkSnatcher** [comment]
ZIC would look so fire with shards sticking out lol

**Comment by Duzos** [comment]
@Westankrang  needs texture

**Comment by Duzos** [comment]
blue cobble lol

**Comment by Loqor** [comment]
krang made texture yayay
