### ISSUE TITLE
Load times / hanging

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#6]
The teleport either spends a long time on the load terrain screen 
OR
just hangs for a while and eventually sends you there

**Comment by Duzos** [comment]
Load times get improved tenfold upon leaving and reloading the world
this is common with most issues
being fixed by world reload

**Comment by Duzos** [comment]
this could be multiple seperate issues but for now im making it a generic thing
cus unless you do a relog,
placing a tardis
entering/exiting a tardis
placing a console
linking stuff to a console
etc
all temporarily hangs or really lags out your game

**Comment by Duzos** [comment]
I believe this has been fixed.
Reopen if it hasnt
