### ISSUE TITLE
Console Generator is missing some textures

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#605]
![2024-11-20_09 19 44](https://github.com/user-attachments/assets/725e4595-b95d-48db-9a2d-ca7d8aa9ebd8)

**AIT Version:**
ait-1.2.0.908-1.20.1-beta_engine

**Comment by Duzos** [comment]
i'll fix this

**Comment by Loqor** [comment]
fixed

**Comment by Duzos** [comment]
u annotated it with "no model" or whatever yes?
