### ISSUE TITLE
World Load Freezes

### ISSUE THREAD

**Issue by NotGorgo** [amblelabs/ait#611]
So on a world you cannot load back in after you leave it and i get this error whenever i try to change the desktop
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "loqor.ait.core.tardis.handler.SonicHandler.getConsoleSonic()" because the return value of "loqor.ait.core.tardis.Tardis.sonic()" is null

**Comment by 1sckk** [comment]
now i get this error 
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "loqor.ait.core.tardis.handler.travel.TravelHandler.getState()" because the return value of "loqor.ait.core.tardis.Tardis.travel()" is null

**Comment by 1sckk** [comment]
latest bets 923

**Comment by 1sckk** [comment]
[crash-2024-11-26_18.33.02-client.txt](https://github.com/user-attachments/files/17926788/crash-2024-11-26_18.33.02-client.txt)

**Comment by 1sckk** [comment]
[latest.log](https://github.com/user-attachments/files/17926797/latest.log)

**Comment by Duzos** [comment]
what version

**Comment by 1sckk** [comment]
beta 918-923 i cant change interiors or anything and as soon as i leave the tardis the interior is gone and if i leave the world i get load locked

**Comment by Duzos** [comment]
first two things idk about
second one i know about the load locking

**Comment by Duzos** [comment]
load locking seems like an engine issue
