### ISSUE TITLE
changing interiors breaks tardis

### ISSUE THREAD

**Issue by yakirfranko** [amblelabs/ait#612]
dont know if im missing something but after changing interior i built an enclosure for the engine core 3x3x3 filled with water but core wont activate tried sonicing it that did nothing am i missing something?

**Comment by Addi3** [comment]
in 1.1.0 you dont need the water part (the wiki is outdated with some parts)

**Comment by yakirfranko** [comment]
so what should i be doing to activate?

**Comment by Addi3** [comment]
just place it anywhere in the tardis and turn the power on

**Comment by yakirfranko** [comment]
fr?! thanks
