### ISSUE TITLE
Spawning in Overworld when logging onto a server

### ISSUE THREAD

**Issue by Mononoke-star** [amblelabs/ait#617]
**Describe the bug**
Whenever I set my spawn to my TARDIS interior, or otherwise log off inside, I end up underground and suffocating in the Overworld when I log back in much later, likely after a server restart

**To Reproduce**
1. Set spawn in TARDIS, or just generally be inside
2. Log off/server restart?
3. Log in

**Expected behavior**
You'd probably usually spawn inside the TARDIS

**AIT Version:**
1.1.0.1167

**Additional context**
Using Bisect Hosting

**Comment by Duzos** [comment]
known about, is (probs) fixed in 1.2.0
