### ISSUE TITLE
Entities in a specific area do not get deleted on interior change like they should.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#62]
In the interior, entities (namely item frame entities) do not get killed/removed properly.

**Comment by Duzos** [comment]
my 2c
the chunk is not loaded so the item frames cannot stop hanging to become item entities
because once you enter the tardis you can see them floating and then they start ticking and remove themselves

**Comment by Duzos** [comment]
look at AITMod:67

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/2fcdc51b-bd7b-4b48-8089-7a6fc7816025)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/2ece9c94-7ba8-46b8-bce6-84e6e81b9058)

basically, this.

**Comment by Creativious** [comment]
that is a problem tomorrow me can suffer through. I am tired :P

**Comment by Duzos** [comment]
fair
sleep well if you are

**Comment by Duzos** [comment]
Needs doiiing

**Comment by Duzos** [comment]
its because the corners.box thing that we get is shitty and doesnt seem to work for this
ill see if creating a new box from one corner to the other manually fixes this
