### ISSUE TITLE
Multiplayer Sync Issues

### ISSUE THREAD

**Issue by NotGorgo** [amblelabs/ait#643]
**Describe the bug**
When spawning into server it starts by softlocking you and start falling below world then ait tardis's are invisible and dont have any of the componets

**To Reproduce**
1. log onto server
3. kill your self (the player)
4. leave & rejoin world 
5. spawn tardis
6. bam invisible tardis

**Expected behavior**
load into world normal and use tardis
**Screenshots**
![2024-11-30_22 48 33](https://github.com/user-attachments/assets/d39e36aa-194a-4da5-95c3-0caaa1381838)
![2024-11-30_22 48 11](https://github.com/user-attachments/assets/9e0775b7-2c5d-45a9-9826-2b76b403f837)

**AIT Version:**
AIT 1.2.0 beta 956

**Additional context**
just voice chat and the dependency mod owo lib

**Comment by Duzos** [comment]
oh no
