### ISSUE TITLE
SMS drops on interior change

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#651]
remove it
wait what do we do about subsystems when the interior changes

**Comment by MaketendoDev** [comment]
do the lazy route by throwing it out the materials out of the exterior if one exists

**Comment by MaketendoDev** [comment]
it would be funny if the door opens throw the items and closes lol

**Comment by Loqor** [comment]
@Duzos room that jigsaws up to the interiors and moves all the active components with structures there.

**Comment by Duzos** [comment]
i don't want to do something like that without ARS though

**Comment by Duzos** [comment]
chest of all subsystems at door
