### ISSUE TITLE
[1.1.0 fabric] exiting a world while in a tardis causes you to suffocate underground in single player

### ISSUE THREAD

**Issue by kalethemonster** [amblelabs/ait#653]
in single player, if you exit the world, or your game crashes while you are inside a tardis, you end up at the corresponding co-ordinates of your interior in the overworld, which puts you underground given the typical y placement of interiors within the tardis dimension. the first time this happened i was testing in creative and crashed, chalked it up to the consequences of the crash, the second time i had to close the game due to irl stuff, when i next logged in, i was 1000 blocks away from my base, underground, and i would have suffocated if my pickaxe wasn't fully enchanted,, while i havent had the chance to test this on a server, given their technically no-longer client side, i don't think it would affect servers in the same way.

1. create or load a singleplayer world
2. enter a tardis and stand within the interior
3. exit the world
4. re-load the world, and you should be somewhere underground at co-ordinates relevant to the interior of the Tardis you were in.

Expected behaviour:
either load into the interior of the tardis, or if not posible, your last position in the overworld before entering your tardis, or where it would have spit you out in a crash(if flying the tardis when the world is exited)

**Comment by Duzos** [comment]
dupe
