### ISSUE TITLE
Protocol 3 rendering issues after eating Zeiton dust

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#671]
**Describe the bug**
Originally, when you activated Protocol 3, the closer you were to the TARDIS, the clearer you could see it.
But after eating Zeiton Dust, the transparency of the TARDIS's exterior remained the same no matter how far away you were from it.

https://streamable.com/88c931

**AIT Version:**
ait-1.2.0.1030-1.20.1-beta

**Comment by trerrturyy** [comment]
im not a dev but this is intended

**Comment by trerrturyy** [comment]
nevermind proably shoulda watched the video

**Comment by Ouroboros-Games** [comment]
99% sure this is intended

Since that's how zeiton dust worked in my original suggestion for it, you use it to be able to see cloaked TARDISes

**Comment by Duzos** [comment]
feature creature
