### ISSUE TITLE
Cobbled Snowball

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#683]
Snowball item texture with rock chunks inside it
When thrown gives 3 possible effects
- Blindness
- Nausea
- Slowness
Unlocks 29/12

**Comment by Loqor** [comment]
Finished

**Comment by MaketendoDev** [comment]
it do be crashin

**Comment by MaketendoDev** [comment]
i'll see if i can fix it leter but if some one wants to fix it go ahead

**Comment by MaketendoDev** [comment]
turns out its not broken but a silly loqor issue forgetting to disable snowball item
