### ISSUE TITLE
Snow on Telepathic Circuit sends you to Snow Biome

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#685]
title
mixin?
unlocks 31/12

**Comment by Loqor** [comment]
@Duzos you do this code i legitimately cannot be bothered

**Comment by Duzos** [comment]
copy it over from feat/advent i think i already did this one

**Comment by Duzos** [comment]
nah i didn't push

**Comment by Duzos** [comment]
why did brother close it if it's not done

**Comment by Loqor** [comment]
oh you didnt push i see

**Comment by Loqor** [comment]
push just that to main
