### ISSUE TITLE
Ice/Festive TARDIS Exterior

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#690]
choose your favourite variant krang and just add ice and decorations to it

**Comment by Loqor** [comment]
jan 6th, also we should do more for jan 6th

**Comment by MaketendoDev** [comment]
+ dm exteriors maybe?

**Comment by MaketendoDev** [comment]
then we'll have to think for somthing else in its place

**Comment by MaketendoDev** [comment]
or just more iced varients

**Comment by MaketendoDev** [comment]
finsihed
