### ISSUE TITLE
Classic Animation is too long

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#7]
the values of it need adjusting but id prefer if @Loqor did it as hes all fussy about it so he can tinker with it getting it right
poor craig his emails getting spammed while hes tryna snooze

**Comment by Duzos** [comment]
It also starts at the wrong time

**Comment by Duzos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix classic animation values](https://trello.com/c/l95XAgm2/106-fix-classic-animation-values)

**Comment by Duzos** [comment]
shut your gob

**Comment by Creativious** [comment]
HOLY SHIT I FIXED IT
