### ISSUE TITLE
Maiden Voyage fires even if demat fails

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#712]
you get the "maiden voyage" advancement regardless of if your acctualy able to fly or not (lack of demat circuit)

![penut](https://github.com/user-attachments/assets/9b7373ff-e891-4628-a48a-b4331e8443a0)

**Comment by Duzos** [comment]
ill add a `SUCCESSFUL_DEMAT` event and listen to that instead

**Comment by Duzos** [comment]
wait that already exists
