### ISSUE TITLE
Stattenheim remote on tardis' first place causes the exterior to duplicate.

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#73]
Using the stattenheim remote for the first time on relog causes the exterior to duplicate, its really bizarre.

**Comment by Duzos** [comment]
maybe the last exterior pos isnt getting saved correctly so it cant delete the last one?
its defo smth to do with the last exterior not getting deleted
maybe the animation doesnt finish properly / the world is invalid / no position etc

**Comment by Creativious** [comment]
Should be fixed as far as I know.

**Comment by Duzos** [comment]
nuh uh

**Comment by Duzos** [comment]
its even worse now

**Comment by Duzos** [comment]
its bugged out until you enter the interior, which then causes the old one to go invis
could this be an issue with the block breaking mixin maybe

**Comment by Creativious** [comment]
oh my I am going to want to scream now

**Comment by Duzos** [comment]
real
