### ISSUE TITLE
Exterior duplicates with no apparent reasoning behind it

### ISSUE THREAD

**Issue by Loqor** [amblelabs/ait#74]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/65447472/de8a7d7a-a409-42cb-bb55-a00a87dc5f8b)

**Comment by Loqor** [comment]
idk whats going on here it just duplicates itself, its very bizarre too.

**Comment by Loqor** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/65447472/8bca2460-275d-4ead-8d61-b511293710e5)

**Comment by Loqor** [comment]
@Duzos yeah this is what happens when you land, it duplicates the exterior and lands on itself

**Comment by Duzos** [comment]
is this consistent?

**Comment by Loqor** [comment]
> is this consistent?

yes, it happens every time when using autopilot

**Comment by Duzos** [comment]
only if you land on your last position or everytime
might be because of 33247cc4973bbeb02fa3d0701542a1a751b857b6 ( ? )
spamming a materialise method COUUULD cause issues icl
but im no good cooder so tahts how i did it
