### ISSUE TITLE
flag and power converter Particles don't work

### ISSUE THREAD

**Issue by MaketendoDev** [amblelabs/ait#745]
flag and power converter have particles buuuuuuuut they i think have their models generated and i'm not gonna mess with em so you do your stuff

**Comment by Duzos** [comment]
what do mean

**Comment by MaketendoDev** [comment]
its block model is  generated
so you cant manually put item break particles in there

**Comment by MaketendoDev** [comment]
and idk how to choose it by code

**Comment by Loqor** [comment]
fixed
