### ISSUE TITLE
crash when planting the tardis corl

### ISSUE THREAD

**Issue by rat123fuckthissititwasa** [amblelabs/ait#746]
**Describe the bug**
whenever i plant the corl the game crashes

**To Reproduce**
1. place soul sand
2. place the corl
3. crash

**Expected behavior**
after the placement it crashes after a few sec

**Screenshots**
cant catch it

**AIT Version:**
AIT: 1.20.1 aitforge-1.0.5-0.0.1

**Additional context**
Add any other context about the problem here - just the mod

**Comment by rat123fuckthissititwasa** [comment]
i found a fix but the bug is still happening 
fix: go into a rift chunk
but it will crash you if you go to a non rift chunk

**Comment by Duzos** [comment]
1.0.5 isnt supported anymore
