### ISSUE TITLE
Subsystem Structure Generator

### ISSUE THREAD

**Issue by smallmoss233** [amblelabs/ait#748]
Add a quick structure generator for subsystems that need to build structures.

- The quick generator can be made using blueprints.
- It is possible to preview the placement location.
- You can directly place the structures of the activated subsystems into the world.
- Add a subsystem library,through which all subsystems can be directly connected to the engine via the librarys disk.
- Add a corridor type specifically for placing subsystems.
- Connect the subsystems within the room directly to the engines disk.

**Comment by Duzos** [comment]
no can do
