### ISSUE TITLE
TARDIS Crash Problem

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#755]
**Describe the bug**
When you try to pull the throttle to drive your TARDIS after it crashes, the Repair Time will gradually increase until it reaches 7000.
After that, the throttle cannot be turned off.

**To Reproduce**
1. Crash your TARDIS
2. Pull the throttle

**Video**
https://streamable.com/63vgwa

**AIT Version:**
ait-1.2.0.1077-1.20.1-beta

**Comment by Duzos** [comment]
i dont even know how this happens
