### ISSUE TITLE
The ConsoleBlock doesn't sync properly when a player is loading the chunk and then someone walks in.

### ISSUE THREAD

**Issue by Creativious** [amblelabs/ait#77]
this is lovely

**Comment by Duzos** [comment]
it just needs to be resynced when it gets loaded

**Comment by Duzos** [comment]
on server its correct its just client needs to be reminded of whats going on

**Comment by Duzos** [comment]
tried to do that
for some reason the block entity is always null which is why we cant get it to sync it

**Comment by Loqor** [comment]
only for multiplayer, regardless of if someone is hosting or not

**Comment by Loqor** [comment]
this was fixed by using toInitialChunkNbt()
