### ISSUE TITLE
Fabricator shouldnt use up blueprint

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#771]
dosent really make sense + you cant craft them so thats annoying when your gonna need a lota fluid links n all 

maby once you collect your output it'll tell you to collect your blueprint aswell

otherewise a way to dupe them or generaly anything just to allow some reusing

(duzo dont you dare comment "cope" and close this)

**Comment by Duzos** [comment]
co..

**Comment by cyberdragon442** [comment]
Maybe make it copy like a smithing template. So maybe 7 zeiton + book and quill, and put the blueprint in the center to copy.
