### ISSUE TITLE
Fabricator GUI

### ISSUE THREAD

**Issue by Joggester** [amblelabs/ait#772]
make a GUI for the Fabricator pls

**Comment by Addi3** [comment]
I don't see why it would need one, mojang already give every crafting station a gui and u love the way it is rn. How would adding a gui make this better cus the way stuff is made will still be the same

**Comment by Joggester** [comment]
yeah ur right.

**Comment by Joggester** [comment]
add it pls
![mmexport1734409331857](https://github.com/user-attachments/assets/070b20cc-06af-4f64-b911-067bdc210720)

**Comment by Saturnorsomthing** [comment]
gonna just close this since
1. guis are lame
2. fabricator is pretty much aredy done and a gui would mean remaking it which we dont have the time for
3. guis are so lame they get mentioned again

**Comment by Saturnorsomthing** [comment]
wrong kind of closed

**Comment by Addi3** [comment]
Real

**Comment by Joggester** [comment]
😢
