### ISSUE TITLE
Holding stabalizers in invetory causes crash 

### ISSUE THREAD

**Issue by NotGorgo** [amblelabs/ait#778]
**Describe the bug**
holding stabalizers in invetory causes crash in the beta 1091

**To Reproduce**
1. Go to invetory
2. Click on stabalizer
3. put in invetory

**Expected behavior**
not crash when trying to put stabalizer in general core

**Screenshots**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "loqor.ait.core.engine.SubSystem.isEnabled()" because the return value of "loqor.ait.core.engine.block.SubSystemBlockEntity.system()" is null

**AIT Version:**
beta 1.2.0 ver 1091

**Additional context**
just owolib and jei

**Comment by Loqor** [comment]
fixed
