### ISSUE TITLE
red cube

### ISSUE THREAD

**Issue by Jeryn99** [amblelabs/ait#8]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/36424503/8e56ad48-d9cc-4a2b-bbc6-6e7c562cbfb3)

**Comment by Duzos** [comment]
ez

**Comment by Suff99** [comment]
i demand evidence

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/17592eb5-2927-4900-ac6b-6ec41e719167)
There.

**Comment by Suff99** [comment]
so happy

**Comment by Monsterwaill** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/113268818/478d752f-68d6-4433-ad39-f1451da97a94)

**Comment by Duzos** [comment]
if anyone removes this from the mod im deleting the organisation

**Comment by Suff99** [comment]
should do that anyways

**Comment by Duzos** [comment]
@Loqor You removed cube
You know what happens now
