### ISSUE TITLE
DM exterior causes crash upon opening the interior door 

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#820]
[latest.log](https://github.com/user-attachments/files/18251148/latest.log)

**Comment by MaketendoDev** [comment]
server thing i think

**Comment by Duzos** [comment]
`renderInteriorDoorBoti` is causing a crash as `DalekModDoorVariant#adjustPortalPos` returns null, when it should really not override OR you can actually fill in the positions
Id also recommend adding 
`if (!variant.parent().hasPortals()) return;` at the top of the `renderInteriorDoorBoti` method
