### ISSUE TITLE
Split evrything up in diffrent tabs

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#821]
* AIT
>Contains bassicly evry item (or whichever dont have their own category)

* AIT: Maintenance
>Contains the engine,circuits,generalized subsystem core and the fluid links
>Icon would be the engine

* AIT: Fabrication
>Contains all blueprints,the fabricator,the fluid links,manipulator,inductor,glass bulb and the condenser
>Icon would be a blueprint

* AIT: Combat
>bring this back idk why it was removed in the first place lol,since without it its really easy to miss the guns
>Icon would be a gun (murica)

* This makes it easier to see where stuff is and makes the mod appear larger

**Comment by MaketendoDev** [comment]
I don't like the idea of a combat tab that's why I moved it to weapons since it made sense. 🤷

**Comment by MaketendoDev** [comment]
no point making another tab that already exist

**Comment by Saturnorsomthing** [comment]
fair

**Comment by MaketendoDev** [comment]
for fabrication it kinda is the same thing: materials can go in materials tabs and blueprints could go in where like the weird scroll things are

it just to show that the mod fits in with minecraft like a jigsaw piece
