### ISSUE TITLE
add a disk for wonderful time in space

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#823]
h

**Comment by MaketendoDev** [comment]
but..
there is?

**Comment by Addi3** [comment]
there is but it has no texture in game nor the item folder

**Comment by MaketendoDev** [comment]
dam wait one sec

**Comment by Addi3** [comment]
or model

**Comment by Addi3** [comment]
![image](https://github.com/user-attachments/assets/911b0aef-71fa-4acd-a626-4b18308a0be2)

**Comment by MaketendoDev** [comment]
it'll use mercury disc until the music gets compressed
