### ISSUE TITLE
GFNM picture tps 1 block up

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#826]
im pretty sure this is caused either by flying the tardis or exiting then entering (log and video attached)

[latest.log](https://github.com/user-attachments/files/18254285/latest.log)

https://youtu.be/qsAy0mQS6zY

**Comment by MaketendoDev** [comment]
oops thought that was fixed D:

**Comment by Addi3** [comment]
im on ait-1.2.0.1152-1.20.1-beta so idk

**Comment by MaketendoDev** [comment]
yea no it was supposed to be fixed when i made the painting item

**Comment by MaketendoDev** [comment]
![image](https://github.com/user-attachments/assets/5a7860f4-e6c0-416c-bb33-8a0f53e705c1)
guhhh it goes forward too

**Comment by Addi3** [comment]
oof, couldnt you take something from the mojang painting entity code?

**Comment by MaketendoDev** [comment]
ya thats what i did i guess i forgot somthing
