### ISSUE TITLE
 Add Connector support back

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#831]
Ik forge is pretty ass but a lot of people prefer it and when they use 1.0.5 and come to us with issue from that version, we'll yk how people be. So that way we can actually fix issue or if it's a forge issue and not on fabric tell them to cope ig

**Comment by DrTheodor** [comment]
wdym "add connector support back"
iirc it was never removed? in fact, there was no connector support at all?

**Comment by Saturnorsomthing** [comment]
hes refering to the fact that syntra now throws a fit (presumably due to openGL)

**Comment by DrTheodor** [comment]
> hes refering to the fact that syntra now throws a fit (presumably due to openGL)

Well that's a skill issue
We never had any special code to support synitra and we never will

**Comment by Saturnorsomthing** [comment]
im just gonna close this since this isent exactly our issue and more their issue, so rather go report this in syntras git with a log and such and ask them to fix it (also forge sucks)

![cat](https://github.com/user-attachments/assets/9005cdcc-d0c4-4fe6-b05b-abe2f4f42ab3)
