### ISSUE TITLE
hums broken

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#835]
they just dont change even if i leave and re-enter the tardis and relog
### ` beta: ait-1.2.0.1169-1.20.1-beta `

[latest.log](https://github.com/user-attachments/files/18275655/latest.log)

**Comment by nitrogenez** [comment]
4d37a04 - confirmed. the hum changes, but the first one still plays, meaning that the 'new' hum is overlayed over the 'old' one. tracing the bug's origin.

**Comment by Loqor** [comment]
common ait gaslighting (this wasnt a bug)
