### ISSUE TITLE
Classic Animation is so broke and broke many thing

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#85]

**Comment by Duzos** [comment]
solution: remove classic animation
we can just do it again in future time

**Comment by Duzos** [comment]
( animation lengths r wrong which freaks out other stuff kinda )

**Comment by Loqor** [comment]
Way to fix: remove it.

**Comment by Duzos** [comment]
Yeah but also PulsatingAnimation be kinda buggy sometimes? so idk

**Comment by Loqor** [comment]
deprecated, and the pulsating animation is surprisingly fine.
