### ISSUE TITLE
Auto-Pilot Bug | Landing Sound

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#92]
Version: ait-1.0.7-1.20.1-alpha
Issue: I have disengaged both Protocol-116 [Auto-Pilot] & Protocol-813 [Hail Mary], and she still lands automatically.
Landing sound is a chain sound instead of her thud sound. 
https://streamable.com/foszli

**Comment by SpartanGamezFTB** [comment]
the auto pilots been fixed in latest alpha now

**Comment by Duzos** [comment]
okiay
this was because of an issue with HADS
which needs a glance at codewise it might b causing some problems
