### ISSUE TITLE
Interior Doors Hitbox - Immersive Portals

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#99]
**Mod Versions:**
immersive-portals-3.3.7-mc1.20.1-fabric
ait-1.0.10-1.20.1-alpha

**Issue:**
While inside the TARDIS, when trying to use the door, the player can open it from the center, however when closing it, they have to basically look at the floor to find the hitbox which seems to become barely visible. But when the player is outside the doors work just fine when opening/closing looking towards the center of the doors to click the hitbox

**Video:** [Hopefully this can show what I'm referring to]
https://streamable.com/ikm50a

**Comment by Duzos** [comment]
this is known about
to fix probably move the interior portal back a smidge

**Comment by Duzos** [comment]
ahhh you can do it from the outside because youre reaching in to right click on the interior door

**Comment by Duzos** [comment]
@Loqor mate this wasnt fixed?

**Comment by Duzos** [comment]
i dont trust you

**Comment by Duzos** [comment]
knew it

**Comment by Duzos** [comment]
ah wait you extended it on the sides
ic
ehh its ok
